AFLplusplus/LibAFL

libafl/Cargo.toml
libafl/examples/llmp_test/main.rs
libafl/src/bolts/compress.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/shmem.rs
libafl/src/events/llmp.rs

This PR will add Broker 2 Broker communication to LLMP.
In first tests, forwarding didn't seem to work yet (`cargo build --example llmp_test`)

Tcp Broker to Broker Communication

---

fuzzers/frida_libpng/Cargo.toml
fuzzers/frida_libpng/harness.cc
libafl_frida/Cargo.toml
libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs

This should fix #73.
We now only emit the report funclet when we absolutely need to. This should significantly reduce the code bloat, and may improve performance.

frida-asan: Un-inline report funclet to reduce code bloat

---

fuzzers/baby_fuzzer/src/main.rs
fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/mod.rs
libafl/src/executors/timeout.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/lib.rs
libafl/src/observers/map.rs
libafl/src/observers/mod.rs
libafl/src/stages/mutational.rs
libafl/src/state/mod.rs
libafl_frida/src/asan_rt.rs

This PR introduces the HasExecHooks trait for pre_exec and post_exec hooks.
These hooks take the state, the manager and the input as parameters.
Now the hooks are separated from the definition of the Observer trait, otherwise we need to introduce EM, S and I as generics to observers and then feedbacks.
Executors should implement HasExecHooks too, that is now a common interface.

Observers refactor

---

fuzzers/baby_fuzzer/Cargo.toml
fuzzers/baby_fuzzer/src/main.rs
fuzzers/frida_libpng/Cargo.toml
fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/libfuzzer_libmozjpeg/Cargo.toml
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/Cargo.toml
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_stb_image/Cargo.toml
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/Cargo.toml
libafl/src/corpus/testcase.rs
libafl/src/events/llmp.rs
libafl/src/executors/inprocess.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/state/mod.rs
libafl_frida/Cargo.toml
libafl_frida/src/asan_rt.rs

Now FeedbacksTuple is not a thing anymore.
State take just one feedback for the normal feedback and one feedback as objective.
You can use multiple feedbacks composing them in a boolean formula.
For instance `feedback_and!(MyFeedback::new(), feedback_not!(CrashFeedback::new()))` returns an instance of AndFeedback now.

Composing feedback

---

fuzzers/frida_libpng/Cargo.toml
fuzzers/frida_libpng/src/fuzzer.rs
libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/lib.rs

Implements #75.
To ignore a particular error, simply add it's `module-path@offset` to the `suppress instrument-locations` option in the `LIBAFL_FRIDA_OPTIONS` environment variable.

Frida suppress instrumentation locations option

---

libafl/src/feedbacks/mod.rs

#65, #85 
And, Or, Not feedback should append/discard feedback metadata.

add append/discard_metadata for and/or/not feedback

---

fuzzers/baby_fuzzer/src/main.rs
fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_reachability/src/lib.rs
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/src/corpus/queue.rs
libafl/src/events/llmp.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/mod.rs
libafl/src/executors/timeout.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/fuzzer.rs
libafl/src/lib.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/scheduled.rs
libafl/src/observers/map.rs
libafl/src/observers/mod.rs
libafl/src/stages/mod.rs
libafl/src/stages/mutational.rs
libafl/src/state/mod.rs
libafl_frida/src/asan_rt.rs

In this PR, I change the design of LibAFL.
+ Now the Fuzzer is an entity that holds the feedbacks and the scheduler and any other entities that want to do alter entirely the State
+ Now the Feedback can store temporary data as before in its own fields, but needs to rely on FeedbackState to store persistent data (such as the history map) in the State

Introduce FeedbackState and allow Feedbacks to process the entire State

---

fuzzers/baby_fuzzer/src/main.rs
fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_libpng_launcher/src/lib.rs
fuzzers/libfuzzer_reachability/src/lib.rs
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/src/executors/inprocess.rs
libafl/src/lib.rs

This PR alllws the usage of abstract non-binary inputs for the InProcessExecutor. This can be used for ASTs for example.
I hope I found all references, if not I think the CI should fail.

Make InProcessExecutor use a plain Input instead of bytes

---

libafl/src/bolts/rands.rs
libafl/src/generators/mod.rs
libafl/src/mutators/mutations.rs

The choose method takes an ExactSizeIterator and returns a randomly
chosen item from it. Using this method prevents chosing items with an
incorrect upper_bound on the index.
Various macros help with defining and implementing repetitive mutation
strategies.

new Rand method: choose. fixes #117

---

libafl/src/bolts/rands.rs

This is unsed and causes confusion when writing muators.

Remove unused HasRand to avoid confusion with libafl::state::HasRand

---

fuzzers/frida_libpng/Cargo.toml
fuzzers/frida_libpng/src/fuzzer.rs
libafl/src/events/llmp.rs
libafl/src/executors/inprocess.rs
libafl_frida/Cargo.toml
libafl_frida/build.rs
libafl_frida/src/alloc.rs
libafl_frida/src/asan_errors.rs
libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/lib.rs

This PR implements #72, refactoring `asan_rt` to use Frida's interceptor to hook functions instead of the `gothook` crate.
This should be both more portable and more hermetic.
Currently this requires features in https://github.com/frida/frida-rust/pull/18, which is yet to be merged. Should hopefully be merged in the next couple of days.

Hook using frida gum interceptor instead of gothook

---

libafl/src/executors/timeout.rs

Looking back at the TimeoutExecutor(#31), I think we don't need to allocate Timeval or Itimerval struct everytime we call run_targets,
This PR embeds the pre-set Itimerval into TimeoutExecutor struct (for unix only, of course)

Improve TimeoutExecutor

---

fuzzers/frida_libpng/src/fuzzer.rs
libafl_frida/src/alloc.rs
libafl_frida/src/asan_errors.rs
libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs

Fix the following bugs:
- `posix_memalign`/`memalign` hooks had incorrect signatures, resulting in ASAN false-positives
- `realloc` hook did not deal with the case that the `realloc` shrinks the allocation
- when checking the `ModuleMap` to see whether a function should be hooked or not, we did not translate addresses from stalked addresses to real addresses
- somewhere in the merge, the `cfg` attributes on `walk_proc_maps` and `find_mapping_for_path` broke.
- there was an extra call to `stalker.deactivate` resulting from a bad merge.

Fix frida bugs

---

libafl/src/executors/forkserver.rs
libafl/src/executors/mod.rs
libafl/src/executors/timeout.rs

#82 #111 
I've made the TimeoutForkserverExecutor that wraps around the normal ForkserverExecutor and can check timeout also. It can be used similarly as the TimeoutExecutor, (just pass the Executor and the Duration to call the constructor).

Timeout forkserver

---

libafl/src/executors/forkserver.rs

Sorry for making a very small PR.
The call to kill would sometimes fail and return  `Unknown("Sys(ESRCH)")` if the child process has already exited before the call to the kill from the parent, so I modified it to call unwrap instead of `?`.

TimeoutForkserverExecutor fix

---

libafl/src/generators/mod.rs

LibAFL is overusing generics a bit.. :upside_down_face:
It looks like most cases of `PhantomData` are necessary though or would require bigger changes to rip out. Here's one that isn't used in a type bound anywhere.

remove unnecessary generics on RandGenerators

---

libafl/src/observers/mod.rs

On some machines the system clock can be faulty and `start_time` maybe
actually be after the end time. This causes a panic, instead gracefully
just put a None time in `self.last_runtime`
See POC here https://github.com/bitterbit/rust-docker-timetravel-error

Don't panic on time subtraction failure

---

.github/workflows/build_and_test.yml
libafl/Cargo.toml
libafl/src/events/mod.rs
libafl/src/fuzzer.rs

This uses [cargo-hack's](https://github.com/taiki-e/cargo-hack) `--each-feature` to run `cargo check` for every feature on each crate in the workspace. This should only add a few seconds of build time.
`cargo-hack` can also check every combination with `--feature-powerset` but that doesn't seem viable with 9 features :slightly_smiling_face:

check each feature in CI and fix introspection on no_std

---

libafl/Cargo.toml
libafl/src/bolts/tuples.rs

Two small commits:
1. Bumps version to 0.8.2 (0.8.1 had bug with incorrect output for streaming version, doesn't affect this code base)
2. Removes const usage as it is used in non-const context, hence it is going to be waste of time to hope for compile to optimize it or at least I beleive so, but it is optional and if you think it is ok then I'll remove this commit (const version is slower than regular)

Bump xxhash-rust minimal version to fixed one

---

libafl/examples/llmp_test/main.rs
libafl/src/bolts/llmp.rs

With this PR, messages from clients should have the correct sender id assigned to them.
This allows us to filter our own messages.

Fix client_id for outgoing messages

---

libafl/src/bolts/launcher.rs

This PR adds a `spawn_broker` flag to the launcher, that will not spawn a launcher if it set to false. Instead, the main process will wait for its children.
Fixes #128

launchers without brokers (fixes #128)

---

libafl/src/fuzzer.rs
libafl/src/state/mod.rs

The new `load_initial_inputs_forced` method allows a fuzzer author to forcefully add all inputs to a corpus, even if they are not "interesting" (fixes #123)

Added load_initial_inputs_forced (fixes #123)

---

libafl_frida/src/alloc.rs
libafl_frida/src/lib.rs

- Too large allocs should return 0 instead of panicing
- Don't forcibly free unfreed allocations when resetting between tests

frida: small fixes to remove false positives

---

libafl/src/stages/mutational.rs

When using the introspection feature, all statistics appear under Stage 0 instead of being displayed by separately for each stage.
This happens because no one ever calls `finish_stage()`

fix introspection for multiple mutational stages

---

libafl/Cargo.toml
libafl/src/bolts/rands.rs
libafl/src/executors/forkserver.rs
libafl/src/stages/mutational.rs

This PR optionally adds implements `Rng` (or rather, `RngCore`) for all of our Rand implementations.
With this, users can optionally use `rand::Rng` to fill buffers conveniently. This also makes it easy to use microsoft Lain for input generation, without having to fall back to slow randomness.

Implemented rand::Rng for libafl::Rand as feature flag

---

libafl/src/executors/forkserver.rs

Maybe I'm misunderstanding, so if this is the case no worries just let me know. 
If a testcase times out when run by `TimeoutForkserverExecutor`, it will send a kill signal to the `child_pid` and mark `self.executor.forkserver().last_run_timed_out()` to a non zero value. Then, all sequential calls to `run_target` will send a non zero value on the CTL pipe. 
I think this is a problem as we should send a non-zero value only once. If not, we will hit `waitpid(child_pid...)` more than once, which by the second time will block. 
_The relevant code in afl_forkserver inside qemu_
```c
while (1) {
// forkserver reading the CTL pipe
if (read(FORKSRV_FD, &was_killed, 4) != 4) exit(2);
if (child_stopped && was_killed) {
child_stopped = 0;
if (waitpid(child_pid, &status, 0) < 0) exit(8);
}
// ...
} …
```

Fix TimeoutForkserverExecutor blocking on testcase timeout

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

I just accidentally opened a issue in afl++ and noticed they have shiny issue templates.

Add simple issue templates

---

fuzzers/generic_inmemory/src/lib.rs
libafl/src/bolts/llmp.rs

This PR reapplys 6d2074bd7e2c7cdaba57a1a5b1c93886e9675663 that must have gotten lost in a merge.
See discussion in #193

Refix Shm ID

---

libafl/src/events/llmp.rs
libafl/src/events/mod.rs

This PR should make it easy to identify which client is currently running, and to enable and sdisable features because of it.

Added mgr_id to EventManager

---

libafl/Cargo.toml

Without setting branch = "main", `cargo build` gives me this error
```
toka@desktop:~/LibAFL$ cargo build --release
Updating git repository `https://github.com/domenukk/tuple_list`
error: failed to get `tuple_list` as a dependency of package `libafl v0.5.0 (/home/toka/LibAFL/libafl)`
Caused by:
failed to load source for dependency `tuple_list`
Caused by:
Unable to update https://github.com/domenukk/tuple_list
Caused by:
failed to find branch `master`
Caused by:
cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```

Branch = "main" in Cargo.toml

---

fuzzers/fuzzbench/src/lib.rs
libafl/src/events/simple.rs
libafl/src/lib.rs

This PR loads the corpus size stats after crash/timeout.
It does not reload the exec counter, though, as there is no place during fuzzing where we would have access to this information. We'd need some dirty hackery for that, I think. Probably not worth it(?)

Reload corpus size after restart (addresses #210)

---

libafl/src/bolts/staterestore.rs

When opening the tmpfile to write to, `File::create` should be used instead of `File::open`.

staterestore `File::open` should be `File::create`

---

libafl/src/bolts/staterestore.rs

Previously, the fuzzer would fill up the tmp folder after crashes/restarts. This PR prunes them on `.reset()`

StateRestorer.reset() removes old tmpfile

---

Cargo.toml
Dockerfile
fuzzers/libfuzzer_stb_image_concolic/fuzzer/Cargo.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/build.rs
libafl_concolic/symcc_libafl/Cargo.toml
libafl_concolic/symcc_libafl/src/lib.rs
libafl_concolic/symcc_runtime/Cargo.toml
libafl_concolic/symcc_runtime/build.rs

This PR introduces a separate crate that contains just the symcc repo url and commit hash to be shared between the different crates. Also contains code to clone and build symcc from build scripts.

Separate symcc crate

---

fuzzers/libfuzzer_stb_image_concolic/fuzzer/Cargo.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
fuzzers/libfuzzer_stb_image_concolic/runtime/src/lib.rs
libafl/src/stages/concolic.rs

Fixes a bunch of issues with the concolic example fuzzer. Now it is actually doing useful stuff :) 
Notably, this PR also contains changes that allow the example fuzzer to be run in concolic or non-concolic mode. The concolic mode only does concolic tracing+solving and non-concolic mode only does i2s+traditional fuzzing (same as lifuzzer_stb_image fuzzer).

Concolic example fuzzer fixes

---

.dockerignore
Dockerfile

Copy crates and scripts from `libafl_concolic` folder to docker image.
Tested this by running the smoke test in the produced image.

Address Dockerfile issues

---

.devcontainer/devcontainer.json

This adds a basic VS Code [development container](https://code.visualstudio.com/docs/remote/containers) configuration.
It uses the already provided Dockerfile in the root of this repository and additionally installs the rust-analyser extension. It is also configured to enable gdb inside the container (requires some flags with docker). 
Note that any user of VS Code can create this configuration by themselves, so this PR is really more of a suggestion to make setup easier for those of us who use VS Code with development containers. The general benefits include: not messing up your system with global state, having a development setup that "just works" without manual configuration and enabling coding in a linux based system while running macOS or Windows on your actual hardware. There is …

add vscode development container configuration

---

fuzzers/libfuzzer_libpng/Makefile
fuzzers/libfuzzer_libpng_launcher/Makefile
fuzzers/libfuzzer_libpng_launcher/src/lib.rs

Apparently, `libtool` for libpng uses the system `gcc` command instead of honoring the `CC` env variable (?)
To address #252, it was enough to disable the (failing) creation of a shared library in libpng's `configure`.
That did the trick, although it'd still be interesting to know a better fix in case someone ever needs a shared object.

Bring back libpng CI on MacOS

---

libafl/src/bolts/os/unix_shmem_server.rs

This PR adds an internal env variable that tells subsequent calls to `ShMemProvider` to not try to spawn a `ShMemService`.
This should keep thread and mutex use to a minimum.

shmem service speedup env

---

libafl_frida/src/asan_rt.rs

The following functions are GNU extensions and therefore not available on superior systems:
- explicit_bzero
- malloc_usable_size
- memalign
- memrchr

libafl_frida: remove non-gnu hooks on macos

---

fuzzers/baby_fuzzer/Cargo.toml
fuzzers/baby_no_std/Cargo.toml
fuzzers/forkserver_simple/Cargo.toml
fuzzers/frida_libpng/Cargo.toml
fuzzers/fuzzbench/Cargo.toml
fuzzers/fuzzbench_qemu/Cargo.toml
fuzzers/generic_inmemory/Cargo.toml
fuzzers/libfuzzer_libmozjpeg/Cargo.toml
fuzzers/libfuzzer_libpng/Cargo.toml
fuzzers/libfuzzer_libpng_launcher/Cargo.toml
fuzzers/libfuzzer_reachability/Cargo.toml
fuzzers/libfuzzer_stb_image/Cargo.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/Cargo.toml
fuzzers/libfuzzer_stb_image_sugar/Cargo.toml
libafl/Cargo.toml
libafl_cc/Cargo.toml
libafl_concolic/symcc_runtime/Cargo.toml
libafl_derive/Cargo.toml
libafl_frida/Cargo.toml
libafl_qemu/Cargo.toml
libafl_sugar/Cargo.toml
libafl_targets/Cargo.toml

this changes the dependency version of libafl to the next released version (0.6) to prepare for the release of the next version of libafl (0.6.0)

symcc_runtime dependency fix for next libafl version & bump to 0.6.0

---

.gitmodules
libafl_concolic/symcc_runtime/Cargo.toml
libafl_concolic/symcc_runtime/build.rs

symcc_runtime doesn't build on docs.rs, because the worker there does not have access to the network and the build.rs script attempts to download symcc from git.
the workaround to this problem is to include symcc as a submodule which will be included in the packaged crate file, so no network access is necessary to build the symcc_runtime on docs.rs.
This does add a submodule to the repository.

Symcc runtime docsrs fix

---

libafl/src/bolts/llmp.rs

#284 
with "0.0.0.0" windows gives this error `The requested address is not valid in its context. (os error 10049)` when broker2broker is used.

Fix _LLMP_BIND_ADDR for Windows

---

fuzzers/baby_no_std/src/main.rs
libafl/src/bolts/mod.rs

Added the possibility to create a custom current_millis function for no_std environments (e.g. custom OS, microcontroller, etc.)

Use external, custom time function for no_std environments

---

libafl/src/bolts/launcher.rs

When launching, sleep for **index** seconds between cores instead of for **id**. This makes life much better when launching on e.g. cores 20-30, as you don't need to wait 20 seconds before fuzzing commences.

Sleep for `index` rather than `id`

---

fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/generic_inmemory/src/lib.rs
fuzzers/libfuzzer_libpng_launcher/src/lib.rs
libafl/src/bolts/launcher.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

This allows you to do per-core configuration such as setting a core-id-suffixed corpus directory.

Add core_id to launcher `run_client` closure signature

---

libafl/src/bolts/llmp.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/executors/inprocess.rs

The ucontext_t and mcontext_t structs are missing in libc for 32 bit armv7 (e.g., rust target armv7-unknown-linux-gnueabihf).
Adding their definitions enables compilation for such targets.

armv7 support: add ucontext struct definition

---

.github/workflows/build_and_test.yml
Dockerfile
fuzzers/baby_fuzzer/src/main.rs
fuzzers/libfuzzer_reachability/src/lib.rs
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/src/bolts/llmp.rs
libafl/src/stages/concolic.rs
libafl/src/stats/mod.rs
libafl/src/stats/multi.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/lib.rs
libafl_targets/src/sancov_pcguard.rs

This PR ignores the `python` feature that needs its own tool to build

Fixed CI by ignoring python, resolved multiple warnings

---

libafl/build.rs
libafl_frida/src/helper.rs

very small pr; I noticed two warnings popping up when I upgraded rust to the latest
```
note: the built-in attribute `allow` will be ignored, since it's applied to the macro invocation `windows::build`
--> C:\Users\toka9\source\repos\LibAFL\libafl\build.rs:9:5
9 |     windows::build!(
|     ^^^^^^^^^^^^^^
warning: `libafl` (build script) generated 1 warning
Compiling frida_libpng v0.6.1 (C:\Users\toka9\source\repos\LibAFL\fuzzers\frida_libpng)
warning: unused import: `CpuContext`
--> C:\Users\toka9\source\repos\LibAFL\libafl_frida\src\helper.rs:26:5
|
26 |     CpuContext, ModuleDetails, ModuleMap,
|     ^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `libafl_frida` (lib) generated 1 warning
warning: Now compile libpng with either visual studio or msys2
Finished …
```

Fix warnings for windows

---

fuzzers/baby_fuzzer_gramatron/src/main.rs
libafl/Cargo.toml
libafl/src/bolts/launcher.rs
libafl/src/bolts/mod.rs
libafl/src/events/llmp.rs
libafl/src/events/simple.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/mod.rs
libafl_frida/src/alloc.rs

This allows us to disable fork when using Restarting Mgr and Launcher, for use cases that don't support `fork` (such as threaded applications)

Fork feature flag to disable fork in Launcher

---

libafl/src/feedbacks/map.rs

Just a wrong doc string I stumbled upon

Fix MaxReducer docstring

---

libafl/src/bolts/llmp.rs
libafl/src/bolts/shmem.rs

This fixes a warning in nightly rust.
So far, we moved a Rc<RefCell> to a background thread, but actually can just recreate the provider.

Fixed potential unsoundness due to Rc threading for ShMemProvider

---

libafl/Cargo.toml
libafl/src/bolts/minibsod.rs
libafl/src/bolts/mod.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/executors/inprocess.rs

Add's the minibsod bolt, which provides `mini-Blue Screen of Death` output on crashes, including register dump, backtrace and mappings.

Add minibsod

---

libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs

Fixes missing/broken cfg directives from @tokatoka's frida-asan-x86_64 PR.

Fix cfg directives for frida-asan

---

libafl/src/bolts/minibsod.rs
libafl/src/bolts/os/unix_signals.rs

This allows a user to dump registers at any point in time.

make dump_registers method public

---

libafl/Cargo.toml
libafl/src/feedbacks/map.rs
libafl/src/observers/map.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/power.rs
libafl_qemu/Cargo.toml
libafl_qemu/src/emu.rs

This adds a new feedback that only tracks new testcases if the edges count has at least a pow2 distance to the last

implemented MapMaxPow2Feedback

---

libafl/src/observers/cmp.rs

Fix staterestore

---

libafl/src/bolts/minibsod.rs
libafl/src/bolts/os/unix_signals.rs

Implements the missing helper functions for dumping on crash for 32 bit ARM.

dump_registers and write_crash for armv7

---

libafl/src/feedbacks/map.rs
libafl/src/observers/map.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/power.rs

As @vanhauser-thc noticed, the map in a map observer is not necessarily debuggable.
Since it needs to be serializable, though, we can always implement debug for it.

make map debuggable

---

fuzzers/forkserver_simple/Cargo.toml
fuzzers/forkserver_simple/README.md
fuzzers/forkserver_simple/src/main.rs

This pr removes hardcoded paths from forkserver example, and use clap to make it look more decent

better forkserver example

---

libafl/src/executors/timeout.rs

This PR adds a `set_timeout` function to the `TimeoutExecutor`, allowing to change the desired timeout at runtime.

add set_timeout fn to TimeoutExecutor

---

libafl/src/executors/forkserver.rs
libafl_sugar/src/forkserver.rs

mainly for @epi052, now the map size is a generic parameter (ForkserverBytesCoverageSugar was WIP).
for the "I want a fixed header in my input" the right, generic way to do it is create a new Input wrapping BytesInput and then adding the header in target_bytes()

Debug output for forkserver

---

libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/executor.rs

This pr fixes map_to_shadow! macro
The current map_to_shadow does not work in some cases.
For instance, let's suppose we have shadow_bit = 44 and the address (to concvert) is 0xffffcf608000.
We want to get 0x2ffff9ec1000 as the shadow address but the current implementation gives us 0xffff9ec1000 
- TODO

Frida shadow fix

---

libafl_frida/src/alloc.rs
libafl_frida/src/lib.rs

Also sets the shadow-bit options to 44 and 36 instead of 46 and 36. 46 does not work on aarch64-linux.

Implement max total allocation size for frida asan

---

libafl_frida/src/asan/hook_funcs.rs

Otherwise it will report false positives.

Fix strncmp hook to only check the length of the needle string

---

libafl_qemu/build.rs

I noticed qemu was only building on one core, so I debugged the jobs environment variable. Evidently cargo forwards `CARGO_BUILD_JOBS` to build.rs scripts as `NUM_JOBS`. Other env vars for build.rs can be found [here](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts)

[libafl_qemu] fix build.rs

---

libafl_qemu/build.rs

`libqasan/libqasan.so` never exists during a normal `cargo build` because the .so is built directly to the target_dir, not in the source directory. This missing file was triggering cargo to rerun the build script every time a user of this library made an incremental change to their code.
pointing `rerun-if-changed` to a directory will make cargo rerun build.rs if any file in that directory changes.
Big thanks to bjorn3 and Eric Huss on the rust zulip for helping me track down the reason cargo was rerunning build.rs:
https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/.E2.9C.94.20cargo.20explain.20reason.20for.20running.20build.2Ers.20again.3F

[libafl_qemu] prevent unneeded build.rs runs

---

libafl_qemu/src/i386.rs

The `Regs` enum was defined out of order, leading to incorrect results from `emu.read_reg` for i386. I found the correct ordering defined [here](https://github.com/AFLplusplus/qemu-libafl-bridge/blob/cabf9862e42ffeab9de9b1bfa12cddaf125c53e8/target/i386/cpu.h#L46-L54).

[libafl_qemu] fix i386 Regs values

---

libafl/src/events/simple.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/with_observers.rs
libafl/src/feedbacks/mod.rs

this pr sorts the type parameters
I skimmed through every impl and that was a pita 🥙

Reorder type parameters in the correct order

---

libafl/src/lib.rs
libafl_cc/src/lib.rs
libafl_derive/src/lib.rs
libafl_frida/src/lib.rs
libafl_sugar/src/lib.rs
libafl_targets/src/lib.rs

This makes rustc less pedantic for debug builds

Disable pita 🥙 compiler in debug mode

---

libafl_frida/src/helper.rs

We really need CI for frida windows. This is so fragile

Fix windows build

---

libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/lib.rs

With this pr we try every possible shadow bit and make sure it is valid (by enumerating existing memory ranges and checking they don't collide)

Shadow bit

---

libafl/src/executors/inprocess.rs
libafl_cc/build.rs
libafl_frida/src/lib.rs

This pr fixes 
1) a race condition on when crash handler are called right after timer handler finishes its execution
2) set `enable_asan_allocation_backtraces` to false by default. It does not work with amd64 asan
I don't know why, but my guess is alloc() calls _hooked_ malloc() which recursively alloc() (?)

Various Fixes (windows timeout race & frida options)

---

libafl/src/state/mod.rs

Fix typo in documentation of libafl::state::StdState

---

fuzzers/forkserver_simple/src/main.rs

The `debug_child` command line argument presence was not properly checked,
so it couldn't be set to true. Hence it was not possible to print out
the content of the buffer sent to the harness while fuzzing.

Fix debug_child arg in forkserver_simple example

---

fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/qemu_launcher/src/fuzzer.rs
libafl_qemu/src/emu.rs

Methods read_mem and write_mem now operate on &[u8], not &[T]
The generic T slice interface was prone to various footguns:
* i32 is the default Rust integer type, but buffers are often expected
to hold u8. This means the following code writes 16 bytes to the
guest, not 4:
let buf = [0; 4];
emu.write_mem(addr, &buf);
* If a buffer of 16-bit or larger integers (&[u64] for example) is
needed to read/write, the user will need to consider host/guest
endianness. The byte array methods in std are a good, explicit
alternative.
Perhaps libafl_qemu could expose/define "to/from guest endianness"
helper functions or extension traits using the established cfg flags,
so that guest endianness is always right by default.
* emu::read_mem causes insta-UB if a user did something like:
let mut my_bool = …

[libafl_qemu] simplify emu::{read,write}_mem

---

libafl_sugar/src/lib.rs
libafl_sugar/src/qemu.rs

re: https://discord.com/channels/736989425770168422/745844821800779786/935105388527902740
Of note: 
- all add'l options are optional, so existing users of the python api shouldn't have breakage
- the TypedBuilder with generics prevented me from doing conditional build steps, so i updated the rust struct to accept Options instead of stripping them off
- for my personal target that i used this on, i needed to call exit(0) after on_restart; i left that off with the expectation that it was just my target
- i registered the forkserver python sugar in lib.rs, lmk if leaving it out was intentional, and i'll remove it

Expose more options to python qemu sugar

---

libafl_sugar/src/forkserver.rs

Closes #499 
changes are largely the same as those found in the qemu sugar. 
I tested using variations of the following code, against `forkserver_simple`. Similar to my patch for [exercise-5](https://github.com/epi052/fuzzing-101-solutions/blob/main/exercise-5/libafl_sugar_qemu.patch#L37), i had to use `exit(0)` for the fuzzer to actually respawn. I suspect the same is needed for qemu, since it appears to be not just my target. 
I exposed `use_cmplog` to keep the API's uniform, and emit a warning when used, as it's not implemented in the sugar itself.
```python
from pylibafl import qemu, sugar
sugar.ForkserverBytesCoverageSugar(
["corpus"], "crashes", 1336, [0], iterations=1000, use_cmplog=True
).run("./program", [])
```

extend python forkserver api

---

libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

closes #498 
same changes, different sugar
i didn't have a good way to test this quickly. tried generic_inmemory compiled to .so via afl-gcc-fast with ctypes, but then couldn't resolve symbols at runtime on the python side. Aside from that, the api can be called, params passed in, etc. 
I poked around afl++ directory for the proper libs to link etc, but ran out of time.  Leaving it here for now 
```
import ctypes
from pylibafl import sugar
fuzz_so = ctypes.CDLL("./fuzz.so")
toi = fuzz_so["LLVMFuzzerTestOneInput"]
def harness(buffer):
toi(buffer, len(buffer))
sugar.InMemoryBytesCoverageSugar(
["corpus"], "crashes", 1336, [0], iterations=1, use_cmplog=True
).run(harness)
```

extended inmemory; added exit to qemu

---

libafl/src/bolts/cli.rs

simplifies ergonomics related to destructuring the SubCommand enum. 
re: https://discord.com/channels/736989425770168422/737602414395260970/937984800239779850
At a glance, this works. ~~I need to update the documentation~~ if this is the route we want to take. Mainly wanted to get a working example for @s1341 to play with for comparison.
With these changes, main can look like 
```rust
fn main() {
let parsed = parse_args();
if parsed.replay.is_some() {
replay(parsed);
} else {
fuzz(parsed);
}
}
```
With signatures being
```rust
fn replay(options: FuzzerOptions) -> Result<(), Error> {}
fn fuzz(options: FuzzerOptions) -> Result<(), Error> {}
```
Leaving this as WIP for now until we know which API we want for the cli. Pinging @evanrichter since he was the main proponent of subcommands.

removed subcommands from FuzzerOptions

---

libafl/src/bolts/fs.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/executors/combined.rs
libafl/src/executors/command.rs
libafl/src/executors/differential.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/mod.rs
libafl/src/feedbacks/differential.rs
libafl/src/feedbacks/mod.rs
libafl/src/observers/mod.rs
libafl/src/observers/stacktrace.rs
libafl/src/observers/stdio.rs

This PR adds a few features to better support differential fuzzing.

Differential executor, diff feedback, stdio observers for command executor

---

libafl/src/feedbacks/differential.rs

This makes it a tiny bit faster to know if something `is_diff` or `is_equal`

Shorthand for differential fuzzing results

---

fuzzers/libfuzzer_libpng_accounting/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_ctx/src/bin/libafl_cc.rs
libafl_cc/src/clang.rs
libafl_cc/src/coverage-accounting-pass.cc

Implemented [TortoiseFuzz](https://www.ndss-symposium.org/wp-content/uploads/2020/02/24422-paper.pdf)'s function call level granularity for coverage accounting. I'll add loop level granularity in a separate PR.

Add function call level granularity for coverage accounting

---

libafl_qemu/src/hooks.rs

Closure hooks are going to be super useful, but I ran into a drop issue when I tried the following change:
```diff
-static mut COV_SOCKET: Option<TcpStream> = None;
-
-/// Send PC over a local TCP socket so that another process can record and format the data
-///
-/// SAFETY: This function must only be called from one thread at a time
-unsafe fn block_exec(_emu: &Emulator, pc: u64) {
-    unsafe {
-        let pc = pc as u32;
-        let mut sock = COV_SOCKET.take().unwrap();
-        sock.write_all(&pc.to_ne_bytes()).unwrap();
-        COV_SOCKET.replace(sock);
-    }
-}
-
// Useful for crash minimization with afl-tmin (from the stock AFL++ project)
// Usage:
//     AFL_NO_FORKSRV=1 AFL_DEBUG=1 \
@@ -650,17 +633,17 @@ pub fn repro(emu: &PreppedEmulator, config: ReproConfig) {
let …
```

Prevent dropping variables in closure hooks

---

libafl/src/corpus/accounting.rs
libafl/src/corpus/fav_factor.rs
libafl/src/corpus/minimizer.rs
libafl/src/corpus/mod.rs
libafl/src/corpus/probabilistic_sampling.rs
libafl/src/lib.rs

This PR moves `FavFactor` to a different file and implements a probabilistic sampling corpus scheduler. This scheduler can be useful for implementing [TortoiseFuzz](https://www.ndss-symposium.org/wp-content/uploads/2020/02/24422-paper.pdf), directed fuzzing, etc.

Add probabilistic sampling corpus scheduler

---

libafl_cc/Cargo.toml
libafl_cc/src/afl-coverage-pass.cc
libafl_cc/src/cfg.rs
libafl_cc/src/lib.rs

I am trying to implement PANGOLIN, AFLGo, DigFuzz, etc. in LibAFL, which all needs control flow graph info. This PR adds code to AFLCoverage pass to dump the CFG into a readable file and to libafl_cc to parse such file. 
For libpng, such dump file is ~700KB and parsing it takes <0.1s.

Dump Control Flow Graph in AFLCoverage LLVM Pass

---

libafl_frida/src/executor.rs

My VScode's rust-analyzer wants this fix
`this operation is unsafe and requires an unsafe function or block`

Fix unsafe bracket

---

fuzzers/libfuzzer_libpng/Cargo.toml
fuzzers/libfuzzer_libpng/Makefile.toml
fuzzers/libfuzzer_libpng/src/lib.rs
libafl/src/bolts/llmp.rs
libafl/src/events/llmp.rs
libafl/src/events/simple.rs
libafl/src/monitors/mod.rs

After the first restart, the sender was no longer set.
This PR re-reads the correct sender from the initialized page.
The sender data is now redundant in an env and the page, I guess this could be cleaned up further in the future.

Sender id fix

---

libafl/src/executors/inprocess.rs

This commit modifies the imports of `ucontext_t` in inprocess.rs to use the local definitions in **bolts::os::unix_signals**.
Here, we added custom structs for armv7, as the libc crate for this arch does not feature a `ucontext_t` definition.

Use ucontext from bolts::os::unix_signals for armv7 support

---

fuzzers/backtrace_baby_fuzzers/forkserver_executor/src/main.rs
fuzzers/forkserver_simple/src/main.rs
libafl/src/executors/forkserver.rs

Fixes #611, an issue where `StdShMemProvider` does not work properly on Macs with targets compiled with `afl-cc`.
Since that particular combination seems to not be used frequently, I fixed the issue by using `UnixShMemProvider` in `forkserver_simple` and `backtrace_baby_fuzzers/forkserver_executor`, controlled by a cfg
One issue I ran into is that `ForkserverExecutorBuilder` only implemented `autotokens` and `parse_afl_cmdline` when ForkserverExecutorBuilder used a `StdShMemProvider` as its generic type (idk if my wording here is proper). All I did was change which impl block those two functions were put in.

Fixes forkersever_simple issue on Macs

---

fuzzers/fuzzbench/src/lib.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/fuzzbench_text/src/lib.rs
fuzzers/fuzzbench_weighted/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
fuzzers/tutorial/src/lib.rs
libafl/src/corpus/mod.rs
libafl/src/corpus/testcase.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/testcase_score.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/power.rs

- Rename PowerSchedulerMetadata to SchedulerMetadata, and PowerSchedulerTestcaseMetadata to SchedulerTestcaseMetadata, as these data are likely to be used in other schedulers.
- Add these metadata in `Scheduler` not in `Stage`

Make weigthed scheduler independent of powersheduler stage

---

libafl/src/stages/calibrate.rs

use reset_map() , not pre_exec_all() in calibration stage.
I originally thought that post_exec_all() is missing from calibration stage, but adding the post_exec_all() would cost additional cost
What we want is resetting the map every time before running the harness, so I change it to call to reset_map() instead of pre_exec_all()

Call post_exec_all() in calibrate.rs

---

libafl/src/bolts/core_affinity.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/minibsod.rs
libafl/src/bolts/os/unix_shmem_server.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/events/llmp.rs
libafl/src/executors/command.rs
libafl/src/executors/inprocess.rs
libafl/src/lib.rs

The `libc` crate is potentially broken, see https://github.com/rust-lang/libc/issues/2812 leading to a segfault.
Also, aarch64 macOS doesn't support core affinity on a kernel level, so we ignore it, instead of crashing.
(or should we report this error and leave it up to the user? cc @andreafioraldi )

Apple aarch64 fixes

---

fuzzers/libfuzzer_libpng_launcher/.gitignore
fuzzers/libfuzzer_libpng_launcher/src/lib.rs
libafl/src/bolts/launcher.rs
libafl/src/bolts/os/unix_shmem_server.rs
libafl/src/feedbacks/map.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/mod.rs
libafl/src/observers/mod.rs
libafl/src/stages/sync.rs
libafl_cc/src/cfg.rs

The env var LIBAFL_DEBUG_OUTPUT avoid to close stderr and stdout of the launcher children for debugging

LIBAFL_DEBUG_OUTPUT in Launcher and OnDiskTOMLMonitor to create fuzzer_stats

---

libafl/src/stages/calibrate.rs
libafl_qemu/build_linux.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/hooks.rs
libafl_qemu/src/lib.rs

The use case is to allow a frontend fuzzer to expose commands such as `monitor input-location 0xababcafe 42` and `monitor start-fuzzing` to avoid to write an harness and fuzz from GDB connected to qemu user.

Add custom GDB commands to libafl_qemu

---

fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/qemu_launcher/src/fuzzer.rs
libafl/Cargo.toml
libafl/src/lib.rs
libafl/src/monitors/tui/ui.rs
libafl_qemu/Cargo.toml
libafl_qemu/build_linux.rs
libafl_qemu/src/aarch64.rs
libafl_qemu/src/arm.rs
libafl_qemu/src/asan.rs
libafl_qemu/src/calls.rs
libafl_qemu/src/cmplog.rs
libafl_qemu/src/edges.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/helper.rs
libafl_qemu/src/hooks.rs
libafl_qemu/src/i386.rs
libafl_qemu/src/lib.rs
libafl_qemu/src/snapshot.rs
libafl_qemu/src/x86_64.rs
libafl_sugar/src/qemu.rs

The new hook system will allow multiple generation hooks (translation time). This will open the window to generation hooks that analyze the code and insert generic hooks to single instruction, for instance for call stack tracking.

New hooks for libafl_qemu

---

libafl/src/feedbacks/map.rs
libafl/src/monitors/tui/ui.rs

VariableObserver doesn't work for this commit. https://github.com/AFLplusplus/LibAFL/pull/665/commits/89403e024156eab7e0b418f0e5eb58452b9c9b44
It's already patched from calibration stage side, but this code here in feedback/map.rs is wrong so I change usable_change to len.

Fix feedback from #665 & Fmt

---

libafl/src/mutators/mutations.rs

Only a small change but it still broke my application so it would be nice to have it upstream

Remove unused trait bounds from BytesSwapMutator

---

libafl/src/mutators/mutations.rs

Change the ByteNegMutator to negate a byte, not flip it. Flipping a byte is already implemented in ByteFlipMutator.
See issue: https://github.com/AFLplusplus/LibAFL/issues/674

Make ByteNegMutator negate, not flip

---

fuzzers/baby_fuzzer/Cargo.toml
fuzzers/baby_fuzzer/src/main.rs
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs

Using the TuiMonitor instead of the SimpleMonitor in the baby_fuzzer breaks the terminal in which the fuzzer runs as soon as the main thread panics and thus kills all threads.
Reproduce:
- Ubuntu 20.04
- GNOME Terminal
- Replace SimpleMonitor by TuiMonitor (see changes to `fuzzer/baby_fuzzer/src/main.rs`)
- Run fuzzer
Minor:
- Check clients != 0 in tui to avoid sub_overflow

TUI monitor breaks the terminal if main thread panics

---

fuzzers/baby_fuzzer_gramatron/Cargo.toml
fuzzers/baby_fuzzer_grimoire/Cargo.toml
fuzzers/baby_fuzzer_nautilus/Cargo.toml
fuzzers/baby_fuzzer_tokens/Cargo.toml
fuzzers/backtrace_baby_fuzzers/c_code_with_inprocess_executor/Cargo.toml
fuzzers/fuzzbench_text/Cargo.toml
fuzzers/fuzzbench_weighted/Cargo.toml
fuzzers/libfuzzer_libmozjpeg/Makefile.toml
fuzzers/libfuzzer_libpng_accounting/Cargo.toml
fuzzers/libfuzzer_libpng_accounting/Makefile.toml
fuzzers/libfuzzer_libpng_ctx/Cargo.toml
fuzzers/libfuzzer_libpng_ctx/Makefile.toml
fuzzers/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/libfuzzer_stb_image_sugar/Cargo.toml
fuzzers/libfuzzer_stb_image_sugar/Makefile.toml

Cargo spits out a bunch of `duplicate package` warnings when scanning the repo checkout of `libafl = { git = "..." }` for `Cargo.toml`s:
```
warning: skipping duplicate package `baby_fuzzer` found at `~/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/c45b6be/fuzzers/baby_fuzzer_nautilus`
warning: skipping duplicate package `fuzzbench` found at `~/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/c45b6be/fuzzers/fuzzbench_text`
[...]
```

Cleanup duplicate package warnings

---

libafl_targets/src/coverage.rs

I think I was confused when I pushed #703 
#614 intends to fix runtime error when there're no token, but with #703 I changed the LLVM Pass back to the original state, then now it fails again when there're no tokens.
So this time just return Tokens::default(), no Err

Fix Autotokens

---

libafl/src/bolts/mod.rs
libafl/src/lib.rs

`use libafl::prelude::*` to import most of the components in libafl

Prelude module

---

libafl/src/bolts/mod.rs
libafl/src/feedbacks/map.rs
libafl/src/observers/map.rs
libafl/src/stages/calibrate.rs

This brings back iterators to HitcountsMapObserver.
I would be surprised if it were a lot slower, @tokatoka pleas check :)

Add HitcountsIterableMapObserver, rename AsMutIter to AsIterMut

---

libafl/src/feedbacks/map.rs

Currently MinMapFeedback does not work because the coverage map is initialized with T::default() (in most cases, 0)
So 
- add another reset_with_value API 
- resize them with observer.inital() in is_interesting

Resize MapFeedbackMetadata with observer.initial()

---

libafl/src/monitors/mod.rs

Clone was not implemented for the NopMonitor which made it incompatible with the launcher

Deriving Clone for NopMonitor

---

scripts/fmt_all.sh

This fixes the warnings in `fmt`, caused by rustfmt.toml

Use nightly fmt

---

libafl_qemu/src/aarch64.rs

Typo lead to fail to compile for arm64

fix typo in aarch64.rs

---

libafl_cc/build.rs
libafl_cc/src/clang.rs

https://github.com/llvm/llvm-project/issues/56137
The new pass manager still needs `-Xclang -load -Xclang -<pass>.so` if we want to load additional arguments

New Pass Manager Arguments

---

libafl/src/monitors/tui/ui.rs

Running libAFL fuzzer (`syheliel`'s nyx-standalone) TUI with 1 client (1 bound cpu) , starts you off on client `#1` screen (when it should be 0, because the fuzzer itself gets clients_idx 0?), so you arrow-left to get to 0, and then any further arrow-left/right cause panic (due to divide by 0)? 
This change stops that from happening. You still start off at fuzzer 1 and need to be on 0, but at least it doesn't panic when you arrow-key around

unbreak tui with 1 client

---

libafl_cc/src/clang.rs

Add force_load option to libafl_cc when linking static libs on macOS.
This option is equivalent to linux's --whole-archive, and it is necessary because the linker does not pick the strongly defined symbol otherwise
https://stackoverflow.com/questions/13089166/how-to-make-gcc-link-strong-symbol-in-static-library-to-overwrite-weak-symbol/37191811#37191811

OSX force_load option

---

libafl/src/monitors/disk.rs
libafl/src/monitors/mod.rs

Add a monitor that appends a single-line JSON object (https://jsonlines.org/) containing the current state every 60 seconds. I want to use it so that I can do some time-related analysis, e.g. how much coverage is found after a certain amount of time etc.

Add continous JSON Logging monitor

---

libafl/src/bolts/rands.rs

This PR fixes an error in the documentation of `Rand::below`.

Fix documentation error

---

libafl/src/feedbacks/map.rs

MapFeedback currently only support `with_names()`. 
Using `with_names()` results in errors like the one below. Even though one could specify the type directly, this is very impractical in my opinion. Therefore I suggest adding `with_name()` and potentially even removing `with_names()`.
```
error[E0284]: type annotations needed for `MapFeedback<libafl::inputs::BytesInput, DifferentIsNovel, O, MaxReducer, libafl::state::StdState<libafl::corpus::InMemoryCorpus<libafl::inputs::BytesInput>, libafl::inputs::BytesInput, RomuDuoJrRand, libafl::corpus::OnDiskCorpus<libafl::inputs::BytesInput>>, T>`
--> src/fuzzer.rs:165:43
|
165 |     let mut objective_coverage_feedback = MaxMapFeedback::with_names("objective_coverage_feedback", &edges_observer.name());
|         ------------------------------- …
```

MapFeedback: Adding support for with_name()

---

libafl/src/bolts/core_affinity.rs

supporting most of linux sched api here.

dragonflybsd build fix for core affinity.

---

libafl_nyx/src/executor.rs

Nyx input is provided by raw bytes, but it does not require that there be an internal bytes vector as HasBytesVec implies.

adjust NyxExecutor trait bound to HasTargetBytes from HasBytesVec

---

.github/workflows/build_and_test.yml

Remove clang download from windows CI since there is [already one installed](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#language-and-runtime)

Remove clang download from windows CI

---

libafl/src/fuzzer/mod.rs

I often find myself trying out different configurations on every aspect of the fuzzing. Especially ObserversTuple, StagesTuple, but I think there could be a discussion over more generic parts of the code.
With this change, I could configure stages at run-time (with CLI flags in my case):
```rs
let concrete_stages = tuple_list!(
...
);
let mut stages = Box<dyn StagesTuple<_,_,_,_>>;
if args.is_present("flag") {
// Con-style stages
stages = Box::new((AdditionalStage::new(), concrete_stages));
else {
stages = Box::new(concrete_stages);
}
fuzzer.fuzz_loop(stages.as_mut(), &mut executor, &mut state, &mut mgr);
```
I would like to add this to more parts of the code, because I want to run quick sanity-checks.
Note that my main issue is that I have to write out full types if I have to e.g. …

Add ability to use virtual dispatch to stagesTuple

---

libafl/src/observers/mod.rs
libafl/src/stages/getdeps.rs

Now Rust enforce the security guarantee of the intrinsics and give an error if they don't match the ones declared in core (fuck you btw)

Disable ObserversOwnedMap due to new Rust error

---

libafl_qemu/Cargo.toml
libafl_qemu/src/executor.rs
libafl_qemu/src/lib.rs

Problem:
Currently, it is not possible to disable the `fork` feature on `unix` without breaking the `libafl_qemu` build process. This is because `QemuForkExecutor` depends on `InProcessForkExecutor`.
Fix:
Adding `fork` feature to `libafl_qemu` and passing it down to `libafl`.

Adding fork feature passing from libafl_qemu to libafl crate

---

fuzzers/baby_fuzzer_minimizing/Cargo.toml
libafl/Cargo.toml
libafl/src/lib.rs

Auto-importing types oftentimes picks up the prelude, instead of the proper type.
Since prelude is a different use-case, I'd suggest to hide it behind a feature flag.

Hide prelude behind feature flag

---

fuzzers/frida_gdiplus/Cargo.toml
libafl/src/bolts/os/windows_exceptions.rs
libafl_frida/Cargo.toml
libafl_frida/src/executor.rs
libafl_frida/src/lib.rs
libafl_frida/src/windows_hooks.rs

Closes #395
I feel like I just created the architectual crutches by introducing [windows_hooks.rs](https://github.com/AFLplusplus/LibAFL/compare/main...expend20:LibAFL:fastfail-fix?expand=1#diff-039e662e2d4ee92b6b369a86ff38b2bf5e3a8a642e56a42386aff7c89f8efd31) with lazy_static in it. I basically needed the following, but didn't find a good way to do that. I appreciate the review comments
* I need a placeholder for keeping the result of `interceptor.replace` becase the function returns the original (not hooked) function so we could use it from our detour
* The reference for that placeholder can be passed as a parameter to the *_detour functions, now it is passed through a Mutex, but anyway the placeholder should live all the time hook exist

Hook IsProcessorFeaturePresent to crash with STATUS_STACK_BUFFER_OVERRUN exception

---

fuzzers/frida_libpng/README.md
fuzzers/qemu_arm_launcher/Makefile.toml
libafl/src/mutators/token_mutations.rs

I haven't measured this and am not even sure if CmpValues::Bytes is currently populated by any executor, but this seems like an oversight.

token mutations: set MutationResult for CmpValues::Bytes

---

fuzzers/frida_gdiplus/README.md
fuzzers/frida_gdiplus/harness.cc

It works until it starts trying to load JPEG files because the JPEG decoder uses exception unwinding (see #830)

Fix memory leaks and module instrumentation in frida_gdiplus

---

fuzzers/baby_no_std/Cargo.toml
fuzzers/baby_no_std/Makefile.toml
fuzzers/baby_no_std/build.rs
fuzzers/baby_no_std/rust-toolchain
fuzzers/baby_no_std/src/main.rs
libafl/Cargo.toml
libafl/src/executors/inprocess.rs

Seems like the baby_nostd example no longer works.
This moves it to a nightly no_std completely, also on unix.
Windows is likely still broken, though

Fixing baby_no_std

---

libafl_cc/src/clang.rs

This makes it possible to copy&paste clang.rs and edit it for custom compiler wrappers, without copying everything.

Expose OUT_DIR for compiler passes to other components

---

.gitmodules
fuzzers/backtrace_baby_fuzzers/command_executor/src/main.rs
fuzzers/backtrace_baby_fuzzers/forkserver_executor/src/main.rs
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
libafl/src/bolts/cpu.rs
libafl/src/executors/command.rs
libafl/src/executors/differential.rs
libafl/src/executors/forkserver.rs
libafl/src/observers/mod.rs
libafl/src/observers/stacktrace.rs
libafl/src/observers/stdio.rs

This gets rid of the hacks in StdOutObserver et al.
@VTCAKAVSMoACE I got issues with type inference atm, but we should wait here for your AT PR #767 to land, before it makes no sense.
@andreafioraldi what do you think

Refactor Output Observers

---

libafl/src/bolts/launcher.rs

With that change the Launcher works with run_client functions that return, which is required for e.g. corpus minimization.
@domenukk suggested to either use exit or return, I think by returning the user of the library can implement its own error handling and the library does not panic on each Error?

Fix launcher to work with returning run_client functions

---

.gitmodules
libafl_nyx/build_nyx_support.sh

This pr removes qemu-nyx and packer from git submodules but clone them in the shell script in libafl_nyx
The problem we have currently is that we have to clone many repos recursively even when we don't use nyx.
The solution was suggested here:
https://github.com/rust-lang/cargo/issues/4247#issuecomment-959912231

Less git modules

---

.github/workflows/build_and_test.yml
.gitmodules
libafl/src/bolts/core_affinity.rs
libafl/src/bolts/minibsod.rs
libafl_nyx/build_nyx_support.sh

we can t pin to a coreid however we can at least choose the performance cores for our thread.

sort of fix core affinity on mac arm64

---

scripts/check_for_blobs.sh

This should fix the builds that fail due to blobs detected in cached artifacts (#875).
~~The `check_for_blobs.sh` script takes ages locally for me though so I'm not sure what's up with that.~~
I'm not sure how the macOS fuzzer test job broke :/
It's probably related to the `pyo3` update from yesterday, but there's no obvious build system changes:
https://github.com/PyO3/pyo3/releases/tag/v0.17.3

check_for_blobs.sh: respect gitignore

---

libafl/src/executors/command.rs
libafl/src/executors/differential.rs
libafl/src/observers/mod.rs
libafl/src/observers/stacktrace.rs
libafl/src/observers/stdio.rs

Previously, the `CommandExecutor` attempted to decode its child process's stdout and stderr as UTF-8 `String`s. This could fail if the output was not UTF-8. However, the `Std{Out,Err}Observer`s should probably be able to be used in such a situation - Consider fuzzing `echo` with a random `BytesInput`.
The fix is to not decode the output, but rather directly store and provide the bytes of stdout/stderr in the observers.
Fixes #884.

stdio observers should use bytes, not strings

---

libafl/src/bolts/core_affinity.rs
libafl_cc/src/clang.rs

fixing clang wrapper test passing llvm pass api support when there are actual passes.

fixing freebsd unused import warning in core affinity.

---

libafl/src/mutators/mopt_mutator.rs

I ran into a non-determinism issue during debugging caused by this.

mopt: seed from state rand instead of current_nanos

---

libafl_frida/src/cmplog_rt.rs

For some reason, Apple's aarch64 processor throws a SIGILL when encountering LDP x5, x5 (or any other repeating register). STP works, but I changed both for symmetry.

Fix mac m1 incompatibility for cmplog in frida mode

---

libafl/src/schedulers/minimizer.rs

on_replace may cause a change in the TopRatedsMetadata. This adds it.

Fix scores when using on_replace

---

libafl_frida/src/asan/asan_rt.rs

Add MAP_JIT, and extract the writable portion of generate_instrumentation_blobs into AsanRuntime

Fix frida ASAN incompatibility with mac m1

---

libafl/src/observers/map.rs

These methods force a `MapObserver` to own an initial value, but there's no reason for this to be the case - If you don't need to allow a dynamically-changeable initial value, it might be nice to use  `<<Self as MapObserver>::Entry as Default>::default()` everywhere and have the compiler statically propagate that value.
Not a lot of code used these methods (which seems like a good argument that they aren't a fundamental part of the inteface). In particular, they were apparently intended to be used in `reset`, but `reset` doesn't have a default implementation using them - and I'd argue that's just as well, for the reasons outlined above. It might be desirable to add a sub-trait of `MapObserver` with these methods and an implementation of `reset` in terms of them.
Could probably eliminate …

libafl: Remove `set_initial`, `initial_mut` from `MapObserver` trait

---

libafl/src/executors/inprocess.rs

I'm fuzzing on windows and it seems like exception_pointers can actually be null. I observed this when calling ´abort()´ in the fuzzing harness.

[Windows] Handle crashes without exception

---

utils/gramatron/gnf_converter.py

This patch addresses the issue in #879, which fixes a typo in the `remove_left_recursion` method.

Fix a typo in gnf_converter.py

---

libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/prometheus.rs
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs

When running with many cores, or exec/sec is small (around 1), the rounding error can be relatively large for the *global* monitor.
I would also prefer printing a float, not a number. However, this PR does not change the output format. (Only when calculating the global exec/sec from client exec/sec values)
Note that I have not investigated whether TUI module works OK, but even the interfaces did not change.

Fix run/exec rounding by using floats + prettify result

---

libafl/src/bolts/cli.rs
libafl_frida/src/executor.rs

Make stalker.exclude() configurable from command line arguments

Make stalker.exclude() configurable from command line arguments

---

libafl_nyx/build_nyx_support.sh

due to the call to pushd on line 23 not being directed at packer, the wrong commit was being used and so that resulted in the wrong init.cpio.gz being generated which hangs when trying to run the libxml2 examples however using the right commit (86b159bafc0b2ba8feeaa8761a45b6201d34084f) fixes this problem.

using wrong commit due to wrong directory

---

fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
libafl/src/monitors/mod.rs

Currently, the `SimpleMonitor` does not print the user_monitor stats. Especially for the edge coverage, this would be quite useful tho. Therefore, I suggest adding an option flag to enable printing the user_monitor.
Example:
`cargo make run` in `fuzzer/fuzzbench_fork_qemu`
Current state:
```
[Testcase #0] run time: 0h-0m-4s, clients: 1, corpus: 27, objectives: 0, executions: 372, exec/sec: 91.78
[Stats #0] run time: 0h-0m-4s, clients: 1, corpus: 27, objectives: 0, executions: 372, exec/sec: 87.34
[Testcase #0] run time: 0h-0m-4s, clients: 1, corpus: 28, objectives: 0, executions: 393, exec/sec: 92.27
[Stats #0] run time: 0h-0m-5s, clients: 1, corpus: 28, objectives: 0, executions: 393, exec/sec: 78.34
```
With user_monitor:
```
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 7, …
```

SimpleMonitor optionally with user_monitor stats

---

libafl_qemu/src/mips.rs

This naming of the registers should make it easier to use them as per manual

Better MIPS register naming

---

libafl/src/mutators/mutations.rs

can result in a null op, this fix is how it is done in afl++

Avoid no-op in ByteRandMutator

---

libafl/src/observers/stacktrace.rs

As far as I've been able to see we don't use the symbols anyway, and it makes the call *way* faster. (On the system we're using it's the difference between 200 exec/sec and 0.5 exec/sec.)
Happy to make it an option if that's preferred?

stacktrace: Use unresolved backtrace call

---

libafl_cc/src/common-llvm.h

None constant being deprecated, it is recommended
to use the std::nullopt_t type instead.

libafl_cc fixes clang 16 build.

---

libafl_frida/build.rs
libafl_frida/src/asan/asan_rt.rs

iOS does not have any TLS, so we don't need to keep track of it. This allows compiling for the `aarch64-apple-ios` target.

libafl_frida: Allow compilation for iOS

---

fuzzers/forkserver_libafl_cc/Cargo.toml
fuzzers/forkserver_simple/Cargo.toml
fuzzers/fuzzbench/Cargo.toml
fuzzers/fuzzbench_fork_qemu/Cargo.toml
fuzzers/fuzzbench_forkserver/Cargo.toml
fuzzers/fuzzbench_qemu/Cargo.toml
fuzzers/fuzzbench_text/Cargo.toml
libafl/Cargo.toml
libafl/src/bolts/staterestore.rs
libafl/src/events/mod.rs
libafl/src/inputs/bytes.rs
libafl/src/inputs/encoded.rs
libafl/src/inputs/gramatron.rs
libafl/src/monitors/prometheus.rs
libafl/src/observers/map.rs
libafl/src/stages/tmin.rs
libafl_concolic/symcc_runtime/Cargo.toml
libafl_frida/Cargo.toml
libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/drcov_rt.rs
libafl_frida/src/helper.rs
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_build/Cargo.toml
libafl_sugar/Cargo.toml
utils/libafl_benches/Cargo.toml
utils/libafl_benches/benches/hash_speeds.rs

Reduces total number of packages from 577 to 571 on building with: `cargo +nightly build --workspace --all-features`
* ahash 0.7 -> 0.8
* Move `AHasher::new_with_keys` to `RandomState::with_seeds` given the recommendation from: aHash maintainer: https://github.com/tkaitchuck/aHash/issues/132#issuecomment-1288207069
* bindgen: 0.61 -> 0.63
* c2rust-bitfields: 0.3 -> 0.17
* criterion: 0.3 -> 0.4
* crossterm: 0.25 -> 0.26
* dynasmrt: 1.2 -> 2
* frida-gum/frida-gum-sys
* frida-gum:     0.8.1 -> 0.10
* frida-gum-sys: 0.4.1 => 0.6
* Update underlying frida version from 15.2 -> 16.0
* goblin: 0.5.3 -> 0.6
* hashbrown: 0.12 -> 0.13
* nix: 0.25 -> 0.26
* The `addr` arg of `mmap` is now of type `Option<NonZeroUsize>`
* The `length` arg of `mmap` is now of type `NonZeroUsize`
* prometheus-client: …

Update deps for libafl

---

fuzzers/backtrace_baby_fuzzers/command_executor/Cargo.toml
fuzzers/backtrace_baby_fuzzers/forkserver_executor/Cargo.toml
fuzzers/frida_gdiplus/Cargo.toml
fuzzers/frida_libpng/Cargo.toml
fuzzers/fuzzbench_text/Cargo.toml
fuzzers/tutorial/Cargo.toml
libafl_frida/Cargo.toml
libafl_tinyinst/Cargo.toml

cargo machete
https://github.com/bnjbvr/cargo-machete
This tool is surprisingly fast btw
```
Analyzing dependencies of crates in this directory...
cargo-machete found the following unused dependencies in /home/toka/LibAFL:
libafl -- /home/toka/LibAFL/libafl/Cargo.toml:
async-std
libafl_tinyinst -- /home/toka/LibAFL/libafl_tinyinst/Cargo.toml:
cxx
libafl_frida -- /home/toka/LibAFL/libafl_frida/Cargo.toml:
libloading
regex
command_executor -- /home/toka/LibAFL/fuzzers/backtrace_baby_fuzzers/command_executor/Cargo.toml:
ahash
spawn-ptrace
forkserver_executor -- /home/toka/LibAFL/fuzzers/backtrace_baby_fuzzers/forkserver_executor/Cargo.toml:
clap
fuzzbench_text -- /home/toka/LibAFL/fuzzers/fuzzbench_text/Cargo.toml:
serde
frida_fuzzer -- /home/toka/LibAFL/fuzzers/frida_libpng/Cargo.toml: …
```

Remove unused deps

---

libafl/src/feedbacks/mod.rs
libafl/src/observers/mod.rs

Fix #145 
Define custom deserialization and serialization since serde does not support Instant struct by default
https://github.com/serde-rs/serde/issues/1375

Use Instant::now instead of duration

---

libafl/src/observers/stdio.rs

StdFuzzer under the hood requires all attached observers to have Serialize and Deserialize traits. Even StdOutObserver has one.
StdFuzzer needs serialization to implement ExecutionProcessor trait. Sending a newTestcase event requires a serialized ObserversTuple.
I think this might have been a copy pasta bug or otherwise missing trait. Maybe it would be a good idea to require it from each implementation to prevent typos like this.

Fix StdErrObserver not implementing needed traits

---

libafl/src/corpus/minimizer.rs

Previously, CMin attempted to minimised based on distinct hitcounts; if we had two inputs, one of which had an edge hit and another which did not, it would keep both on the grounds that they were distinct and therefore interesting compared to each other.
This change drops the distinctness requirements for "not hit", which optimises CMin when used with sparse maps at the cost of some potentially interesting inputs by distinctness (notably tested: browser coverage can take several minutes with small corpora before opt).

CorpusMinimizer opt: don't add to map if it's the initial value (uninteresting)

---

libafl/src/inputs/generalized.rs
libafl/src/stages/mutational.rs
libafl/src/stages/power.rs

this is my fix for issue #1059 I am not sure about the `base.clone()` though. Seems kind of unnecessary.

Make sure input was loaded to avoid panic on unwrap in MutatedTransform

---

libafl/Cargo.toml
libafl/src/mutators/mutations.rs

Incomplete as of now (still need to update non-bytes mutators), but this fixes some issues with the likelihoods of various bytes being selected for mutation in a variety of mutators. It also introduces `rand_range`, which generally solves the random range selection problem.
This should not be merged until it has been checked for performance against the previous libafl mutations.

Mutator sampling probability fixes

---

libafl/src/events/mod.rs
libafl/src/executors/inprocess.rs

This fixes issues where std::process::exit was used erroneously instead of _exit.

Fix exits which may cause double-free corruption

---

libafl/examples/llmp_test/main.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/mod.rs
libafl/src/bolts/os/unix_shmem_server.rs
libafl/src/bolts/shmem.rs

This (hopefully) fixes a potential race condition where the message ID on EOP was the old message id, instead of zero - leading to a potential read of an unused message, if the page was mapped fast enough.
On top, it introduces an shmem cache, unused out pages will be reused instead of freed and mmapped again.

Fix llmp eop race, introduce llmp shmem cache

---

libafl/Cargo.toml
libafl/src/executors/forkserver.rs
libafl/src/inputs/encoded.rs
libafl/src/observers/mod.rs

regex is a large crate, and is only used in a few specific spots. Users should have the ability to avoid this transitive dependency if not using the features in question.

libafl: Cargo feature to avoid regex dependency

---

libafl/src/schedulers/minimizer.rs

This PR fixes #1121. I don't believe it is necessary to call `update_score` in this callback since it will get called in `on_add` if a test case gets actually added to the corpus.

Forward on_evaluation callback in MinimizerScheduler

---

libafl_cc/build.rs

When looking for LLVM in Brew Cellar include also explicitly versioned Homebrew formulae for LLVM.
When installing llvm through Homebrew it is possible to choose explicitly a major version by using the formulae `llvm@[version]` instead of installing the current stable by simply using the formulae `llvm` ([Formulae Versions - Homebrew Documentation](https://docs.brew.sh/Versions#acceptable-versioned-formulae)).  
This is useful since the [LibAFL README.md](https://github.com/AFLplusplus/LibAFL/blob/main/README.md) states:
> The LLVM tools are needed (newer than LLVM 11.0.0 but older than LLVM 15.0.0)
The `find_llvm_config_brew()` function is looking for the directory `{brew_cellar_location}/llvm/` and therefore it targets only the current stable version of LLVM (version 15 atm).
In …

Improve find_llvm for MacOS

---

libafl/src/bolts/llmp.rs
libafl/src/executors/forkserver.rs

There is an odd corner case reported by @andreafioraldi where multi core might end up in a broken state, like so:
```rust
thread '<unnamed>' panicked at 'An error occurred when brokering. Exiting.: IllegalState("Inconsistent data on sharedmap, or Bug (next_ptr was c435d0c03a073918, sharedmap page was 7ffff1300000)",    0: libafl::Error::illegal_state
```
While this is not really reproducible, I've added stronger memory boundaries and further assertions to LLMP. This should make either fix the bug, or make it easier to find, at the worst case.

Safer EoP handling

---

fuzzers/fuzzbench/src/lib.rs
libafl/src/corpus/minimizer.rs
libafl/src/corpus/testcase.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/inprocess.rs
libafl/src/feedbacks/nautilus.rs
libafl/src/fuzzer/mod.rs
libafl/src/schedulers/accounting.rs
libafl/src/schedulers/ecofuzz.rs
libafl/src/schedulers/minimizer.rs
libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/probabilistic_sampling.rs
libafl/src/schedulers/queue.rs
libafl/src/schedulers/testcase_score.rs
libafl/src/schedulers/tuneable.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/tmin.rs
libafl/src/state/mod.rs
libafl_frida/src/executor.rs
libafl_qemu/src/executor.rs
libafl_targets/src/windows_asan.rs

- Rename fuzz_level to scheduled_count
- I forgot to increment fuzz_level (scheduled_count) before, so fix this
- Add set_current_scheduled method. scheduler->next() calls this. it sets corpus.current() and update scheduled_count.
- Separate on_remove/on_replace from Scheduler. AFL never expects any corpus entry. so not every scheduler can have this.
- Remove HasFuzzedCorpusId.
- Remove fuzzed member from Testcase. fuzz_level > 0 is the equivalent thing

Fix fuzz_level related thing, separate on_replace/on_remove from Scheduler & various fixes

---

fuzzers/forkserver_libafl_cc/src/main.rs
fuzzers/forkserver_simple/src/main.rs
libafl/src/bolts/mod.rs
libafl/src/bolts/ownedref.rs
libafl/src/executors/forkserver.rs
libafl/src/observers/map.rs

This replaces all `downsize` calls with `truncate`, the name that's used in `Vec`.
It also adds a `Truncate` trait to `bolts `.

Added Truncate trait

---

fuzzers/baby_fuzzer_swap_differential/src/main.rs
libafl/src/observers/map.rs

Right now the Differential Observer used some UB, mainly keeping multiple &mut references to things, see also #1133 
This tries to fix things. @addisoncrump please take a look :)

Fix UB for differential map observer example

---

fuzzers/fuzzbench/fuzz.c
libafl/src/stages/calibrate.rs

This will continue calibration stage infinitely if the corpus already fails or timeouts. (Could happen if user used load_initial_input_forced() )

Fix infinite calibration

---

libafl/src/lib.rs

I noticed some attributes in `libafl/src/lib.rs` have duplicate lines.

Remove duplicate lines in attributes

---

fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/qemu_arm_launcher/src/fuzzer.rs
fuzzers/qemu_launcher/src/fuzzer.rs
fuzzers/qemu_systemmode/src/fuzzer.rs
libafl/src/bolts/cli.rs
libafl_qemu/Cargo.toml
libafl_qemu/src/asan.rs
libafl_qemu/src/emu.rs

Libraries should not `assert!` except in cases of unrecoverable (library) programmer error. These errors are all potentially recoverable, and aren't internal errors in `libafl_qemu` itself.

qemu: Return errors from `Emulator::new` instead of asserting

---

libafl/src/mutators/encoded_mutations.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/token_mutations.rs
libafl/src/stages/colorization.rs

libafl: Mark `buffer_{self_,}copy` as unsafe, don't export them

---

libafl/src/stages/tuneable.rs

This allows us to fuzz single seeds for `timeout` seconds

Tuneable stage with per-seed timeout

---

libafl_targets/src/sancov_8bit.rs

Not sure, but shouldn't `sancov_8bit` use the `OwnedMutSlice` type such that it can be used with the `MultiMapObserver`?

switch sancov_8bit.rs to use OwnedMutSlice

---

libafl/src/stages/dump.rs

I need to access to the `state` inside the callback of DumpToDiskStage.
Else I can't implement this
https://github.com/AFLplusplus/libafl_fuzzbench/blob/main/grimoire/src/lib.rs#L451
because now there's no GeneralizedInput and BytesInput has no generalized() method

Change DumpToDiskStage's callback

---

libafl/src/executors/command.rs

Avoid the fuzzer from getting killed if the child process closes the other end of the pipe before the fuzzer has finished writing to it.
I'm not sure if this is an idiomatic way to do this or if this signal should be handled at the global level.

Ignore 'Broken Pipe' if child process does not read all of stdin

---

libafl_cc/build.rs

#1234 
Add CLANG and CLANG_PP env variables for Windows. Resolves issue if clang and llvm-config are not in the same location.

Add file extension for clang in libafl_cc/build.rs

---

libafl/src/stages/mutational.rs
libafl/src/stages/tmin.rs
libafl/src/stages/tuneable.rs

Mutations may not actually be performed on the input, in which case the mutator will return MutationResult::Skipped. We should not execute mutants which have no difference from the parent. This especially affects slow-executing targets.

Add check for if mutations were skipped to MutationalStages

---

fuzzers/backtrace_baby_fuzzers/command_executor/src/main.rs
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
libafl/src/executors/command.rs

Allow configuring timeout for CommandExecutor

---

docs/.gitignore
docs/listings/baby_fuzzer/listing-01/Cargo.toml
docs/listings/baby_fuzzer/listing-01/src/main.rs
docs/listings/baby_fuzzer/listing-02/Cargo.toml
docs/listings/baby_fuzzer/listing-02/src/main.rs
docs/listings/baby_fuzzer/listing-03/Cargo.toml
docs/listings/baby_fuzzer/listing-03/src/main.rs
docs/listings/baby_fuzzer/listing-04/Cargo.toml
docs/listings/baby_fuzzer/listing-04/src/main.rs
docs/listings/baby_fuzzer/listing-05/Cargo.toml
docs/listings/baby_fuzzer/listing-05/src/main.rs
docs/listings/baby_fuzzer/listing-06/Cargo.toml
docs/listings/baby_fuzzer/listing-06/src/main.rs
docs/src/baby_fuzzer/baby_fuzzer.md

Restructure the `baby_fuzzer` chapter to use listings instead of hardcoded snippets, to allow for better maintenance and hiding/showing relevant parts of code, to reveal how new snippets fit in the complete fuzzer.

Improve `baby_fuzzer` chapter of the documentation

---

libafl/src/events/simple.rs

Does what it says on the tin. Allows you to do:
```rs
mgr.send_exiting()
```
To end the fuzzing campaign.

Make it possible to escape from simple event restarter

---

libafl/Cargo.toml
libafl/src/bolts/anymap.rs
libafl/src/bolts/serdeany.rs
libafl/src/lib.rs

The latest nightly seems to have 128 bit TypeIds, see
https://github.com/rust-lang/compiler-team/issues/608
This adds support for both sizes, using u128 for both.
We might want to use u64 always for performance reasons, what do you think @andreafioraldi

Fix AnyMap for TypeIds with 128 bit

---

libafl_cc/build.rs

Allow one to specify the `LLVM_BINDIR`, `LLVM_VERSION`, `LLVM_CXXFLAGS`, and `LLVM_LDFLAGS` environment variables when building `libafl_cc`, in order to allow one to override the values returned by `llvm-config`, or for cases where `llvm-config` is not available.

libafl_cc: add override env vars

---

libafl_frida/src/asan/asan_rt.rs

I ran into an issue with a stack offset being incorrect for saved registers, in `emit_shadow_check`, in Frida mode, on x64.
In particular, the saved value for RDI is off, when it is used as the index register, and needs to be loaded from the stack.
```
Low mem addr 
|   rax    |   <-- rsp
|   rcx    |
|   rdx    |
|   rsi    |
|   rdi    |  < -- rsp + 0x20
High mem addr
```
This commit makes things work on my target, and seems to match the stack diagram I made while debugging the issue!
Thanks!

Fixes offset math in Frida Offset Checks

---

fuzzers/baby_fuzzer_swap_differential/src/bin/libafl_cc.rs
fuzzers/forkserver_libafl_cc/src/bin/libafl_cc.rs
fuzzers/fuzzbench/src/bin/libafl_cc.rs
fuzzers/fuzzbench_text/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libmozjpeg/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_accounting/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_centralized/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_cmin/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_ctx/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/libfuzzer_libpng_launcher/src/bin/libafl_ar.rs
fuzzers/libfuzzer_libpng_launcher/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_launcher/src/bin/libafl_libtool.rs
fuzzers/libfuzzer_libpng_norestart/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_tcp_manager/src/bin/libafl_cc.rs
fuzzers/libfuzzer_reachability/src/bin/libafl_cc.rs
fuzzers/libfuzzer_windows_asan/src/bin/libafl_cc.rs
fuzzers/nautilus_sync/src/bin/libafl_cc.rs
fuzzers/nyx_libxml2_parallel/src/bin/libafl_cc.rs
fuzzers/nyx_libxml2_standalone/src/bin/libafl_cc.rs
fuzzers/tutorial/src/bin/libafl_cc.rs
libafl_cc/src/ar.rs
libafl_cc/src/clang.rs
libafl_cc/src/lib.rs
libafl_cc/src/libtool.rs

This PR implements a new feature for `libafl_cc` which enables automatic compilation/linking of various configurations of a project/fuzzer, including capabilities like `coverage`, `asan`, `cmplog`, `ubsan`, and `llvm-cov`.
The user specifies the Configurations desired either on the command line or in their `src/bin/libafl_cc.rs` file. An example of the latter is included here in the `libfuzzer_libpng_launcher` fuzzer.
At the moment, it is not possible to build variants which include multiple configurations (i.e. a binary with both `asan` and `coverage`), but we could easily extend to allow this.

Add feature to build variants/configurations automatically, with libtool/cc/cxx shims

---

libafl/src/executors/inprocess.rs
libafl_frida/src/executor.rs
libafl_qemu/src/executor.rs
libafl_targets/src/windows_asan.rs

This is to enable things like crash-exploration, as well as making sure that crashes that are interesting get added to the corpus

Insert into corpus if feedback is_interesting on crash/timeout

---

libafl/Cargo.toml
libafl_sugar/Cargo.toml

Trying to update all the transitive deps of my project to syn 2 so I don't have to build syn twice...

libafl{,_sugar}: Bump typed-builder to 0.15 for syn 2 support

---

libafl/src/observers/value.rs

RefCell is not Hash (and cannot be Hash), which prevents it from being used with NewHashFeedback. This provides an implementation which allows access to an internal RefCell'd value.

Add RefCellValueObserver

---

fuzzers/forkserver_libafl_cc/src/lib.rs
fuzzers/fuzzbench/src/lib.rs
fuzzers/fuzzbench_text/src/lib.rs
fuzzers/libafl_atheris/src/lib.rs
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_libpng_accounting/src/lib.rs
fuzzers/libfuzzer_libpng_centralized/src/lib.rs
fuzzers/libfuzzer_libpng_cmin/src/lib.rs
fuzzers/libfuzzer_libpng_ctx/src/lib.rs
fuzzers/libfuzzer_libpng_launcher/src/lib.rs
fuzzers/libfuzzer_libpng_norestart/src/lib.rs
fuzzers/libfuzzer_reachability/src/lib.rs
fuzzers/libfuzzer_windows_asan/src/lib.rs
fuzzers/nautilus_sync/src/lib.rs
fuzzers/tutorial/src/lib.rs

Else it sounds like things can go... very wrong.

Make all no_mangle fns extern "C"

---

docs/src/core_concepts/feedback.md

This was a leftover from the before-times.

Remove FeedbackState reference from the book

---

libafl_cc/src/cfg.rs

get_edge returns a reference, anyhow CfgEdge does implement the Borrow's trait neither.

ControlFlowGraph::calculate_difference_all_edges build warning fix.

---

libafl/src/bolts/llmp.rs
libafl/src/bolts/os/unix_shmem_server.rs
libafl/src/bolts/tuples.rs

This is still not perfect, but at least should be quite a bit better

Less unsafe `type_eq` in stable

---

.github/workflows/build_and_test.yml
libafl/Cargo.toml
libafl/build.rs
libafl/src/lib.rs
libafl/src/observers/mod.rs
libafl_bolts/Cargo.toml
libafl_bolts/build.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/os/unix_signals.rs
libafl_bolts/src/os/windows_exceptions.rs
libafl_bolts/src/shmem.rs
libafl_bolts/src/tuples.rs

This makes it possible to use bolts without allocator

Make bolts work without alloc

---

libafl/src/lib.rs
libafl_bolts/src/lib.rs

Follow up on #1402: We don't actually use this atm, the `owned` module is disabled.

Removed unused intrinsics features

---

libafl_qemu/Cargo.toml

Fix `Cannot deserialize an unregistered type` occurring when using libafl_qemu.

Add `serdeany_autoreg` to `libafl_qemu`

---

libafl_frida/Cargo.toml

This is the same as #1416 but for frida instead of qemu. Not sure if it's needed but maybe it is?

Add serdeany_autoreg to libafl_frida

---

libafl/src/events/mod.rs
libafl_qemu/src/emu.rs
libafl_sugar/src/lib.rs

For the Derive macro apparently it's not enough to ignore the clippy lint on the struct, we need the whole module...

More Clippy

---

libafl_bolts/build.rs

despite being present in the headers, getcontext is not implemented in musl libc, most likely due to the fact it s a deprecated interface. The only way around is having the third party libucontext apk package installed.

bolts fix musl build.

---

libafl_sugar/Cargo.toml

This adds qemu architectures that are supported but not exposed by the sugar crate right now

Add more libafl_qemu archs to libafl_sugar

---

libafl_sugar/src/qemu.rs

the `clippy.sh` script and the CI unbuntu-check test previously failed with 
```rust
error[E0433]: failed to resolve: use of undeclared type `QemuCmpLogHelper`
--> libafl_sugar/src/qemu.rs:221:25
```
this was caused by using `feature = "{mips,hexagon}"` for the import and `cpu_arch = "{mips,hexagon}"` later when using `QemuCmpLogHelper`.

fix CI QemuCmpLogHelper error.

---

libafl/src/observers/cmp.rs

This turned out to be the root cause of a crash when using something like:
```
let map = unsafe {
let layout = Layout::new::<AFLppCmpMap>();
Box::from_raw(alloc_zeroed(layout) as *mut AFLppCmpMap)
};
let obs = AFLppForkserverCmpObserver::new("cmplog", &mut map, true);
```
Using the explicit memset is the same performance and doesn't crash.

Reset headers with a memcpy, not an assign from zeroed

---

libafl/src/stages/tuneable.rs

I can't see obvious reasons to make `TuneableMutationalStage` a singleton class and it's super inconvenient that every fuzzer can only have one `TuneableMutationalStage`. Therefore, like the observers and feedbacks, I assign a name for each `TuneableMutationalStage` to allow multiple mutational strages while keeping maximum backward compatibility.

Allow multiple tuneable mutational stages

---

fuzzers/baby_fuzzer_grimoire/src/main.rs
libafl/src/stages/mutational.rs

Trivial patch to allow users to set the max iterations for a `StdMutationalStage`

Allow setting the max iterations

---

libafl/src/stages/tuneable.rs

This fixes usability problems after #1437 (for my usecase) by adding _std methods

Create _std public methods on TunableMutationalStage

---

.github/workflows/build_and_test.yml
Cargo.toml
fuzzers/fuzzbench/fuzz.c
libafl_libfuzzer/Cargo.toml
libafl_libfuzzer/build.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs
libafl_libfuzzer/src/lib.rs
libafl_targets/build.rs
libafl_targets/src/cmplog.c
scripts/publish.sh

This wraps up some last minute items to prepare the publishing of libafl_libfuzzer.

Prep for publishing libafl_libfuzzer

---

libafl_bolts/Cargo.toml

mostly due std::cell namespace introduction in the 1.70 version. as rust versions evolve fast enough, it might be easier than having conditional dependency on he old once_cell crate.

bolts: disable build for rust < 1.70 proposal.

---

libafl_bolts/src/llmp.rs

This cleans up client id calculation and adds `peek_next_client_id` to get the next client id

Add Broker.peek_next_client_id

---

libafl/src/events/centralized.rs
libafl/src/events/llmp.rs
libafl_bolts/examples/llmp_test/main.rs
libafl_bolts/src/llmp.rs

This cleans up the LLMP interface to reduce footguns

Less pub in LLMP

---

libafl/src/mutators/mutations.rs

previously this searched for the first and the last difference between the same 2 inputs 3 times in a loop

remove unneeded loop in `SpliceMutator::mutate`

---

libafl_bolts/src/shmem.rs

Improved `CommonUnixShMem` implementation:
In the current implementation, the `new` function allocates new shared memory using `shmctl(IPC_PRIVATE, size, IPC_CREAT)` and attaches it to the current process with `shmat(id, NULL, 0)`. However, when it comes time to `drop` this shared memory, it merely releases the shared memory object with `shmctl(id, IPC_RMID, NULL)`. Unfortunately, this approach leaves the mounted shared memory lingering in the current process's memory space. Even worse, the shared memory won't deallocate from the system until the current process ends.
This pull request addresses this issue by implementing a solution to properly deallocate the shared memory, ensuring that it is no longer present in the process's memory space and is also released from the system resources …

bolts: Fix shmem leak when Drop-ing CommonUnixShMem

---

libafl/Cargo.toml
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs

Change from `Spans` to `Line` is due to a deprecation. Everything else is 1:1, as ratatui is a fork.

Update from unmaintained tui-rs to ratatui

---

fuzzers/forkserver_simple/src/main.rs
libafl/src/executors/forkserver.rs

The forkserver did not kill the child on exit.
This adds a `Drop` implementation.

ForkserverExecutor: stop forked children on exit

---

.github/workflows/build_and_test.yml
libafl_libfuzzer/Cargo.toml
libafl_libfuzzer/build.rs
libafl_libfuzzer/src/lib.rs

Embed the built `libafl_libfuzzer_runtime.a` file when the feature is specified so you can do nice stuff with `libafl_cc` to  use `-fsanitize=fuzzer-no-link` and link the runtime afterward.

Add embed-runtime feature 

---

libafl_targets/build.rs

There was a linkage issue on ARM macOS when linking here because of the difference between unix/linux/freebsd cfgs. This fixes it. cc: @jhertz

Fix linkage on arm macs when building libafl_targets

---

libafl_libfuzzer/build.rs

It is very confusing if you are trying to build on MacOS and it is telling you that it worked, but actually it didn't.

Apparently `cargo:error` does nothing

---

libafl/src/stages/tuneable.rs

TuneableMutationalStage did not correctly access metadata (it should use named metadata, but was not) and could enter an infinite loop if the global metadata was set, but not the named metadata. This fixes both issues.

Metadata + infinite loop fix for TuneableMutationalStage

---

libafl_bolts/src/os/unix_signals.rs

When entering a signal handler, the ucontext_t is not necessarily 0x10-aligned, so we need to use read_unaligned instead of dereferencing.

fix(bolts/unix_signals): unaligned ucontexts

---

libafl/src/lib.rs
libafl_bolts/src/lib.rs
libafl_cc/src/lib.rs
libafl_concolic/symcc_runtime/src/lib.rs
libafl_derive/src/lib.rs
libafl_frida/src/lib.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs
libafl_sugar/src/lib.rs
libafl_targets/src/lib.rs
libafl_tinyinst/src/lib.rs
scripts/clippy.sh

- Addresses some recent clippy error and warning updates which affected #1503.
- Change clippy to use debug instead of release builds to speed up CI a touch.

Clippy error + warning fixes

---

fuzzers/frida_executable_libpng/src/fuzzer.rs
fuzzers/frida_gdiplus/src/fuzzer.rs
fuzzers/frida_libpng/src/fuzzer.rs
libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/cmplog_rt.rs
libafl_frida/src/coverage_rt.rs
libafl_frida/src/drcov_rt.rs
libafl_frida/src/executor.rs
libafl_frida/src/helper.rs

Currently the Frida helper is very dependent on using the FuzzerOptions from `libafl_bolts`. However, there is no reason it has to be, and Frida mode should totally be usable without needing clap or the like.

Rework Frida instrumentation to decouple it from FuzzerOptions and add FridaInstrumentationHelperBuilder

---

libafl/src/stages/tuneable.rs

One should be able to pass both `fuzz_time` and `iters` as the mutator allows to `perform n iterations or fuzz for provided time, whichever comes first`

Remove check and error when both fuzz_time and iters passed

---

libafl/src/monitors/tui/mod.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/src/fuzz.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs

This fixes two bugs:
1. When not using `fork` feature, the `:0` based fork allocation caused each subprocess to mark a separate broker port, and subsequently led to `-fork=n` with `n > 1` not performing any fuzzing.
2. `close_fd_mask` would incorrectly close file descriptors used by the fuzzer runtime (for e.g. logging and tui). This fixes the behaviour for each configuration mode, and also hardens the `TuiMonitor` implementation for similar usages downstream.
This does, however, replace the libafl dependency with a path dependency. This is not optimal, because we need to release this with a fixed path. This blocks the next release. I will open an associated issue for fixing this while we figure out a solution.

libafl_libfuzzer fixes for port and fd allocation

---

libafl/src/observers/map.rs
libafl_bolts/src/staterestore.rs

Fix unsoundness for misaligned map observers

---

libafl_cc/src/autotokens-pass.cc
libafl_cc/src/cmplog-routines-pass.cc

Basically llvm passes were disabled from clang-12 to clang-14 for the past 4 months

Fix llvm passes

---

libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/helper.rs

This fixes Frida after PR #1523

Fix frida libafl after #1523

---

libafl_cc/src/ar.rs

Add `.ao` and `.c.o` to extensions supported by `libafl_ar`

libafl_ar: add extensions

---

libafl_frida/Cargo.toml
libafl_frida/src/alloc.rs

frida-asan: move to mmap-rs

---

fuzzers/qemu_coverage/Cargo.toml
fuzzers/qemu_coverage/Makefile.toml
fuzzers/qemu_coverage/src/fuzzer.rs

The `QemuDrCovHelper` only writes the coverage for an individual core, so we need to write the coverage for each core into a separate file to avoid them all from overwriting each other.
Also made a few tweaks following feedback on the `qemu_launcher` changes.

Write coverage for QEMU into separate files

---

libafl_bolts/src/minibsod.rs

I am fixing the build ability for Android x86_64.

fix(minibsod): allow `dump_registers` and `write_crash` for Android x86_64

---

libafl/src/mutators/mutations.rs

without this, this mutator sometimes deletes the entire input

Fix bytesdelete mutator

---

libafl_cc/src/clang.rs
libafl_cc/src/libtool.rs

We were incorrectly rewriting source files instead of output files. This fixes the issue.

libafl_cc: fix configuration support

---

libafl_libfuzzer/README.md
libafl_libfuzzer/libafl_libfuzzer_runtime/build.sh
libafl_libfuzzer/src/lib.rs

This adds additional usage documentation for `libafl_libfuzzer` for both using with Rust and C targets. Additionally, it provides a build script which assembles the required `libFuzzer.a` for use with C-like targets.

libafl_libfuzzer: documentation and build script

---

libafl_bolts/Cargo.toml
libafl_bolts/src/os/unix_signals.rs

We have a bunch of code for signal handling that we really need, since nix exposes roughly the same API (while supporting more signals)

Make Signals compatible with nix, implement TryFrom<&str>

---

libafl_frida/src/drcov_rt.rs

Update after https://github.com/AFLplusplus/LibAFL/pull/1579.

chore(drcov_rt): remove unused a field and methods

---

Dockerfile

When I start developing in the dev container, I always have to install python3-venv and ninja-build ( `cargo build` fails if they're not installed). So, I added them to the Dockerfile.

added ninja-build and python3-venv as dependencies

---

libafl/src/fuzzer/mod.rs

There is not really any reason(?)

Fuzz_loop should not return CorpusId

---

libafl/src/executors/with_observers.rs

The WithObserver executor is a wrapper to implement the HadObservers trait for other executors but required the wrapped executor to implement HasObserver.

fix: use correct trait bound in WithObservers Executor

---

.gitignore
fuzzers/fuzzbench/fuzz.c
fuzzers/libfuzzer_stb_image_concolic/Makefile.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
libafl/src/observers/concolic/mod.rs
libafl/src/observers/concolic/serialization_format.rs
libafl_concolic/symcc_libafl/src/lib.rs
libafl_concolic/symcc_runtime/src/filter.rs
libafl_concolic/symcc_runtime/src/tracing.rs

following https://github.com/AFLplusplus/symcc/pull/8 https://github.com/AFLplusplus/symcc/pull/7

Update LibAFL concolic

---

libafl/src/executors/inprocess.rs
libafl/src/executors/with_observers.rs

Added a call to the wrapped observer's post run function (similar to the corresponding call in the combined executor).

[WithObservers] Call the wrapped observer's post run function

---

libafl_bolts/src/math.rs

There's a rare bug which can occur where there is precision loss on f32s s.t. we can panic on comparisons with near-one values: https://docs.rs/libafl/latest/src/libafl/mutators/tuneable.rs.html#180
This addresses it by simply clamping the last value to positive infinity, guaranteeing that it will be compared as greater-than.

Fix rare precision issue with comparisons on cumulative distributions

---

libafl/src/corpus/inmemory.rs
libafl/src/corpus/mod.rs
libafl/src/monitors/mod.rs
libafl_bolts/src/lib.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/src/corpus.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/feedbacks.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/merge.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/options.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/tmin.rs

This libafl_libfuzzer corpus had several annoying issues previously, esp. with duplication of existing inputs. This should fix it :)

Improve the libafl_libfuzzer corpus

---

libafl_frida/src/drcov_rt.rs

Unlike `Input` object, which generates files with a unique name, in the coverage module, files are written with a non-unique name, which is why overwriting occurs. It would not play a big role, but the coverage is recorded only once --- when instrumenting by Frida (inside [Transformer](https://github.com/AFLplusplus/LibAFL/blob/5b0e3dd3bcbefc4f02e44a6ee0237998cea294ec/libafl_frida/src/helper.rs#L519-L522)), that is, running the same files leads to overwriting the coverage file with an empty DrCov table.
I used a dirty hack, I admit. If there are better ideas, then I am open to suggestions.

fix(drcov_rt): coverage files are overwritten if have the same names

---

.github/workflows/build_and_test.yml
scripts/fmt_all.sh

Reverts AFLplusplus/LibAFL#1649
This apparently fails on Ubuntu..
```bash
20:33:57 Package 'clang-format-16' not found.
```

Revert "Use clang-format-16"

---

docs/listings/baby_fuzzer/listing-04/src/main.rs
docs/src/baby_fuzzer/baby_fuzzer.md

Otherwise we have an empty feature section and cargo does not find the `panic` feature.
Small fix :) 
It's really cool to have this guide as such a simple starting point to a really complex topic!

Fixed panic feature in baby_fuzzer example

---

libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/mod.rs
libafl/src/executors/shadow.rs
libafl/src/executors/with_observers.rs
libafl/src/feedbacks/concolic.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/observers/map.rs
libafl/src/observers/mod.rs
libafl/src/stages/tmin.rs
libafl_bolts/src/serdeany.rs
libafl_frida/src/executor.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/helper.rs
libafl_qemu/src/hooks.rs

Having Debug as supertrait is undesirable in my opinion, since this propagates everywhere. I would suggest limiting Debug as trait bound to the actual `Debug` trait implementations. This also doesn't really make sense from a semantic standpoint, since most of these traits don't actually need anything from the Debug trait.
There are probably more occurrences of this, but i didn't look through all the code yet. What is your opinion on this?

refactor: Remove unnecessary Debug trait bounds

---

libafl_bolts/examples/llmp_test/main.rs
libafl_bolts/src/core_affinity.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/minibsod.rs
libafl_bolts/src/shmem.rs

core_affinity using available_parallelism which also support this platform. further tests disabling.

bolts for haiku update.

---

.github/workflows/build_and_test.yml
libafl_libfuzzer/Cargo.toml
libafl_libfuzzer/build.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/build.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs

Previously we were unable to use mimalloc due to symbol conflict with the default rust allocator. This avoids this issue by renaming the symbols responsible for allocation.
Note that, in rare circumstances, we would deadlock while handling an ASAN error due to allocations inside of a signal handler. This sidesteps the issue by avoiding the use of the async-signal-unsafe malloc.

libafl_libfuzzer: rename all symbols

---

libafl_libfuzzer/libafl_libfuzzer_runtime/build.sh

This just makes it easier for us to specify `release-fuzzbench` in fuzzbench runs.

Add arg for profile in libafl_libfuzzer build.sh

---

libafl_bolts/src/core_affinity.rs

not really working, explicit current id makes the test always pass.

bolts fix solarish cpu binding. seems PS_MYID to save one syscall was

---

libafl/src/executors/forkserver.rs

Child pid is no longer reset after a target run in persistent mode
Fixes issue #1714

libafl: forkserver in persistent mode bug

---

libafl_bolts/src/llmp.rs

In my opinion the inner value of `Flags` should be publicly accessible.
I am implementing my own llmp runloop in another crate and I need to create my own set of Flags for message handling. The inner value of Tags are already `pub` as well.

Make inner value of llmp Flags pub

---

libafl_frida/Cargo.toml
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/cmplog_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/utils.rs

Not done yet, but this PR removes capstone from libafl-frida for aarch64. 
The changes themselves are mostly done, but it needs to be tested and some tests need to be added. The API also needs to be made consistent with https://github.com/AFLplusplus/LibAFL/pull/1720 to the extent possible.

Remove capstone from frida [aarch64]

---

libafl_frida/Cargo.toml

i noticed @tokatoka pointed the new `yaxpeax-x86` dependency directly at the commit fixing the `r12`/`r13` constructor confusion, that and a few [other fixes](https://github.com/iximeow/yaxpeax-x86/blob/no-gods-no-/CHANGELOG#L1-L34) are all published to crates.io as of 1.2.2. figured i'd come by and offer that version bump :)

use yaxpeax-x86 version from crates.io instead of direct git dep

---

fuzzers/backtrace_baby_fuzzers/c_code_with_fork_executor/src/main.rs
fuzzers/backtrace_baby_fuzzers/c_code_with_inprocess_executor/src/main.rs
fuzzers/backtrace_baby_fuzzers/rust_code_with_fork_executor/src/main.rs
fuzzers/backtrace_baby_fuzzers/rust_code_with_inprocess_executor/src/main.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_forkserver/src/main.rs
fuzzers/fuzzbench_forkserver_cmplog/src/main.rs
libafl/src/observers/cmp.rs
libafl/src/observers/stacktrace.rs
libafl/src/observers/value.rs
libafl_bolts/src/ownedref.rs
libafl_bolts/src/shmem.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/fuzz.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/report.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/schedulers.rs
libafl_targets/src/cmps/mod.rs
libafl_targets/src/cmps/observers/aflpp.rs

This is an attempt to fix the undefined behaviour we currently have, as discussed in #1748

Fix `as_object` UB discussed in #1748

---

Dockerfile
libafl/src/feedbacks/map.rs

According to https://doc.rust-lang.org/core/simd/trait.SimdOrd.html , the correct import seems `core::simd::SimdOrd`.
0.11.2 breaks several downstream project buildings. Currently, I'm setting `=0.11.1` as workaround.

Fix incorrect imports

---

libafl/src/inputs/encoded.rs
libafl/src/mutators/mutations.rs

The regex crate seems incompatible with Miri on M1
I don't think we'll need #1760 apart from this fix.
Tested using `RUST_BACKTRACE=1 MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test`.
Edit: opened a bug report in the underlying crate here https://github.com/BurntSushi/aho-corasick/issues/138

Miri ignores for M1 regex

---

libafl_frida/src/helper.rs

DrCov was enabled on unix only, however, it works perfectly fine on Windows - thus removing unix conditioning.

Enabling DrCov on Windows

---

libafl_qemu/src/cmplog.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/snapshot.rs

Remove the unsafe access to `Emulator` and always check for initialization instead.
Check issue #1757 for more details.

Safe access to QEMU's `Emulator` struct

---

libafl_frida/src/helper.rs

Module such as `linux-vdso.so.1` doesn't have related file on disk.

Check canonicalized_module_path before used

---

libafl_targets/src/lib.rs

This PR solves #1778 - "Build issues on LibAFL//fuzzers/libfuzzer_windows_asan & LibAFL/libafl_targets"

[libafl_targets] # fix typo in windows_asan feature

---

libafl_cc/build.rs
libafl_concolic/symcc_runtime/src/lib.rs
libafl_libfuzzer/build.rs
libafl_qemu/src/edges.rs
libafl_qemu/src/emu.rs
libafl_targets/src/lib.rs

Because else Rust linter on Windows doesn't work (cargo check fails)

Don't use assert fail when building on libafl_libfuzzer on windows

---

.github/workflows/build_and_test.yml

Because it simply doesn't work for the last couple of weeks
https://github.com/AFLplusplus/LibAFL/actions/runs/7515657601/job/20459829193

Remove macos-clippy

---

libafl_qemu/Cargo.toml
libafl_qemu/build.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/lib.rs

Declared functions in `extern "C"` blocks are not necessarily checked at link-time if the symbols are not necessary during compilation (unused symbols).
Some symbols could be declared without any definition and still compile correctly.
Someone had this issue with `libafl_qemu_trigger_breakpoint` being declared in LibAFL without a definition in QEMU.
Calling the wrapper function in a fuzzer resulted in a linker error.
With the new macro `extern_c_checked!`, it is possible to declare C symbols and still get an error if there is no definition.
It relies on a nightly feature, and thus will only trigger in a nightly build.
Stable builds will work as before.
It is mainly useful to catch those kinds of errors early in the CI.

QEMU: safe linking of extern "C" declarations

---

libafl_frida/src/cmplog_rt.rs

This fixes a few aarch64-related regressions introduced by https://github.com/AFLplusplus/LibAFL/pull/1713

Fix build issues in frida cmplog for aarch64

---

libafl_targets/src/sancov_cmp.c
libafl_targets/src/sancov_cmp.rs

This table allows users to map between coverage bitmap entries and the corresponding code in memory.

Expose PCs table.

---

libafl_qemu/Cargo.toml

This makes injections fuzzing easier to use, and it doesn't add much overhead to the build process/downloads (especially when compared to qemu, lol)

QEMU: add injections mode default

---

libafl_bolts/src/serdeany.rs

This PR removes the `create_serde_registry_for_trait` macro, extracting the `serdeany_registry` module out of it.
This should close #1605.

Remove `create_serde_registry_for_trait` macro

---

libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp.rs
libafl_bolts/examples/llmp_test/main.rs
libafl_bolts/src/llmp.rs

It makes the LLMP client timeout value configurable at runtime.
I was considering first making it configurable at compile time with generics to keep the same performance, but I guess it is not really useful and more flexible like this.

Configurable LLMP client timeout

---

fuzzers/qemu_launcher/Makefile.toml

`cargo make run` fails for me because the makefile points to the wrong include directory for the zlib headers (they are located in `*/include` not `*/lib`).

fuzzers: Fix qemu_launcher zlib include path

---

libafl_cc/src/no-link-rt.c

libafl_cc fails to build on x86_32 due to usage of uint128_t data type at:
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/src/no-link-rt.c#L60 and following.
These functions are guarded by an incorrect #ifdef at:
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/src/no-link-rt.c#L59
This fix changes the #iffdef to match the #ifdef at:
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/src/no-link-rt.c#L3

Fix x86_32 build: Don't build functions using uint128_t data type on x86_32

---

libafl_qemu/libafl_qemu_build/src/build.rs

A linking error can happen if this is enabled by default; for now we can disable it.

Disable `af-xdp` from QEMU default config

---

libafl_libfuzzer/README.md
libafl_targets/src/common.h
libafl_targets/src/sancov_cmp.rs

This PR is the last step in making libafl_libfuzzer work on macOS. I have confirmed that it works with the example from the Rust Fuzzing Book.
Two important things were changed:
Fixes #1712. The current implementation provides default implementations for weak functions on macOS, breaking `CHECK_WEAK_FN`. This meant important functions were not being called upon running the target. The approach I came up with was to remove this default impl and require explicit weak linking args on macOS only.
We assert that this will only be called once, though [LLVM does not guarantee that](https://clang.llvm.org/docs/SanitizerCoverage.html#pc-table). In reality, it appears this is called more than once on macOS, but with the same exact arguments. Since the arguments are the same and we are just …

Finalize macOS support for libafl_libfuzzer

---

libafl/src/generators/nautilus.rs

Support raw byte grammar in NautilusContext

---

libafl/src/executors/command.rs
libafl/src/executors/inprocess_fork.rs
libafl/src/executors/mod.rs
libafl/src/feedbacks/differential.rs
libafl/src/mutators/tuneable.rs
libafl/src/state/mod.rs
libafl_qemu/src/hooks.rs

This is likely incomplete (my IDE doesn't work when libafl_qemu is in the workspace :face_with_spiral_eyes:) but should revert changes which over-aggressively made NopState a testing-only feature: https://github.com/AFLplusplus/LibAFL/commit/ba8ca6723b7adbc46ce19b9dce4f46a41e8dd3bc

Make NopState public so that it can be used as reproducer

---

libafl/src/corpus/testcase.rs
libafl/src/events/launcher.rs
libafl/src/events/simple.rs
libafl/src/executors/hooks/inprocess.rs
libafl/src/executors/hooks/inprocess_fork.rs
libafl/src/lib.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/observers/cmp.rs
libafl/src/schedulers/powersched.rs
libafl/src/stages/concolic.rs
libafl/src/stages/logics.rs
libafl/src/stages/mod.rs
libafl/src/stages/tracing.rs
libafl/src/state/mod.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/os/unix_shmem_server.rs
libafl_cc/src/cfg.rs
libafl_cc/src/clang.rs
libafl_libfuzzer/src/lib.rs
libafl_nyx/src/helper.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

Addresses a scenario where comparison log tracing never completes as it gets stuck in a timeout loop.

Implement `RetryProgress` for limiting retry attempts in stages

---

libafl/src/events/centralized.rs
libafl/src/events/llmp.rs
libafl/src/events/tcp.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/transferred.rs
libafl/src/observers/mod.rs

This is useful for short-circuiting potentially expensive objective feedbacks, as well as for creating nodes which just perform analysis on inputs rather than actually fuzzing.

TransferFeedback for determining if a testcase was from another node

---

libafl/src/mutators/mod.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/mutators/scheduled.rs
libafl/src/mutators/tuneable.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/os/unix_signals.rs
libafl_bolts/src/tuples.rs

This PR adds a `.into_vec` function to `MutatorsTuple` and makes `Vec<Box<dyn Mutator<I, S>>>` implement `MutatorsTuple` - allowing us to use vecs instead of proper tuples in certain places.

Implement MutatorTuple for Vecs to allow Dynamic Mutator Choices

---

libafl/Cargo.toml
libafl_bolts/Cargo.toml
libafl_bolts/src/llmp.rs
libafl_qemu/src/hooks.rs

Point 3 here #1850
https://github.com/AFLplusplus/LibAFL/issues/1850#issuecomment-1971307249
While it is not possible to swap client_id with pid, because it is not no-std friendly.
I instead simply printed the pid and client id on the creation of LlmpSender.
Without this kind of info, it is literally IMPOSSIBLE to find the correspondence between the client_id and the pid, making it impossible to attach with gdb (because you don't know pid!)

Print PID when you create a new Llmp Sender.

---

Dockerfile

According to
<https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2109#note_47480476> adding the "-c" to the ENTRYPOINT is necessary to be able to run commands like `docker run libafl "cargo build"`

fix(Dockerfile): allow running commands with docker run

---

fuzzers/fuzzbench_ctx/Cargo.toml
fuzzers/fuzzbench_ctx/src/lib.rs

Cargo previously complained when loading `libafl` as a git dependency:
```
warning: skipping duplicate package `fuzzbench` found at `~/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/55a300d/fuzzers/fuzzbench`
```

fuzzbench_ctx: fix duplicate package warning

---

libafl/src/executors/inprocess/inner.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/executors/inprocess/stateful.rs

The refactoring made in #1900 introduced a wrong cast of the executor in the global state.
It was harmless in the end since it implements `HasObservers` and is only used as an implementor of this trait alone. But it could cause issues in the future if used as an `Executor` for example.

Fix cast to c_void of a non-executor object.

---

Dockerfile

Add `--locked` flag when installing `sccache` in the first stages to ensure the image gets built when the base image's Rust version satisfies `sccache`'s MSRV.
Fixes #1923 :bug:

Fix reproducibility of the docker image

---

.devcontainer/devcontainer.json
Dockerfile
libafl_qemu/src/emu.rs

fix(Dockerfile): setup for building libafl_qemu in Docker

---

libafl/src/mutators/mod.rs
libafl/src/stages/mod.rs
libafl_bolts/src/tuples.rs

Simply because pushing to the front of a vec feels wrong

Tiny optimization for into_vec

---

libafl_bolts/src/lib.rs
libafl_bolts/src/shmem.rs

Use `std::io::Error::last_os_error` instead of `libc::perror` for error printing in unix_shmem.

Fix os error printing in unix_shmem (#1406)

---

bindings/pylibafl/src/lib.rs
fuzzers/push_stage_harness/src/main.rs
fuzzers/tutorial/src/mutator.rs
libafl/src/mutators/encoded_mutations.rs
libafl/src/mutators/gramatron.rs
libafl/src/mutators/grimoire.rs
libafl/src/mutators/mod.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/mutators/multi.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/nautilus.rs
libafl/src/mutators/scheduled.rs
libafl/src/mutators/string.rs
libafl/src/mutators/token_mutations.rs
libafl/src/mutators/tuneable.rs
libafl/src/stages/mutational.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/tmin.rs
libafl/src/stages/tuneable.rs
libafl_targets/src/libfuzzer/mutators.rs

This removes the `stage_idx` parameter from mutators that nothing uses

Remove (almost) unused stage_idx

---

libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/probabilistic_sampling.rs
libafl/src/schedulers/queue.rs
libafl/src/schedulers/tuneable.rs
libafl/src/schedulers/weighted.rs

Because "No entries in corpus" alone is not helpful

Better error message instead of "No entries in corpus"

---

fuzzers/qemu_systemmode/src/fuzzer.rs

The call to `unwrap` in wrong here.

Fix unwrap in qemu_systemmode example.

---

libafl_bolts/Cargo.toml
libafl_bolts/src/serdeany.rs

While _technically_ unsound, this just might give us a build-agnostic anymap which would pre pretty nice to have to store and load state.

SerdeAnyMap: add `unsafe_stable_anymap` feature that uses `type_name` instead of `TypeId::of`

---

fuzzers/fuzzbench/src/lib.rs
fuzzers/tinyinst_simple/src/main.rs
libafl/src/feedbacks/list.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/observers/list.rs
libafl/src/observers/mod.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/report.rs

ListFeedback does not have accompanying ListFeedbackMetadata.
This is because this feedback is supposed to be used with tinyinst where they implement break point coverage, and only novel edges will be given back to the fuzzer.
Therefore for tinyinst this is fine, because every observed value is novel, no need to record accumulated set of values in addition.
The problem is what if this pre-requisite does not hold anymore,
Now this PR addresses this problem. by keeping an metadata and update them accordingly.

More usable ListFeedback

---

fuzzers/nyx_libxml2_parallel/src/main.rs
fuzzers/nyx_libxml2_standalone/src/main.rs
libafl_nyx/Cargo.toml
libafl_nyx/src/executor.rs
libafl_nyx/src/helper.rs
libafl_nyx/src/lib.rs
libafl_nyx/src/settings.rs

Initially, I only wanted to add the option to specify the input buffer size, but I ended up changing a couple things:
- New `NyxSettings` struct that is passed to `NyxHelper::new`.
- `NyxExecutor` takes ownership of `NyxHelper` instead of taking a mutable reference, this removes some lifetime complexity and I didn't see any reason against it.
- Remove dry run in `NyxHelper`. If QEMU didn't spawn, it should be noticed by `NyxExecutor` anyway.
Let me know if this makes sense and what you think.

libafl_nyx: Allow custom input buffer size to be passed to `NyxHelper`

---

fuzzers/baby_fuzzer_swap_differential/build.rs
fuzzers/baby_fuzzer_swap_differential/src/bin/libafl_cc.rs
fuzzers/baby_fuzzer_with_forkexecutor/src/main.rs

This PR starts to address issue #1907, targeting the warnings coming up in `fuzzers/baby_fuzzer*`

Clean up warnings in baby_fuzzers

---

libafl/src/executors/hooks/unix.rs
libafl/src/executors/hooks/windows.rs

First you can do nothing if it fails.
second it leads to infinite recursion inside crash handler for me.

Don't use unwrap() in the crash handler

---

fuzzers/nyx_libxml2_standalone/setup_libxml2.sh

On testing this on my machine not all neccessary files for fuzzing with nyx where provided by the setup_libxml2.sh. Compared to the nyx_libxml2_parallel fuzzer this packer generation line was missing (as also pointed to by @richinseattle in the discord). After adding this the fuzzer was able to start.

Update setup_libxml2.sh of nyx_libxml2_standalone fuzzer

---

docs/src/advanced_features/frida.md
libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/asan/hook_funcs.rs
libafl_frida/src/executor.rs

As discussed in #1988 this makes Frida ASan thread safe.
@s1341 can you check if this introduces runtime overhead?

Frida: Move ASAN_ERRORS values into a Mutex for shared access

---

libafl_bolts/src/llmp.rs

LLMP: Fix map size where allocated message is larger than the current map

---

libafl/src/events/llmp.rs

If I understand correctly. Here this line wants to say child_status == 9.
137 is the exit code for shell not for what you get in wait_status().
Another problem is error code 9 shouldn't always mean there was an oom. it should simply mean that SIGKILL was delivered to the process.
(Because you can send `kill -9 <PID>`, then, that's SIGKILL, too.)
and I don't think you can tell if a process was killed by OOM or not unless you check dmesg

child_status == 137 is strange

---

libafl/src/events/centralized.rs

This CentralizedEventManager's serialize_observers() has 99% the same code as LlmpEventManager.
The only difference is
```
const SERIALIZE_TIME_FACTOR: u32 = 4;
```
is 4 instead of 2 here.

Dedup CentralizedEventManager's serialize_observers() 

---

fuzzers/qemu_systemmode/Cargo.toml
fuzzers/qemu_systemmode/Makefile.toml
fuzzers/qemu_systemmode/build.rs
fuzzers/qemu_systemmode/src/fuzzer_breakpoint.rs
fuzzers/qemu_systemmode/src/fuzzer_classic.rs
fuzzers/qemu_systemmode/src/fuzzer_sync_exit.rs
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_build/src/build.rs
libafl_qemu/libafl_qemu_build/src/lib.rs
libafl_qemu/libafl_qemu_sys/Cargo.toml

* LibAFL QEMU can now be dynamically linked
* LibAFL QEMU reconfiguration happens less frequently
* Possibility to have custom rpath in QEMU
* Update to latest qemu-libafl-bridge

Rework of libafl_qemu configuration

---

fuzzers/forkserver_libafl_cc/src/main.rs
fuzzers/forkserver_simple/src/main.rs

Addresses some concerns following #1886.

Fix some missing tracking hints

---

fuzzers/forkserver_libafl_cc/src/main.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/qemu_cmin/src/fuzzer.rs

There was an inconsistency between two recent PRs #2012 and #2066. This one fixes it.

Fixing the inconsistency btw #2012 and #2066

---

fuzzers/baby_fuzzer_swap_differential/Makefile.toml
fuzzers/forkserver_libafl_cc/Makefile.toml
fuzzers/frida_libpng/Makefile.toml
fuzzers/fuzzbench/Makefile.toml
fuzzers/fuzzbench_ctx/Makefile.toml
fuzzers/fuzzbench_text/Makefile.toml
fuzzers/libfuzzer_libmozjpeg/Makefile.toml
fuzzers/libfuzzer_libpng/Makefile.toml
fuzzers/libfuzzer_libpng_accounting/Makefile.toml
fuzzers/libfuzzer_libpng_aflpp_ui/Makefile.toml
fuzzers/libfuzzer_libpng_centralized/Makefile.toml
fuzzers/libfuzzer_libpng_cmin/Makefile.toml
fuzzers/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/libfuzzer_libpng_norestart/Makefile.toml
fuzzers/libfuzzer_libpng_tcp_manager/Makefile.toml
fuzzers/libfuzzer_stb_image/Makefile.toml
fuzzers/libfuzzer_stb_image_sugar/Makefile.toml
fuzzers/nautilus_sync/Makefile.toml

This allows us to visually inspect fuzzer output in CI to check that local behaviour matches remote.

Use tee, not redirect

---

libafl_nyx/Makefile.libxdc
libafl_nyx/build_nyx_support.sh

Fixing some problems with build_nyx_support.sh. 
Providing Makefile for bug in qemu-nyx
!!Did not test on Ubuntu!! Hope somebody will !
Since packer is made for Ubuntu I had to test with modifications which are not part of the commit. But the fuzzers did run.
Still known bug:
The used qemu-nyx cpu is hardcoded in the dependency libnyx. But the cpu should be changed depending on if kvm-nyx is available or not. (But its working anyway)

Update libafl_nyx to newest qemu-nyx and nyx-packer

---

fuzzers/nyx_libxml2_standalone/setup_libxml2.sh

Fix typo in setup_libxml2.sh

---

libafl/src/mutators/gramatron.rs
libafl/src/mutators/grimoire.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/mutators/scheduled.rs
libafl/src/mutators/tuneable.rs
libafl/src/schedulers/accounting.rs
libafl/src/schedulers/minimizer.rs
libafl/src/schedulers/probabilistic_sampling.rs
libafl/src/schedulers/weighted.rs
libafl_bolts/src/rands.rs
utils/libafl_benches/benches/rand_speeds.rs

First, I'd like to thank you for an excellent library!
I started playing around with libafl and reading the source code, and quickly noticed that there are some things that could be improved in the `rands` module of `libafl_bolts`. I've tried to make the commits in this PR relatively self-contained:
- f5ef082f5e10966108d7ef4b3cce50f4c764a276 fixes seeding problems,
- 8298cb7bd6aa1ce8f26b6925c14b3b427dcc43e3 improves the speed of bounded number generation,
- 99515355a4535b46030251c532c7ebe1707c72fa, 40a45d6b4892ece167dba108540e7d14517d2879 and 19bbf443baec36ad605ff80bd9991acd0524e383 add convenient utility functions,
- fbea313c45274f5a0bb9053b2d13a6fc9903f9c4 adds SFC64 PRNG.
Would gladly discuss and rework anything that raises concerns.

libafl_bolts: some improvements to the `rands` module

---

libafl/src/state/mod.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/os/unix_signals.rs

Introduce AFL_EXIT_ON_SEED_ISSUES

---

libafl_qemu/src/emu.rs
libafl_qemu/src/snapshot.rs

Just a simple reduction in the amount of code that needs to be maintained.

refactor(snapshot.rs): use const generics

---

libafl/src/corpus/mod.rs
libafl/src/generators/gramatron.rs
libafl/src/generators/mod.rs
libafl/src/mutators/encoded_mutations.rs
libafl/src/mutators/gramatron.rs
libafl/src/mutators/grimoire.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/mutators/multi.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/scheduled.rs
libafl/src/mutators/string.rs
libafl/src/mutators/token_mutations.rs
libafl/src/mutators/tuneable.rs
libafl/src/stages/mutational.rs
libafl/src/stages/power.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/tuneable.rs
libafl_bolts/src/rands.rs

Continuing where #2086 left off.
As for faster 32-bit fallback for `fast_bound`, I realized that it will make the values you get different on 32-bit and 64-bit machines (using the same PRNG seed), which sounds bad.
We should either accept the slight speed penalty on machines without fast full-width 64-bit multiply, or say "gotta go fast" and accept the bias you get from 32-bit multiply version. I think favoring 64-bit platforms here is reasonable, since probably the vast majority of fuzzing is done on them.

libafl_bolts: more `rands` improvements

---

fuzzers/libfuzzer_libpng/src/lib.rs
libafl_bolts/src/llmp.rs

This adds a blocking version of `recv_buf_with_flags` to both the llmp receiver and client. This allows for easier creation of external LLMP clients.

Add recv_blocking_with_flags

---

libafl/src/corpus/minimizer.rs
libafl/src/feedbacks/map.rs
libafl/src/mutators/scheduled.rs
libafl/src/mutators/token_mutations.rs
libafl/src/observers/cmp.rs
libafl/src/observers/map.rs
libafl/src/observers/value.rs
libafl/src/schedulers/accounting.rs
libafl/src/schedulers/minimizer.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/os/unix_shmem_server.rs
libafl_bolts/src/ownedref.rs
libafl_bolts/src/shmem.rs
libafl_concolic/symcc_runtime/src/filter/coverage.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/observers.rs
libafl_targets/src/sancov_8bit.rs

Redux of #2000.
Previously, `MapFeedback` required the `Observer` to implement `AsIter`, and to give out references via `.get` and `.get_mut`. This works for all the existing in-repo `MapObserver`s, which use `unsafe` to pretend that they own the underlying map/vector/array. This lets them loan out items in the array with the same lifetime as `&self`.
This wasn't previously possible for observers using `RefCell`, as the loan of the content of a `RefCell` by definition has a shorter lifetime than the `RefCell` itself. With the changes here, we can have a `MapObserver` built in safe Rust, i.e., `RefCellValueObserver<Vec<...>>`
`MapFeedback` already requires that all the values are `Copy`, and in practice, they're generally small (in fact, they're generally primitive integers, meaning …

Allow for AsIter(Mut)/AsSlice(Mut) to be implemented in safe Rust

---

libafl_qemu/libqasan/Makefile
libafl_qemu/libqasan/hooks.c
libafl_qemu/libqasan/libqasan.h
libafl_qemu/libqasan/mmap.c

Added qasan hooks for mmap and munmap. When `mmap` is called, the allocated memory region is unpoisoned.

add mmap hooks to libqasan

---

fuzzers/frida_gdiplus/src/fuzzer.rs
libafl/src/events/launcher.rs

Previously setting the stdout_file in the launcher, while not forking would only result in the stdout being forwarded from the child processes to the parent process, but not written into the specified location.
This PR changes this behaviour to make the parent and all children write into the log file. It also hides the file in non-unix builds. This means, unless debug output is set, on non-unix platforms the stdio from child processes is hidden.
Discovered while debugging https://github.com/AFLplusplus/LibAFL/issues/2111

Allow setting stdout_file in non-fork launcher

---

fuzzers/backtrace_baby_fuzzers/command_executor/src/main.rs
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
libafl/src/executors/command.rs

I have a complex `Input` and would like to map the struct's field to different parts of a command (multiple args, stdin, etc.). To be able to do this, `CommandExecutor` should be generic in the specific `Input` used in the fuzzer. With the current version, `CommandExecutor`s can basically only ever be used with `BytesInput`, since only the bytes are accessible (via the constraint on `HasTargetBytes`). With these changes, all exposed data from the `Input` struct is available in the implementation.
This is just what I came up with, it may still have room for improvement.

Making CommandExecutor generic on the specific Input

---

libafl_qemu/src/emu/systemmode.rs

It's not guaranteed that the `devices` list will be null terminated, so the QEMU function `is_in_list` might loop out of range and cause a SIGSEGV on the `strcmp`.

Add null ptr to devices vector

---

libafl_bolts/Cargo.toml
libafl_bolts/src/tuples.rs

This is right up there with the evilest code I've ever written.
```rs
struct A;
struct B;
fn main() {
println!("A is A: {}", type_eq::<A, A>()); // true
println!("A is B: {}", type_eq::<A, B>()); // false
}
```
This performs a type equality comparison using Copy/Clone specialisation imported from core. In testing, I found that it is optimized out entirely, i.e.:
```rs
fn main() {
if type_eq::<A, A>() {
abort();
}
}
```
Is compiled down to:
```
> disass copy_specialization::main
Dump of assembler code for function _ZN19copy_specialization4main17h45816c84b6311796E:
0x000055555555c260 <+0>:     push   rax
=> 0x000055555555c261 <+1>:     call   QWORD PTR [rip+0x4a8f9]        # 0x5555555a6b60 (std::process::abort)
End of assembler dump.
```

Stable type_eq

---

libafl_libfuzzer/build.rs

TL;DR: The LLVM 14 bfd gold linker plugin, which is used by `nm` is not compatible with libraries compiled with LLVM 18 (default since a few days in Rust)
I was confused by [this issue](https://github.com/AFLplusplus/LibAFL/issues/2039) and wanted to dig deeper why with LLVM 14 installed, compilation fails.
It turned out that the package `llvm-14-linker-tools` installs a bfd plugin at `/usr/lib/bfd-plugins/LLVMgold-14.so` which is used by the system `nm` tool.
The `nm` tool is used to relocate the symbols under a namespace. If the LLVM 14 bfd plugin is installed then the relocations miss the following relocations:
```
_ZN101_$LT$std..os..unix..net..addr..SocketAddr$u20$as$u20$std..os..net..linux_ext..addr..SocketAddrExt$GT$16as_abstract_name17hc452dbc34e1bfe57E …
```

Fix libafl_libfuzzer's compatibility with LLVM 14

---

libafl_qemu/runtime/libafl_qemu.h

This fixes the "bindings generation" reported in #2128. It is a shot in the dark: this is enough to make it compile (or reach the other error in that issue), but I don't know for sure it is correct nor do I know how to properly test it. I would advise someone to test this, or at least someone more familiar with the code and calling conventions should review it before assuming it is correct.
This file also caused `libafl_qemu_stub_bindings.rs` to update after rebuilding. Should I commit the changes in that file? If the file is autogenerated, should it be ignore by git altogether?

Add qemu runtime defs for aarch64

---

libafl_qemu/libafl_qemu_build/src/bindings.rs
libafl_qemu/libafl_qemu_build/src/lib.rs
libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs
libafl_qemu/src/emu/mod.rs
libafl_qemu/src/hooks.rs
libafl_qemu/src/qemu/mod.rs

Fix #2128
Also, avoid writing 2 times bindings to filesystem.

Fix regex fixing generated bindings for QEMU

---

libafl/Cargo.toml

Reverts AFLplusplus/LibAFL#2169
```rust
error: failed to run custom build command for `libz-ng-sys v1.1.15`
Caused by:
process didn't exit successfully: `/home/runner/work/LibAFL/LibAFL/target/x86_64-unknown-linux-gnu/release/build/libafl_libfuzzer-fe1e0e503aac7e96/out/libafl_libfuzzer/release/build/libz-ng-sys-a9d11f6fafc12dfd/build-script-build_zng` (exit status: 101)
--- stdout
```

Revert "Update zip requirement from 0.6 to 1.2"

---

libafl/src/executors/inprocess_fork/mod.rs

The `test_inprocessfork_exec` fn didn't use `serial`, so it will fail on MacOS where only one `StdShMemProvider` can exist at any time

Fix MacOS CI race condition

---

libafl/src/monitors/disk.rs

This adds all client_stats to the continuous JSON logging file. This is nice for visualization, e.g., here: https://github.com/eknoes/libafl-dashboard
If you think that its too much, saving all client stats, I could also make it configurable, however you guys prefer.

Add client_stats to OnDiskJSONMonitor

---

libafl/src/stages/calibrate.rs
libafl/src/stages/colorization.rs
libafl/src/stages/power.rs
libafl/src/stages/sync.rs

add AFL stage names for calibration, colorization, power and sync stages

---

libafl_libfuzzer/libafl_libfuzzer_runtime/src/fuzz.rs

I saw that coverage is not printed when not using `-fork=1`. This changes the output to include coverage.

Use MultiMonitor when fuzzing in non-forking mode

---

libafl/src/stages/sync.rs

Previously, the synchronization process in `SyncFromDiskStage` would get the fuzzer stuck in an infinite loop if one of the synced files caused the target to crash or timeout. This issue arose because `state.last_time` was updated only after all files were evaluated. If a file caused the target to crash, `state.last_time` wasn't updated, leading the fuzzer to continuously sync the same buggy testcases, resulting in an infinite loop.
Now, files are added to `self.to_sync` for syncing, and `state.last_time` is updated only after each file has been successfully evaluated. Additionally, files are removed from `self.to_sync` before evaluation to prevent duplicate processing, ensuring that each file is processed exactly once.

Fixed infinite loop on SyncDiskStage

---

libafl/src/corpus/mod.rs
libafl/src/fuzzer/mod.rs
libafl/src/mutators/token_mutations.rs
libafl/src/stages/generalization.rs
libafl/src/stages/mod.rs
libafl/src/stages/push/mod.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/stats.rs
libafl/src/stages/tmin.rs
libafl/src/state/mod.rs

See discussion in #2201 -> https://github.com/AFLplusplus/LibAFL/pull/2201#issuecomment-2118940872
We currently use `CorpusId` but `current_corpus_idx`, technically confusing index and identifier...
Now that stages get a true index, we'll have to rename the corpus case

Rename CurrentCorpusIdx -> CurrentCorpusId

---

scripts/fmt_all.sh

Makes `fmt_all.sh` 30 times faster on my local machine.
Requires `parallel` to work, but I think it's not a problematic dependency.

Faster fmt_all.sh

---

utils/gramatron/construct_automata/src/main.rs

Clippy in main claims it doesn't want to infer this type, so maybe this helps.

Confuse clippy less

---

libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/hook_funcs.rs
libafl_frida/src/cmplog_rt.rs
libafl_frida/src/coverage_rt.rs
libafl_frida/src/drcov_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/lib.rs
libafl_frida/src/utils.rs

This patch fixes hook_func and implements deinit. The issue with hook_func was that hooked implementations would run in non-harness code as well (Resulting in odd errors from stalked portions of frida). This has been fixed.
Startup should also be much faster on macos as it was earlier attempting to poison the MALLOC_NANO region which is unusually high in memory resulting in 1 min+ startup. 
Should pass all tests now on unix and macos.

Fix hook_func and implement deinit

---

libafl/src/fuzzer/mod.rs
libafl_frida/src/asan/hook_funcs.rs

This PR adds the ability to 'sample' testcases. In other words it allows for a user-specified 'sampling rate', which is used to decide which TestCases to send to the broker.
A sampling rate of 10 means that only every tenth TestCase is sent to the broker.
This can be useful in very large scale fuzzing where the broker is overwhelmed by the volume of TestCases, and to cause the fuzz nodes to diverge somewhat more from each other.

Add testcase sampling rate

---

fuzzers/frida_gdiplus/src/fuzzer.rs
libafl/src/events/launcher.rs

This adds a `launch_delay` option, which specifies a delay in milliseconds to wait between launches of fuzzers.

launcher: add launch_delay option

---

libafl/src/corpus/cached.rs
libafl/src/corpus/inmemory.rs
libafl/src/corpus/inmemory_ondisk.rs
libafl/src/corpus/mod.rs
libafl/src/corpus/nop.rs
libafl/src/corpus/ondisk.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/corpus.rs

Rename peek_next_free_id to peek_free_id (that it's the next is obvious)

---

fuzzers/nautilus_sync/src/lib.rs
fuzzers/nyx_libxml2_parallel/src/main.rs
fuzzers/nyx_libxml2_standalone/src/main.rs
fuzzers/tinyinst_simple/src/main.rs
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/tcp.rs
libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/inprocess/inner.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/executors/inprocess/stateful.rs
libafl/src/observers/concolic/serialization_format.rs
libafl_bolts/src/build_id.rs
libafl_bolts/src/shmem.rs
libafl_frida/src/helper.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/merge.rs
libafl_nyx/src/executor.rs
libafl_sugar/src/forkserver.rs
libafl_targets/build.rs
libafl_tinyinst/src/executor.rs

Unifies all builders.  Unionize!
Also adds a NopShMemProvider and fixes a bunch of new clippy lints.

Make every Builder ::builder(), so  BobTheBuilder::new() becomes BobThe::builder()

---

fuzzers/qemu_systemmode/src/fuzzer_breakpoint.rs
fuzzers/qemu_systemmode/src/fuzzer_sync_exit.rs
libafl_qemu/libafl_qemu_build/src/build.rs
libafl_qemu/src/command/mod.rs
libafl_qemu/src/emu/mod.rs
libafl_qemu/src/emu/systemmode.rs
libafl_qemu/src/qemu/mod.rs
libafl_qemu/src/qemu/systemmode.rs

check qemu snapshot correctness generically, with better typing.
for now, it mostly concerns systemmode since usermode snapshot does not implement the `SnapshotManager` trait yet.

Generic QEMU snapshot checking

---

libafl_libfuzzer/libafl_libfuzzer_runtime/src/lib.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/merge.rs
libafl_libfuzzer/src/lib.rs

@addisoncrump copy&pasted these from the main lib. It doesn't change much and right now doesn't catch anything, either, but might be nice to have

LibAFL_Libfuzzer: Add clippy warnings

---

libafl/src/feedbacks/mod.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/tmin.rs

This simple `Feedback` just checking if any kind of `ExitKind::Diff` was returned. If you're doing differential fuzzing, you'll most likely use this.

Adding DiffExitKindFeedback

---

libafl/Cargo.toml
libafl/src/corpus/testcase.rs
libafl/src/feedbacks/concolic.rs
libafl/src/feedbacks/differential.rs
libafl/src/feedbacks/list.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/nautilus.rs
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/feedbacks/stdio.rs
libafl/src/feedbacks/transferred.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/tmin.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/lib.rs
libafl_frida/Cargo.toml
libafl_frida/src/asan/errors.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/src/feedbacks.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/tmin.rs
libafl_nyx/src/executor.rs
libafl_qemu/src/emu/mod.rs
libafl_targets/Cargo.toml
libafl_targets/src/libfuzzer/observers/oom.rs

Work in progress.
I decided to use Name instead of Handle since Feedback is a trait and I'm not sure how that would work for Testcase since Handle expects a type. Maybe we can make a wrapper type? `TrackedFeedback`?
Once the general approach is decided, the implementation will be done for `Objective` as well

Introduce feedbacks hit tracking for testcases

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
scripts/fmt_all.sh

I thought it would be nice to share this, I've been using it for a few days and it's convenient.
It should also help lighten the CI's burden, avoiding useless runs.
Maybe we also would like to run other things in the future, for now I only put fmt since it's fast and does not cost much to have around.

Pre-commit hooks

---

libafl_bolts/src/tuples.rs

This allows for the mapping of all tuple members to another type, potentially as a generic of the original type.
See the test for details.

Implement tuple mapping

---

fuzzers/dynamic_analysis/Cargo.toml

```
warning: skipping duplicate package `fuzzbench` found at `~/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/058e15f/fuzzers/fuzzbench`
```

Fix duplicate package warning

---

fuzzers/tutorial/Cargo.toml

https://github.com/AFLplusplus/LibAFL/pull/2254#discussion_r1617344909
I can't reproduce this serde error https://github.com/AFLplusplus/LibAFL/pull/2254#discussion_r1617377032. Let's see if CI likes it.

Tutorial fuzzer: Switch lain fork to AFLplusplus/lain

---

fuzzers/libfuzzer_libpng_centralized/src/lib.rs
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs

the closures are different for the main node and the secondary nodes for finer-grained configuration.

Closure builder for inner managers of centralized.

---

libafl/src/schedulers/weighted.rs

WeightedScheduler would never report a complete cycle since the runs would always be set to zero before it got the chance to surpass the corpus count. This PR fixes it

fix WeightedScheduler reporting incorrect queue cylces

---

libafl/src/events/launcher.rs
libafl/src/events/llmp/hooks/centralized.rs
libafl/src/events/llmp/hooks/mod.rs
libafl/src/events/llmp/restarting.rs
libafl_bolts/examples/llmp_test/main.rs
libafl_bolts/src/llmp.rs

- `SP` is not needed
- `LlmpBrokerState` is strange, you have method calls such as `self.state_mut().forward_msg(msg)?;`, but a state will send nothing. renamed it to`LlmpBrokerInner`

Cleanup for #2280

---

libafl_libfuzzer/build.rs

- features check was inverted
- print helpful message when `llvm-nm` wasn't found, which happens to be the case on _stable_

fix: `libafl_libfuzzer` build script

---

libafl/Cargo.toml
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/mod.rs
libafl_frida/src/asan/hook_funcs.rs
libafl_sugar/Cargo.toml
libafl_sugar/src/forkserver.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs
libafl_targets/src/sancov_pcguard.rs

why not?
i'm tired of seeing repeated code in event manager. these cfgs are totally not needed
also clean up the API a bit.
because now we should always pass the Handle<Something> to the interface

Make adaptive serialization into default

---

libafl/src/schedulers/powersched.rs
libafl/src/schedulers/weighted.rs

Based on:
https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz.c#L2764-L2798
There are a few schedules which need to be implemented

Add support for cycling PowerSchedule on completion of a queue cycle in WeightedScheduler

---

libafl/src/feedbacks/mod.rs

This does not change any functionality, but makes the macros a bit easier to use, because they don't fail to match if there is a trailing comma for some reason.

Allow trailing comma in feedback macros

---

libafl/src/feedbacks/map.rs

The original implementation:
```rust
{
if history_map[i] == initial {
map_state.num_covered_map_indexes += 1;
}
history_map[i] = R::reduce(history_map[i], value);
}
```
`num_covered_map_indexes` may be also counted if `R::reduce(histroy_map[i], value)` returns `history_map[i]` and `history_map[i]` is the initial value. For instance, given `history_map[i] = 0, value = -1, R::reduce = max`, `num_covered_map_indexes` is updated but `history_map[i]` doesn't change and is still 0, as the initial value. This soon falsely triggers the debug_assert:
```rust
debug_assert!(
history_map
.iter()
.fold(0, |acc, x| acc + usize::from(*x != initial))
== map_state.num_covered_map_indexes,
"history_map had {} filled, but map_state.num_covered_map_indexes was {}",
history_map
.iter()
.fold(0, |acc, x| acc + …
```

Fix debug assert on map_state.num_covered_map_indexes

---

libafl/Cargo.toml
libafl/src/events/broker_hooks/centralized_multi_machine.rs
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/mod.rs
libafl/src/events/multi_machine.rs
libafl/src/events/tcp.rs
libafl/src/lib.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/llmp.rs
libafl_qemu/libafl_qemu_sys/src/lib.rs

A bunch of smaller cleanups addressing my comments in PR #2302

Address comments from #2302

---

libafl/src/events/llmp/mgr.rs

This applies the same behavior as ``TcpEventManager::handle_in_client``
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/events/tcp.rs#L616-L618

Fix LlmpEventManager not calling hooks pre_exec

---

libafl_bolts/src/lib.rs

the feature `error_in_core` has been stable since 1.81.0-nightly and no longer requires an attribute to enable

bolts: fix warning about `error_in_core` now stable

---

libafl_qemu/src/helpers/injections.rs
libafl_targets/Cargo.toml
libafl_targets/src/libfuzzer/mutators.rs

This addresses the issue reported in #2345 and removes the needless double copy

Fix LLVMFuzzerCustomMutator with different sizes

---

fuzzers/cargo_fuzz/README.md
fuzzers/dynamic_analysis/README.md

In light of #424 i fixed some typos in the cargo_fuzz README and also in the dynamic_analyis README. 
In the latter one the instructions lack anything about the corpus right now. Would it be possible to just commit some files into the repository and have the user extend them as needed?

Improved documentation for fuzzers/cargo_fuzz and dynamic_analysis

---

libafl/src/events/centralized.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/tcp.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/tmin.rs

Some functions have really strange names.
execute_no_process doesn't execute anything.
execute_and_process doesn't execute anything either.
i just rename it to make them have proper names

Rename some functions in fuzzer.rs

---

libafl_bolts/src/serdeany.rs

Wrap metadata elements in Cow

---

libafl/src/monitors/tui/ui.rs

The length constraint on the bottom areas was set to 0 and thus those two blocks were invisible. We adjusted those to the correct values to show all lines & also removed the unnecessary extra chunk layout variable.

tui: make client bottom layouts visible again

---

libafl/src/executors/inprocess_fork/mod.rs

On Linux, when fuzzing a Rust target, set `panic = "abort"` in your `Cargo.toml` (see [Cargo documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#panic)).
This PR adds this hint.

Add documentation for InProcessForkExecutor

---

libafl/src/common/nautilus/grammartec/mutator.rs
libafl/src/common/nautilus/grammartec/tree.rs
libafl_frida/src/cmplog_rt.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/rustfmt.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/src/corpus.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/misc.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/schedulers.rs
libafl_qemu/src/command/mod.rs
libafl_qemu/src/helpers/asan.rs
libafl_qemu/src/helpers/mod.rs
libafl_qemu/src/helpers/snapshot.rs

We use it everywhere so we should continue doing so. We should especially not mix and match both.

Replace uses std HashMap with hashbrown for consistency

---

.github/workflows/build_and_test.yml

Qemu CI was running iif `libafl_qemu` or qemu-related fuzzers changed.
Recently (#2373) it caused an issue where a `libafl` change impacted negatively `libafl_qemu` but was not detected by the CI (since it was not being run).
now qemu CI will run also when its dependencies change.

Run Qemu CI more

---

libafl_qemu/runtime/libafl_qemu.h

Minor fix to `libafl_qemu.h`.
A while back the function switched from `_libafl_exit_call2()` to `_libafl_sync_exit_call2()` but `LIBAFL_QEMU_INPUT_PHYS` didn't get updated.

update function from _libafl_exit_call2 to _libafl_sync_exit_call2

---

libafl_frida/src/asan/asan_rt.rs

This attempts to fix multi-threaded target issues with hooking, by making sure that the 'recursion blocker' is thread local, instead of using the global `hooks_enabled` variable.

frida: make hooks thread local

---

libafl_qemu/libqasan/libqasan.c

Noticed the missing return statement while building `libafl_qemu`:
```
libqasan.c:364:1: warning: non-void function does not return a value [-Wreturn-type]
364 | }
| ^
1 warning generated.
```

libqasan: Add missing return to qasan_swap

---

libafl_qemu/libqasan/string.c

Some firmware has named tolower differently in it's libraries. Ideally, one would use the correct cross-compiler for libqasan, but this can be tricky to figure out. Since tolower is a trivial function, adding it in libqasan helps make the library more compiler agnostic and easier to use.

Added a tolower implementation in libqasan

---

fuzzers/others/libafl-fuzz/Makefile.toml
libafl/src/corpus/inmemory_ondisk.rs
libafl_targets/src/cmplog.h
libafl_targets/src/cmps/mod.rs

only set testcase filepath if filepath is none

Fix cmplog implementation

---

libafl/src/feedbacks/mod.rs

It is currently not possible to use a `NotFeedback` or `ConstFeedback` (or a combination thereof) for a `StdTMinMutationalStage`, because both of these feedback types do not implement `FeedbackFactory`.
This PR implements `FeedbackFactory` for both.

libafl: Implement FeedbackFactory for {Const,Not}Feedback

---

docs/src/getting_started/setup.md

Fix a small typo for the `rustup` command. Although `rustup upgrade` works (it fallback to `rustup update`), the official subcommand is `rustup update`

Fix rustup command in the LibAFL book

---

libafl_bolts/Cargo.toml

> Caret requirements are the default version requirement strategy, it is recommended to use the simplified syntax when possible. [Source](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)

Uniform deps versions: do not use caret requirements

---

libafl/src/corpus/minimizer.rs

There is an issue in the interaction between StdWeightedScheduler and CorpusMinimizers. 
StdWeightedScheduler calls [on_next_metadata](https://docs.rs/libafl/latest/src/libafl/schedulers/mod.rs.html#143) which in turns calls `state.corpus().current()`. Because the current entry is not made None, the current could be outdated.

Minimizer fix

---

libafl/src/mutators/token_mutations.rs

There is an issue in `I2SRandReplace` where not all indexes are checked. We can go all the way to `=len-sizeof(cmp_val_size)`. This is because when we extract the word from the bytes, we do `i..i+sizeof(cmp_val_size)` which is equivalent to `len-sizeof(cmp_val_size)..len` which is valid.

Fix i2srandreplace

---

libafl/src/stages/calibrate.rs

The if-statement right before the removed line already ensures that `bitmap_size >= 1`

Remove redundant line

---

libafl/src/events/mod.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/logics.rs
libafl/src/stages/mod.rs
libafl/src/state/mod.rs
libafl/src/state/stack.rs
libafl_libfuzzer/runtime/src/fuzz.rs
libafl_libfuzzer/runtime/src/report.rs

See[ `HasCurrentCorpusId`](https://docs.rs/libafl/latest/libafl/corpus/trait.HasCurrentCorpusId.html)

Rename HasCurrentStage to HasCurrentStageId for Consistency

---

libafl/src/executors/inprocess_fork/mod.rs

`cargo test -p libafl --no-default-features --features=std ` results into a bunch of unused import errors, moving the cfg at mod level fixes the issue.
Thanks

Move cfg to avoid unused import error on cargo test

---

.devcontainer/devcontainer.json
Dockerfile
scripts/createAliases.sh

This removes a workaround no longer necessary to install LLVM and updates the rust-analyzer plugin to use the official name, although the old one is aliased to my knowledge. 
A possible improvement to the build time of the Devcontainer image would be to utilize [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) to download the binary release for sccache. Let me know if that is a worthwhile improvement and i'll add it.

Small improvements to the devcontainer

---

libafl_qemu/src/emu/hooks.rs
libafl_qemu/src/emu/mod.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/modules/calls.rs
libafl_qemu/src/modules/cmplog.rs
libafl_qemu/src/modules/edges.rs
libafl_qemu/src/modules/mod.rs
libafl_qemu/src/modules/usermode/asan.rs
libafl_qemu/src/modules/usermode/asan_guest.rs
libafl_qemu/src/modules/usermode/drcov.rs
libafl_qemu/src/modules/usermode/injections.rs
libafl_qemu/src/modules/usermode/snapshot.rs

I modified emulator hooks to have state as the argument. in this way we can, for example, change the metadata before and after the execution.

Change Qemu hook signature

---

fuzzers/baby/baby_fuzzer_custom_input/Cargo.toml
fuzzers/baby/baby_fuzzer_custom_input/src/input.rs
fuzzers/baby/baby_fuzzer_custom_input/src/main.rs
libafl/src/mutators/havoc_mutations.rs

- Follow-up to #2422.
- Closes #2202 since that is still open for some reason.
@domenukk Here's your cleanup, thanks for noticing!

Code Cleanup

---

libafl/src/executors/forkserver.rs
libafl/src/inputs/bytessub.rs
libafl/src/inputs/mod.rs

This should fix the builder issue reported in #2538

Fix ForkserverExecutorBuilder::shmem_provider (#2539)

---

libafl/src/executors/command.rs
libafl/src/observers/concolic/serialization_format.rs

This fixes #2541 by un-commenting what was commented out in #2167

Bring back placeholder value in CommandExecutor to fix #2541

---

libafl_bolts/src/shmem.rs

This PR fix this panic on macOS:
```
thread '<unnamed>' panicked at /Users/jeremie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libafl_bolts-0.13.2/src/shmem.rs:695:68:
range end index 20 out of range for slice of length 19
```

Fix panic in mmap shmem when full_file_name is less than MAX_MMAP_FILENAME_LEN

---

libafl/src/executors/forkserver.rs

@tokatoka does it ever make sense to run with `None` as map_size?

Make map size mismatch return a proper error instead of abort

---

libafl/src/corpus/inmemory_ondisk.rs
libafl/src/corpus/ondisk.rs
libafl/src/corpus/testcase.rs
libafl/src/events/broker_hooks/mod.rs
libafl/src/events/centralized.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/fuzzer/mod.rs
libafl/src/monitors/mod.rs
libafl/src/stages/sync.rs
libafl/src/stages/tmin.rs
scripts/clippy.sh

adding exec count info into a testcase (or objective) event does not feel right. i don't think knowing how many execs were required to find a testcase is important (afaik)
the main downside is that it reduces the responsiveness of the monitor.
imho we should send more heartbeats if we want to increase it.

Do not embed client exec count in testcase and objective

---

fuzzers/binary_only/frida_executable_libpng/Cargo.toml
fuzzers/binary_only/frida_gdiplus/Cargo.toml
fuzzers/binary_only/frida_libpng/Cargo.toml
libafl_frida/Cargo.toml
libafl_frida/src/executor.rs
libafl_frida/src/lib.rs

Update frida to 0.14.0

---

libafl/src/monitors/prometheus.rs

If a user starts a logger doing `env_logger::init()` in their fuzzer, it will collide with the logger started in prometheus (`tide::log::start();`).
@peterwhitingyb @domenukk what's the purpose of `tide::log::start()`? Should we remove it or it's me that doesn't know how to use `env_logger`?

Do not start another logger in prometheus

---

libafl_qemu/src/qemu/mod.rs

This error happens when building fuzzers/binary_only/qemu_launcher with cargo check for example

fix error[E0308]: mismatched types for libafl_qemu_init

---

.vscode/settings.json
fuzzers/forkserver/libafl-fuzz/src/feedback/persistent_record.rs
fuzzers/forkserver/libafl-fuzz/src/feedback/seed.rs
fuzzers/forkserver/libafl-fuzz/src/stages/time_tracker.rs
fuzzers/fuzz_anything/push_harness/src/main.rs
fuzzers/structure_aware/baby_fuzzer_custom_input/src/input.rs
fuzzers/structure_aware/baby_fuzzer_custom_input/src/main.rs
fuzzers/structure_aware/baby_fuzzer_gramatron/src/main.rs
libafl/Cargo.toml
libafl/src/executors/forkserver.rs
libafl_bolts/Cargo.toml
libafl_bolts/examples/llmp_test/main.rs

Unless if you only use prelude _exclusively_, there's no reason to use prelude at all.
This removes the default feature. It can still be used by adding it in Cargo.toml.
This will stop confusing rust-analyzer etc.

Remove prelude from default features

---

libafl/src/executors/forkserver.rs

When the fork server read a value from the pipe via `read_st_size`, the call `self.st_pipe.read()` may not read exactly `size` bytes. This happens when `size` is large (e.g., > 65535). In this case, we will run into the error at line 958 when the AUTODICT in the target is large.
https://github.com/AFLplusplus/LibAFL/blob/a69cd9843248665c3f6e5b519e045eada091c6d3/libafl/src/executors/forkserver.rs#L955-L959
When `size` is large, multiple reads are required to fill the buffer until `read` returns 0.

Fix pipe I/O in forkserver

---

fuzzers/inprocess/dynamic_analysis/src/lib.rs

the compiler produces warnings in fuzzers/inprocess/dynamic_analysis:
```
warning: creating a mutable reference to mutable static is discouraged
--> src/lib.rs:255:72
|
255 |     let func_list = unsafe { OwnedMutPtr::from_raw_mut(Lazy::force_mut(&mut FUNCTION_LIST)) };
|                                                                        ^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
|
= note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
= note: this will be a hard error in the 2024 edition
= note: this mutable reference has lifetime `'static`, but if the static gets accessed (read or written) by any other means, or any other reference is created, then any further use of this mutable reference is Undefined Behavior
= note: …
```

minor: fix mutable reference warning in examples/dynamic_analysis

---

.github/workflows/build_and_test.yml
fuzzers/full_system/qemu_baremetal/Cargo.toml
fuzzers/full_system/qemu_baremetal/src/fuzzer_low_level.rs
libafl_qemu/Cargo.toml
libafl_qemu/build.rs
libafl_qemu/build_linux.rs
libafl_qemu/libafl_qemu_sys/Cargo.toml
libafl_qemu/libafl_qemu_sys/build_linux.rs
libafl_qemu/libafl_qemu_sys/src/lib.rs
libafl_qemu/libafl_qemu_sys/src/usermode.rs
libafl_qemu/src/command/mod.rs
libafl_qemu/src/emu/builder.rs
libafl_qemu/src/emu/drivers.rs
libafl_qemu/src/emu/hooks.rs
libafl_qemu/src/emu/mod.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/lib.rs
libafl_qemu/src/modules/calls.rs
libafl_qemu/src/modules/cmplog.rs
libafl_qemu/src/modules/drcov.rs
libafl_qemu/src/modules/edges.rs
libafl_qemu/src/modules/mod.rs
libafl_qemu/src/qemu/config.rs
libafl_qemu/src/qemu/hooks.rs
libafl_qemu/src/qemu/mod.rs
scripts/clippy.sh
scripts/parallellize_cargo_check.py

This PR follows discussion https://github.com/AFLplusplus/LibAFL/discussions/2505
**TLDR:** Using only the feature flag simplifies things a bit and allows the usage of optional dependencies

Avoid using feature flags and env variable to set the same parameter pt.1 emulation_mode

---

libafl/src/corpus/inmemory_ondisk.rs
libafl/src/generators/nautilus.rs
libafl/src/observers/profiling.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/lib.rs
libafl_bolts/src/serdeany.rs

Not sure if we want this, it makes using serde_json a bit more annoying (errors need to be mapped).
Then again, it makes libafl_bolts a bit more lightweight.
Related to #2638

Remove serde_json dependency from libafl_bolts

---

libafl_bolts/src/shmem.rs

Small change, makes it much more convenient to use. You'll typically call `persist_for_child_processes` during creation, and if the method takes a borrow, it requires two statements. Now, it can be done in one.

Moving ShMem persisting to take an owned value

---

fuzzers/binary_only/frida_executable_libpng/Makefile.toml
fuzzers/binary_only/frida_libpng/Makefile.toml
fuzzers/binary_only/frida_windows_gdiplus/Makefile.toml
fuzzers/binary_only/fuzzbench_qemu/Makefile.toml
fuzzers/binary_only/qemu_cmin/Makefile.toml
fuzzers/binary_only/qemu_coverage/Makefile.toml
fuzzers/binary_only/qemu_launcher/Makefile.toml
fuzzers/binary_only/tinyinst_simple/Makefile.toml
fuzzers/forkserver/forkserver_libafl_cc/Makefile.toml
fuzzers/forkserver/libafl-fuzz/Makefile.toml
fuzzers/fuzz_anything/baby_no_std/Makefile.toml
fuzzers/inprocess/dynamic_analysis/Makefile.toml
fuzzers/inprocess/fuzzbench/Makefile.toml
fuzzers/inprocess/fuzzbench_ctx/Makefile.toml
fuzzers/inprocess/fuzzbench_text/Makefile.toml
fuzzers/inprocess/libfuzzer_libmozjpeg/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_accounting/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_centralized/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_cmin/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_norestart/Makefile.toml
fuzzers/inprocess/libfuzzer_libpng_tcp_manager/Makefile.toml
fuzzers/inprocess/libfuzzer_windows_asan/Makefile.toml
fuzzers/structure_aware/nautilus_sync/Makefile.toml

Use `mapping` to deduce `PROFILE_DIR` variable from `PROFILE` if possible. makes it easier to switch from `release` to `dev` builds

better definition for PROFILE_DIR in all Makefile.toml files

---

libafl/src/mutators/multi.rs

If a multipart input is empty, crossover mutators make the program crash with a divide by zero exception:
<details><summary>Backtrace</summary>
```
thread 'main' panicked at /home/ubuntu/fuzzing-zephyr-network-stack/LibAFL/libafl/src/mutators/multi.rs:267:30:
attempt to calculate the remainder with a divisor of zero
stack backtrace:
0:     0x555f9cb4c7fa - std::backtrace_rs::backtrace::libunwind::trace::h99efb0985cae5d78
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
1:     0x555f9cb4c7fa - std::backtrace_rs::backtrace::trace_unsynchronized::he2c1aa63b3f7fad8
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2:     0x555f9cb4c7fa - …
```

Fixing Crossover Mutators for Empty Multipart Inputs

---

libafl_bolts/Cargo.toml
libafl_bolts/src/shmem.rs

memfd backed shmprovider. Tested on android with ForkserverExecutor but should be usable on other Linux flavors. Minor caveat: Android 7 and older as well as old linux kernel (AFAICT < 3.17) are unsupported.

Add memfd shmem backend

---

fuzzers/forkserver/libafl-fuzz/Cargo.toml
fuzzers/forkserver/libafl-fuzz/Makefile.toml
fuzzers/forkserver/libafl-fuzz/src/executor.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
fuzzers/forkserver/libafl-fuzz/src/main.rs
libafl_bolts/src/ownedref.rs
libafl_nyx/Cargo.toml
libafl_nyx/src/executor.rs
libafl_nyx/src/helper.rs

Let's see if the CI works. We need an intel CPU for nyx_mode

libafl-fuzz: introduce nyx_mode

---

fuzzers/baby/backtrace_baby_fuzzers/c_code_with_fork_executor/src/main.rs
fuzzers/baby/backtrace_baby_fuzzers/c_code_with_inprocess_executor/src/main.rs
fuzzers/binary_only/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/binary_only/qemu_cmin/src/fuzzer.rs
fuzzers/structure_aware/baby_fuzzer_multi/Cargo.toml
fuzzers/structure_aware/baby_fuzzer_multi/src/main.rs
libafl/src/observers/map/const_map.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/ownedref.rs

The `ConstMapObserver` wasn't really usable after #2592

Actually make ConstMapObserver work, introduce `nonnull_raw_mut` macro

---

fuzzers/binary_only/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/binary_only/fuzzbench_qemu/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
fuzzers/forkserver/fuzzbench_forkserver/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_cmplog/src/main.rs
fuzzers/inprocess/dynamic_analysis/src/lib.rs
fuzzers/inprocess/fuzzbench/src/lib.rs
fuzzers/inprocess/fuzzbench_ctx/src/lib.rs
fuzzers/inprocess/fuzzbench_text/src/lib.rs
libafl/src/mutators/mopt_mutator.rs

`I` is unused in `::new` and thus requires callers to explicitly specify any type as it can't be determined by type inference.
Clippy's `extra_unused_type_parameters` should pick this up, but is tuned a bit too conservative in order to avoid false positives AFAICT.
If the type parameter was deliberate in order to easily set the mutator's input type we could also add the missing type bound. Here, I'm letting type inference figure it out.. :shrug: 
Note: The CI failure seems like an unrelated flaky test.

`StdMOptMutator::new`: remove unused type parameter

---

fuzzers/forkserver/libafl-fuzz/Makefile.toml
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
libafl/src/observers/cmp.rs

I've also increased all the timeouts.

libafl-fuzz: fix cmplog running on inputs more than once

---

Cargo.toml
libafl/Cargo.toml
libafl_bolts/Cargo.toml
libafl_concolic/symcc_runtime/Cargo.toml
libafl_concolic/test/dump_constraints/Cargo.toml
libafl_frida/Cargo.toml
libafl_intelpt/Cargo.toml
libafl_nyx/Cargo.toml
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_sys/Cargo.toml
libafl_sugar/Cargo.toml
libafl_targets/Cargo.toml
libafl_tinyinst/Cargo.toml
utils/drcov_utils/Cargo.toml
utils/gramatron/construct_automata/Cargo.toml
utils/libafl_benches/Cargo.toml

improvements:
- no redundant `path`
- no redundant `version` (easier libafl version bumps I guess)
drawbacks:
- `default-features` must be explicitly enabled in packages if required
Just an idea, open for feedbacks

Libafl workspace internal deps in workspace Cargo.toml

---

libafl_bolts/src/shmem.rs

cater to platforms knowingly support this feature instead.

bolts: fix build for tiers 3 platforms.

---

libafl/src/stages/mod.rs
libafl/src/stages/tmin.rs
libafl/src/stages/tuneable.rs

The metadata is inserted as a named metadata. 
https://github.com/AFLplusplus/LibAFL/blob/b3d3c38b2900e45246ea8dd75648f25818226d74/libafl/src/stages/mod.rs#L693-L696
The `debug_assert!` will always fail since unnamed metadata and named metadata are stored in different fields in `StdState`
https://github.com/AFLplusplus/LibAFL/blob/b3d3c38b2900e45246ea8dd75648f25818226d74/libafl/src/state/mod.rs#L264-L267

Fix metadata removal for ExecutionCountRestartHelper

---

fuzzers/forkserver/libafl-fuzz/Cargo.toml
fuzzers/forkserver/libafl-fuzz/Makefile.toml
fuzzers/forkserver/libafl-fuzz/src/executor.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
fuzzers/forkserver/libafl-fuzz/src/main.rs

Only build nyx mode if `target_os = linux` and if the feature ``nyx`` is enabled

libafl-fuzz: feature-flag nyx mode

---

libafl/src/executors/forkserver.rs
libafl/src/stages/verify_timeouts.rs
libafl_bolts/src/serdeany.rs
scripts/clippy.ps1

Addresses some concerns we discussed about serdeany to ensure that it doesn't rely on features which aren't present downstream.

Fixup serdeany_autoreg

---

.github/workflows/build_and_test.yml
libafl/Cargo.toml
libafl_bolts/Cargo.toml
libafl_cc/Cargo.toml
libafl_derive/Cargo.toml
libafl_targets/Cargo.toml

Hi,
specifying `rust-version= ".."` in Cargo.toml is nice because it gives a descriptive error message when people try to use LibAFL on older Rust versions. I've added the MSRV for the core-ish `libafl` crates and added a check in CI that makes sure these are up-to-date.
Thanks!
Note: The CI failure is unrelated :upside_down_face:

Specify minimum supported Rust version and check in CI

---

libafl/src/executors/command.rs
libafl/src/executors/mod.rs
libafl/src/observers/stdio.rs

Make exit status interpretable by CommandConfigurator

---

libafl/src/inputs/multi.rs

If the name is empty, `OnDiskCorpus` etc. panic.

Fix Empty MultipartInput Name

---

libafl_frida/build.rs

Currently, there is a problem where, when linking frida-gum, glib cannot find certain symbols because libresolv is not linked properly. The error is below:
```
Undefined symbols for architecture arm64:
"_res_9_dn_expand", referenced from:
_OUTLINED_FUNCTION_16 in libfrida_gum_sys-a07f5e3f0fd74186.rlib(gthreadedresolver.c.o)
"_res_9_ndestroy", referenced from:
_do_lookup_records in libfrida_gum_sys-a07f5e3f0fd74186.rlib(gthreadedresolver.c.o)
"_res_9_ninit", referenced from:
_do_lookup_records in libfrida_gum_sys-a07f5e3f0fd74186.rlib(gthreadedresolver.c.o)
"_res_9_nquery", referenced from:
_do_lookup_records in libfrida_gum_sys-a07f5e3f0fd74186.rlib(gthreadedresolver.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see …
```

Link libresolv on all apple OSs

---

Cargo.toml
libafl/src/observers/cmp.rs
libafl_intelpt/src/lib.rs

Seeing if updating bitbybit helps

Maybe fix CI

---

Cargo.toml
libafl/src/observers/cmp.rs
libafl_intelpt/src/lib.rs

The `missing_docs` issue was introduced in 1.3.3
We can use 1.3.2 until [this](https://github.com/danlehmann/bitfield/issues/66) gets fixed
This PR reverts #2768

Revert #2768 fix bitbybit CI by locking bitbybit <1.3.3

---

libafl_cc/Cargo.toml
libafl_cc/src/cfg.rs
libafl_derive/Cargo.toml

This brings the MSRV in line with the other core crates (`libafl`, `libafl_bolts`), which (sadly) is outside of the "packaged Rust in distros" range (Ubuntu 24.04 is at `1.80`, 25.04 is at `1.81` :melting_face:).
With the upcoming 2024 edition we should also set `resolver = "3"` in the workspace's Cargo.toml at some point to opt into the new MSRV-aware dependency resolver. This would fix the breakage we encountered with dependencies that bump their MSRV in a minor version update.
CC #2754

libafl_{cc,derive}: Bump MSRV to 1.82 for `home` crate update

---

fuzzers/forkserver/forkserver_libafl_cc/src/main.rs
fuzzers/fuzz_anything/baby_no_std/src/main.rs
fuzzers/fuzz_anything/push_harness/src/main.rs
fuzzers/inprocess/libfuzzer_libpng_accounting/src/lib.rs
fuzzers/structure_aware/baby_fuzzer_gramatron/src/main.rs

Cleanup clippy warnings in example fuzzers

---

libafl/src/monitors/prometheus.rs

The aggregated and per-client fuzzing stats were mixed in the Prometheus monitor, either the ones displayed on stderr and the ones served. The metrics were structured to show stats for each client, with Prometheus labels using `sender_id.0` as an identifier. However, only the `custom_stats` were actually per-client, while the rest (e.g., exec/s, objective_count, etc.) were all aggregated. This created confusion.
I separated the metrics into two categories: global metrics and per-client metrics. Now, they are served separately. I also thought it would be nice and beautiful to display the parameter `edges_hit/edges_total`, so I dared to add it in the `custom_stats`.
I refactored a bit the monitor here and there.

Separate Prometheus metrics into global and per-client categories with refactoring

---

MIGRATION.md
fuzzers/structure_aware/baby_fuzzer_custom_input/src/input.rs
fuzzers/structure_aware/baby_fuzzer_custom_input/src/main.rs
libafl/src/inputs/bytes.rs
libafl/src/inputs/bytessub.rs
libafl/src/inputs/mod.rs
libafl/src/inputs/value.rs
libafl/src/mutators/havoc_mutations.rs
libafl/src/mutators/mapping.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/numeric.rs
libafl_bolts/src/lib.rs

Turns out implementing the required traits directly on the borrows is possible and much cleaner.
This also allows removing `MappedInput`, which caused significant headaches for mapping mutators.

Remove MutVecInput and MappedInput in Favour of Impls on References

---

libafl/src/fuzzer/mod.rs

When trying to use the `last_found_time` member of state, I found that it is only updated in the function `add_input`. 
In my case, I was using `fuzzer.fuzz_one` and add_input was never called during fuzzing.
This looks like a bug as the description of this field is `The last time we found something by ourselves`.  
In this fix I added 3 lines to update `last_found_time` when an interesting input is found in `evaluate_execution`.

Update last found time when evaluating an input

---

libafl/src/mutators/multi.rs

When `other` is empty, the mod calculation following the changed code throws a divided by 0 panic.

Fix Empty Multipart Crossover Bug

---

libafl/src/mutators/havoc_mutations.rs
libafl_bolts/src/shmem.rs
libafl_bolts/src/tuples.rs

Check out an initial application in `havoc_mutations.rs`.

Add macros to libafl_bolts tuples for mapping and merging types

---

libafl_cc/build.rs
libafl_cc/src/ar.rs

Previously, you needed to explicitly specify `LLVM_AR_PATH` as an environment variable.

libafl_cc: Automatically find llvm_ar path

---

libafl/src/corpus/inmemory_ondisk.rs

This is necessary if you want to disable locking for a corpus.

imemory_ondisk: Don't fail write under any circumstances if locking is disabled

---

fuzzers/binary_only/qemu_launcher/src/options.rs

Seems that `clap` has changed the way it parses arguments with multiple options. Now rather than...
```--include 0x1000-0x2000,0x3000-0x4000```
It expects...
```--include 0x1000-0x2000 --include 0x3000-0x4000```
The code needs to change accordingly.

Fix command line parsing of ranges in `qemu_launcher`

---

libafl/src/state/mod.rs

I have some non-multi-input files in my multi-input corpus - they don't serialize for obvious reasons.

Continue loading inputs even if some fail to deserialize

---

libafl_qemu/src/modules/usermode/snapshot.rs

It looks like my previous fix wasn't ideal and I was still getting SIGSEGVs during fuzzing run because of brk operations.
This time, to be sure 100%, I created [this](https://github.com/cube0x8/libafl_qemu_snapshot_test) fuzzer, which is a simple program that does things with brk, like increasing it or shrinking it below the snapshotted brk value. I used it to properly debug the snapshot feature behavior and then I let it run for almost 1 week. No more crashes came up, either with this fuzzer or with my other targets.

Fix snapshot reset function when brk shrunk below the snapshotted value

---

.github/workflows/build_and_test.yml

Use ubuntu-22.04 and restore the action instead of the script

CI check-md-links fix

---

libafl_targets/build.rs

`--undefined` flags must be passed to the linker instead of being given to the compiler. Some compilers are not aware of the `--undefined` flag.

Fix libafl_targets cmplog linking

---

.github/workflows/build_and_test.yml

because there's an ICE in cargo-fuzz

Don't fail fast for now

---

libafl/src/executors/forkserver.rs

The bound should no longer be necessary since the introduction of the TargetBytesConverter

Remove unnecessary HasTargetBytes constraint

---

libafl/src/inputs/bytes.rs
libafl/src/inputs/bytessub.rs
libafl/src/inputs/mod.rs
libafl/src/mutators/multi.rs
libafl/src/mutators/mutations.rs
libafl/src/mutators/token_mutations.rs
libafl/src/mutators/unicode/mod.rs
libafl/src/stages/colorization.rs
libafl/src/stages/generalization.rs
libafl_targets/src/libfuzzer/mutators.rs

(See #2853.)
This commit attempts to improve the [`HasMutatorBytes`] trait to allow it to
be used along with input types that cannot be resizable.
[`HasMutatorBytes`] is split into two traits:
- [`HasMutatorBytes`]: requires `bytes` and `bytes_mut`.
- `HasMutatorResizableBytes`: requires [`HasMutatorBytes`], and also requires
a few other methods for resizing / shrinking the underlying input type.
N.B.: I believe that if merged, this would introduce a breaking change.
[`HasMutatorBytes`]: https://github.com/AFLplusplus/LibAFL/blob/198cd5dbc5200bfba3df48cf2a14376e0f0e3000/libafl/src/inputs/bytes.rs#L26

Fix #2853: split `HasMutatorBytes` trait into two traits.

---

MIGRATION.md
fuzzers/baby/baby_fuzzer_minimizing/src/main.rs
libafl/src/observers/map/const_map.rs
libafl/src/observers/map/hitcount_map.rs
libafl/src/observers/map/mod.rs
libafl/src/observers/map/multi_map.rs
libafl/src/observers/map/owned_map.rs
libafl/src/observers/map/variable_map.rs
libafl/src/observers/value.rs
libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/colorization.rs
libafl/src/stages/mod.rs
libafl/src/stages/tmin.rs
libafl_targets/src/sancov_8bit.rs

This is useful if one wants to use a map-ish `Observer` for certain `Scheduler`s. I'm currently tracking a very sparse map (~0.01% of entries usually set), and memory consumption is eating me alive. But implementing `MapObserver` also means implementing functions that would need to allocate the entire `Vec` again, so not really feasible. Hence the separation into two traits where the scheduling algorithms only need `SimpleHash`.

Remove MapObserver dependency from observer-dependent stages and schedulers in favour of generic hashing

---

.vscode/settings.json.default

Reverts AFLplusplus/LibAFL#2864
-> I need tests to be rust analyzered

Revert "Set rust-analyzer.cargo.allTargets to False in setings.json.default"

---

fuzzers/binary_only/qemu_launcher/src/client.rs
fuzzers/binary_only/qemu_launcher/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs

1. Fixed the issue where compilation failed under the `simplemgr` features in `Cargo.toml`
2. Fixed the issue where the crash handler would fail during rerun. This issue was discovered with the guidance of @tokatoka , and its root cause is quite complex, as detailed in #2837.
(P.S. Currently, another issue potentially related to the `AsanModule` has been observed and may be further discussed in #2837.)

Qemu launcher bugfix

---

fuzzers/binary_only/qemu_cmin/Cargo.toml
fuzzers/binary_only/qemu_cmin/src/fuzzer.rs
fuzzers/binary_only/qemu_coverage/Cargo.toml
fuzzers/binary_only/qemu_coverage/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/Cargo.toml
fuzzers/binary_only/qemu_launcher/src/client.rs
fuzzers/binary_only/qemu_launcher/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/harness.rs

Log messages changed to `log::info` so they aren't compiled out of release builds. They are in non-performance critical portions of code.

Add support for env_logger for qemu binary only fuzzers

---

fuzzers/binary_only/qemu_coverage/README.md
fuzzers/binary_only/qemu_coverage/src/fuzzer.rs
libafl_qemu/src/modules/cmplog.rs
libafl_qemu/src/modules/drcov.rs
libafl_qemu/src/modules/edges/helpers.rs

move DrCov hook initialization to `first_exec` to avoid using the hook before it's actually possible.

Fix qemu cov

---

Cargo.toml
bindings/pylibafl/Cargo.toml
fuzzers/binary_only/qemu_coverage/Makefile.toml
fuzzers/binary_only/qemu_coverage/src/fuzzer.rs
libafl/src/lib.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/tuples.rs
libafl_cc/build.rs
libafl_concolic/symcc_runtime/src/lib.rs
libafl_concolic/symcc_runtime/src/tracing.rs
libafl_intelpt/src/lib.rs
libafl_libfuzzer/build.rs
libafl_qemu/build_linux.rs
libafl_qemu/src/arch/hexagon.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/modules/drcov.rs
libafl_qemu/src/modules/mod.rs
libafl_qemu/src/modules/usermode/injections.rs
libafl_qemu/src/modules/usermode/snapshot.rs
libafl_qemu/src/modules/utils/filters.rs
libafl_targets/src/drcov.rs
libafl_targets/src/lib.rs
libafl_targets/src/sancov_pcguard.rs
scripts/clippy.sh
utils/drcov_utils/Cargo.toml
utils/drcov_utils/src/bin/drcov_dump_addrs.rs
utils/drcov_utils/src/bin/drcov_merge.rs

also, apply suggestion in #2883 from @domenukk.

Fix drcov path parsing

---

libafl/src/monitors/mod.rs

Related to issue #2895. Now we can create multiple monitors for one fuzzer instance.
Currently, the API of Monitor is not good enough to implement a zero-cost combined monitor, the client stats need to be synced to underline monitors in the right time (I choose to sync before each display call), which incurs some runtime overhead.

Add combined monitor

---

libafl_bolts/src/rands/mod.rs

The implementation of [`Lehmer64Rand::next`] performs a mul on `u128`, which
is not checked against overflows. It leads to panic in debug mode.
[`Lehmer64Rand`]: https://github.com/AFLplusplus/LibAFL/blob/fd6271fa356f3addda6db33f37db7e42a2c99bbc/libafl_bolts/src/rands/mod.rs#L373-L376

Fix Lehmer64 implementation of `next`.

---

libafl/src/mutators/mod.rs

Useful for complex input types containing booleans in combination with `MappingMutator`s.

Introduce BoolMutator

---

libafl/src/events/broker_hooks/mod.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/tui/mod.rs

Follow up the discussion in #2900.
Previously, since both `client_stats_mut` and `client_stats_mut_for` of `Monitor` are broadly used, and those mothods could not give us a good knowledge of "when a client stat is modified", so we have to sync client stats everytime we call the `display`, which is a relatively large runtime overhead.
This PR changes the API: 
* remove the `client_stats_mut_for`, use `update_client_stats_for` instead
* make `client_stats_mut` internal usage only
* introduce `update_all_client_stats` to update all client stats at once
If you think this PR is acceptable, I'm willing to update the `MIGRATION.md` before finally merged.

Change Monitor API for more flexibility

---

bindings/pylibafl/pyproject.toml

According to `maturin`'s documentation: https://www.maturin.rs/config.html
`python-source` should point to the source directory containing python sources.
In `LibAFL` case, it does not exist. However, `maturin` will panic if that directory does not exist in development.
So better point to `src`.
For bindings, only `pyo3`, `Py_LIMITED_API/abi3`, `cffi`, `uniffi` options are available.
In `LibAFL` case, it should be `pyo3`.

Fix the python binding configuration

---

libafl/src/executors/hooks/unix.rs
libafl/src/executors/inprocess/mod.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/qemu/hooks.rs

For my use case, I have a custom executor that uses Qemu. A few unneeded restrictions on the current code base annoys me. I also added some documentation about the `QemuHooks` (the ones that I know enough). 
- Removed the unnecessary `Executor<EM, I, S, Z>` trait for a few handlers.
- Set `inproc_qemu_crash_handler` to public to be consistent with `inproc_qemu_timeout_handler` an allow to use it if needed (like in my case)
- Added documentation on instruction, edge, block, cpu_run and read / write hooks based on libafl-qemu paper and my understanding of the code.

Small improvements for Qemu

---

libafl/src/events/simple.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/disk_aggregate.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/prometheus.rs
libafl/src/monitors/tui/mod.rs
libafl/src/statistics/manager.rs
libafl_libfuzzer/runtime/src/fuzz.rs
libafl_libfuzzer/runtime/src/merge.rs

Follow up discussions in #2940. This will remove the barriers for removing `base`-patterns for `Monitor`s.
In this PR, `start_time` is moved from `Monitor` to `ClientStatsManager`. Since then, each `Monitor`s could be completely independent.

Move start_time to ClientStatsManager

---

libafl_qemu/src/modules/usermode/asan.rs
libafl_qemu/src/qemu/mod.rs

Since nightly clippy has added the rule [format_push_string](https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string). This fix is modified as suggested in that webpage.

Fix clippy

---

MIGRATION.md
fuzzers/inprocess/libfuzzer_libpng_launcher/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_norestart/src/lib.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/disk_aggregate.rs

Previously, `OnDiskTomlMonitor`, `OnDiskJsonMonitor`, `OnDiskJsonAggregateMonitor` take a base monitor for wrapping. However, after #2940 and #2948, monitors could be completely independent, and the wrap is no longer needed. As a result, the `base`-pattern can be safely removed. To use multiple monitors together, use `libafl::combine_monitor!` instead.

Remove base-pattern for Monitor

---

Cargo.toml
libafl_bolts/Cargo.toml
libafl_bolts/src/tuples.rs

Avoid dependence on std specialization. Fixes #2945.

Better type_eq

---

fuzzers/binary_only/fuzzbench_qemu/src/fuzzer.rs
libafl/src/executors/hooks/unix.rs
libafl/src/executors/hooks/windows.rs

So that it's easier to catch what's wrong when next time we have a bug in crash handler

Properly use in_handler

---

libafl/Cargo.toml
libafl/src/monitors/mod.rs
libafl/src/monitors/stats/manager.rs
libafl/src/monitors/stats/mod.rs
libafl/src/monitors/statsd.rs
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs

This PR adds a `StatsdMonitor`, which is roughly a counterpart of [AFL++'s rpc_statsd](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/rpc_statsd.md).
There are two more things could be done after this PR:
* Write sections in LibAFL book to tell about how to use statsd metrics in LibAFL (or we could even tell about all other monitors' usage in that section)
* As you could see in `libafl/src/monitors/statsd.rs`, there are several metrics currently not available, which is available in AFL++. Some of these metrics could be resolved in `AflStatsStage`. This stage involves much with the Monitor's statistics, so we should think more about this (and maybe some refactors to make this more maintainable). (In my first thought, shouldn't it be Monitor's responsibility to write to …

Add StatsD monitor

---

libafl_qemu/src/modules/usermode/asan.rs
libafl_qemu/src/modules/utils/addr2lines.rs
libafl_qemu/src/modules/utils/mod.rs

For now just separating the addr2line code, and also `pub`s so that I can access them from other modules.
Ideally I want also to separate the code from asan_report. but addr2line's API is not very ergonomic, and I gave up 😩

Separate addr2line code from asan module

---

fuzzers/full_system/unicorn/Justfile
fuzzers/full_system/unicorn/src/main.rs
libafl/src/events/launcher.rs
libafl_unicorn/src/emu.rs
libafl_unicorn/src/helper.rs

Some fixes for the unicorn emulation example
fix https://github.com/AFLplusplus/LibAFL/pull/2983#issuecomment-2661771753

Fix unicorn

---

libafl_qemu/runtime/libafl_qemu_arch.h

This PR fixes riscv target compilation that use qemu calls, by adding checks for riscv compiler macros (64 and 32).
Current issue: on riscv targets `libafl_word` and `LIBAFL_CALLING_CONVENTION` would not get defined.
Fixed: `libafl_word` and `LIBAFL_CALLING_CONVENTION` are defined for riscv targets

chore: adds check for riscv64 and riscv32 archs

---

.github/workflows/build_and_test.yml
fuzzers/inprocess/libfuzzer_libpng/Justfile
just/libafl-cc-libpng.just
just/libafl-cc.just
just/libafl-qemu-libpng.just
just/libafl.just
libafl_targets/src/forkserver.c

also did the migration to library-style justile.
next step is to migrate other libpng fuzzers

Fix build for libfuzzer_libpng in ubuntu 24

---

libafl/src/common/mod.rs
libafl/src/feedbacks/list.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/observers/map/mod.rs

In this PR. I added `add_metadata_checked` and `add_namedmetadata_checked`. 
This is for checking the metadata or named metadata is already existent and return error if so.
This way we can avoid bugs like when you use same mapmetadata for objectives and feedbacks such as this: https://github.com/AFLplusplus/LibAFL/pull/2983#discussion_r1957105585

Add `add_metadata_checked` method

---

scripts/test_fuzzer.sh

Calling test_fuzzer.sh without parameters will by default try to test all fuzzers. This will not work, as the working directory is changed in the first iteration from LibAFL to LibAFL/fuzzers/.
Solution is quite simple: Create a subshell with parentheses to keep same base working directory for every fuzzer in the list.
Run test_fuzzer.sh from LibAFL directory without parameters:
`/LibAFL# ./scripts/test_fuzzer.sh`
> [+] Done building ./fuzzers/inprocess
./scripts/test_fuzzer.sh: line 46: cd: ./fuzzers/fuzz_anything: No such file or directory
- [ x] I have run `./scripts/precommit.sh` and addressed all comments

scripts/test_fuzzer.sh: correct working directory

---

.github/workflows/build_and_test.yml

We don't have enough machines for these 2nd-tier architecures.

Remove aarch64, arm, i386, ppc tests from CI

---

libafl/src/executors/hooks/inprocess.rs
libafl/src/executors/hooks/inprocess_fork.rs
libafl_qemu/src/executor.rs

Revert #2935

---

libafl/src/feedbacks/map.rs

Fix https://github.com/AFLplusplus/LibAFL/issues/2006
Here instead of making this metadata named. I just make it forbidden to overwrite this metadata.
This means that users are responsible for setting the `tracking` correctly for the corresponding observers attached to each mapfeedback

Forbid overwriting MapIndexesMetadata

---

libafl_targets/build.rs

Adds accidentally-removed option for the libfuzzer_interceptors feature back into libafl_targets. Resolves #3043.
/cc @addisoncrump
/cc @ammaraskar

Add build option for FuzzerInterceptors

---

fuzzers/binary_only/frida_executable_libpng/src/fuzzer.rs
fuzzers/binary_only/frida_libpng/src/fuzzer.rs
fuzzers/binary_only/frida_windows_gdiplus/src/fuzzer.rs
fuzzers/binary_only/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/binary_only/fuzzbench_qemu/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
fuzzers/full_system/nyx_launcher/src/instance.rs
fuzzers/full_system/qemu_linux_kernel/src/fuzzer.rs
fuzzers/full_system/qemu_linux_process/src/fuzzer.rs
fuzzers/fuzz_anything/libafl_atheris/src/lib.rs
fuzzers/inprocess/fuzzbench/src/lib.rs
fuzzers/inprocess/fuzzbench_ctx/src/lib.rs
fuzzers/inprocess/fuzzbench_text/src/lib.rs
fuzzers/inprocess/libfuzzer_stb_image/src/main.rs
fuzzers/structure_aware/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
libafl/src/stages/mod.rs
libafl/src/stages/shadow.rs
libafl/src/stages/tracing.rs
libafl_libfuzzer/runtime/src/lib.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

First, separate ShadowTracingStage and TracingStage into different files
These two should be used at very different times.
Essentially in libafl it is not possible to have more than one inprocess executor or its childeren.
So i fixed the misuse of them in fuzzers/*

Fix usage of TracingStage

---

libafl/src/executors/forkserver.rs

We don't need to expose Forkserver as there is ForkserverExecutorBuilder to take care of proper forkserver initialization

Hide Forkserver::new() API

---

Dockerfile

A previous commit added git config `core.pager=cat` to the devcontainer, presumably because the pager bevahiour was sub-standard. A better solution is to install less.

Fix git pager (needs less, not cat, for expected behaviour).

---

libafl_libfuzzer/build.rs

This performs symbol renaming on Rust internal symbols for when we link a static (but differently sanitized) libafl_libfuzzer to our target. Follows changes from https://github.com/rust-lang/rust/pull/127173 without breaking compatibility for existing targets in older nightlies.
This needs testing on macOS, as I'm not sure if the macOS prefixing for these symbol names is the same.

Fixup libafl_libfuzzer with new nightly internal symbol mangling

---

fuzzers/binary_only/qemu_launcher/src/client.rs
fuzzers/binary_only/qemu_launcher/src/options.rs
libafl_qemu/librasan/Justfile
libafl_qemu/librasan/runner/src/fuzz.rs

Add support for command line arguments to filter addresses included in `asan` for both `qemu_launcher` and `librasan's` `runner`.

Add ASAN filter

---

libafl_targets/src/sancov_cmp.c
libafl_targets/src/windows_asan.rs

There is an issue with one of the macros for generating `__libafl_targets_value_profileX` calls, which resulted in all instances calling `__libafl_targets_value_profile1` - meaning that only 1 byte of the conditional check got passed through.
@ammaraskar: you said that you found the bug due to some unexpected results (not being able to break through magic numbers); any chance you can rerun your setup and see if this fixes it?
Also: not sure if the formatter setup has changed or what - let me know if you'd prefer I remove the whitespace changes from this PR and create a new one after. Only `libafl_targets/src/sancov_cmp.c:17` has changed semantically.

Proposed fix for #3094, issue with trace-cmp

---

fuzzers/binary_only/frida_libpng/Justfile
fuzzers/binary_only/frida_libpng/README.md
fuzzers/binary_only/frida_libpng/harness.cc

Added windows full build of libpng to Justfile. Enabled harness.cc for cl.exe. Updated README.
Harness changes are minimal and works compiling with clang or cl on windows as well including fuzzing with the harnesses that both compilers generated so should compile fine with clang on linux.

Enable building libpng on CI without using GUI

---

fuzzers/forkserver/libafl-fuzz/src/hooks.rs
libafl/src/corpus/minimizer.rs
libafl/src/events/broker_hooks/centralized.rs
libafl/src/events/broker_hooks/centralized_multi_machine.rs
libafl/src/events/broker_hooks/mod.rs
libafl/src/events/centralized.rs
libafl/src/events/events_hooks/mod.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/mod.rs
libafl/src/events/multi_machine.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/feedbacks/map.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/afl_stats.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/sync.rs
libafl/src/state/mod.rs

that way, every event has the most up to date info about the client sending the event.
it also avoids duplicating fields like `executions` in other events.
also, adds a `Heartbeat` event to make it clearer what the intent of the event is.
`EventWrapper` is a bad name, does someone have a better suggestion?
@wtdcode @domenukk @tokatoka
it's another follow up to #3115.

Send client stats with every event

---

libafl/src/corpus/inmemory_ondisk.rs
libafl/src/corpus/ondisk.rs
libafl/src/corpus/testcase.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/tmin.rs

Following #2582, this adds back the `executions` field to `Testcase` and fire an extra event to sync executions metrics, which solves two main issues:
- When a `Event::NewTestcase` is fired, the executions and speed metrics are stale and incorrect.
- Allow users to retrieve the executions of a `Testcase` for post analysis of corpus.
Although the first point can be fixed by fire another `Event::UpdateExecStats`, it is infeasible and not inconvenient to pair such update with new test cases and thus can't fix the second point.
Note that it doesn't add `executions` field to `Event::NewTestcase`.
- [ x ] I have run `./scripts/precommit.sh` and addressed all comments

Add back executions to Testcase

---

.github/workflows/build_and_test.yml
.github/workflows/qemu-fuzzer-tester-prepare/action.yml
.github/workflows/ubuntu-prepare/action.yml

- GH images come with baked-in software that doesn't come from apt, getting the apt version will just slow down CI since the baked in version will be used anyway.
- Move ARM build chains as suggested by @tokatoka 
- Do not uninstall installed Clang, just set the desired one as default (is quicker)

CI: try to speedup by avoiding unnecessary installs

---

fuzzers/inprocess/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng/src/lib.rs
fuzzers/structure_aware/baby_fuzzer_multi/Cargo.lock
fuzzers/structure_aware/baby_fuzzer_multi/src/main.rs
libafl/Cargo.toml
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/simd.rs
libafl_bolts/Cargo.toml
libafl_bolts/examples/simd/simd.rs
libafl_bolts/src/simd.rs

As title. This PR does:
- Rename `stable_simd` to `simd`
- No longer rely on `nightly` for `std::simd` since `wide` is slightly faster and stable
- Support SIMD for `MaxReducer`, `OrReducer`, `AndReducer`, `MinReducer`
- Move `Reducer` to `libafl_bolts` to live with`SimdReducer`
- Benchmarked these SIMD operations and choose defaults for them
- Generalized SIMD vector support.

Default to use SIMD acceleration map feedbacks

---

fuzzers/full_system/qemu_linux_process/Justfile

Fix a typo in the Justfile of qemu_linux_process, which impedes the execution of `just run`

fix typo in qemu_linux_process

---

libafl_qemu/src/arch/arm.rs
libafl_qemu/src/qemu/usermode.rs
libafl_targets/src/libfuzzer/mutators.rs

When compiling the python bindings with `CPU_TARGET=arm maturin develop` I got an error because of a type mismatch in `py_syscall_hook_wrapper` (`libafl_qemu/src/qemu/usermode.rs`) and some unused functions in `libafl_qemu/src/arch/arm.rs`.
This fixes those issues.
I ran `./scripts/precommit.sh` but compilation for libafl_nyx failed so it only partially applied.

Fix python bindings

---

libafl_qemu/libafl_qemu_build/src/bindings.rs

This PR removes two lines from `libafl_qemu_build/src/bindings.rs` that define the existence of libclang headers `avx512vlfp16intrin.h` and `avx512fp16intrin.h`.
This used to be a workaround for bindgen not working well with specific types defined in Clang's `mmintrin.h`, see https://github.com/rust-lang/rust-bindgen/issues/2500#issuecomment-1640545912.
This seems to have been resolved in https://github.com/rust-lang/rust-bindgen/pull/2667, pushed to bindgen `v0.69.3`, rendering the workaround unnecessary.
With the old workaround, I was not able to compile libafl_qemu on clang-19 and later. See the build error below.
I tested this PR, and libafl_qemu compiles properly with clang-13, clang-15, and clang-19 to clang-21.
<details>
<summary>Clang 21 error message</summary>
```
--- stderr …
```

Remove bindgen float16 workaround

---

libafl_qemu/librasan/asan/src/maps/libc.rs
libafl_qemu/librasan/asan/src/mmap/libc.rs

The `errno` C macro should point to `__errno_location` on Linux.
http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib---errno-location.html

librasan: Fix errno_location function name

---

Cargo.toml

Reverts AFLplusplus/LibAFL#3184
this is clearly not mergeable as it is, it breaks the whole ci.

Revert "Update hashbrown requirement from 0.14.5 to 0.15.3"

---

libafl_qemu/librasan/asan/src/patch/raw.rs
libafl_qemu/librasan/asan/tests/patch_raw.rs

ARMv7 has two instruction sets: Thumb2 and ARM. ARM CPUs switch to Thumb state when they jump to a target address if the least significant bit of the address is set to 1. While `libc` can be compiled with ARM or Thumb instructions entirely, mixed instruction sets are also possible. This can happen when `libc` is compiled for ARM but has some handwritten Thumb assembly implementations for certain functions for performance reasons.
The following command shows a `libc.so.6` where two symbols have an address with the least significant bit set to 1.
```
$ readelf --syms --wide libc.so.6 | awk '$2~/.*[13579bde]$/'
Symbol table '.dynsym' contains 2208 entries:
Num:    Value  Size Type    Bind   Vis      Ndx Name
523: 0007bb21   156 FUNC    GLOBAL DEFAULT   12 memchr@@GLIBC_2.4
769: 0007a641 …
```

librasan: Support patching Thumb functions

---

libafl/src/mutators/nautilus.rs

The implementation of NautilusSpliceMutator does not need S: HasCorpus<NautilusInput> at all.
Clippy complains at somewhere I did not modify.

Remove unnecessary trait bounds in NautilusSpliceMutator

---

CONTRIBUTING.md

Basically it's only mentioned in the PR template, but would be nice to have it earlier, since there are ways to avoid the template when creating a PR.
- [*] I have run `./scripts/precommit.sh` and addressed all comments

Add a mention of precommit.sh to CONTRIBUTING.md

---

libafl/Cargo.toml
libafl/src/common/nautilus/grammartec/context.rs
libafl/src/common/nautilus/grammartec/mod.rs
libafl/src/common/nautilus/grammartec/rule.rs
libafl/src/common/nautilus/grammartec/tree.rs
libafl/src/generators/nautilus.rs

This allow users get rid of the python dependency if they don't need python scripts for nautilus grammar.

Split nautilus Python dependencies into separate feature

---

libafl_targets/src/coverage.c

#3183 removes a weak symbol `__afl_sharedmem_fuzzing`, which is only defined in `afl-cc`. Add it back for other modes that use forkserver.

Add weak symbol for forkserver

---

fuzzers/forkserver/fuzzbench_forkserver/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_cmplog/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_sand/src/main.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
libafl/src/executors/forkserver.rs
libafl_targets/src/forkserver.rs

Previously we already have methods to map `__AFL_SHM_ID` and `__AFL_SHM_FUZZZ_ID`. Now add the method to map `__AFL_CMPLOG_SHM_ID`.

Add cmplog shared memory mapping method for forkserver

---

libafl_qemu/librasan/asan/Cargo.toml
libafl_qemu/librasan/asan/src/allocator/frontend/default.rs
libafl_qemu/librasan/asan/src/patch/mod.rs
libafl_qemu/librasan/asan/src/tracking/guest_fast.rs
libafl_qemu/librasan/asan/src/tracking/mod.rs
libafl_qemu/librasan/gasan/src/lib.rs
libafl_qemu/librasan/zasan/src/lib.rs

Replace `BTreeMap` and `BTreeSet` with `hashbrown` data types.

Optimize data structures used by librasan

---

libafl_qemu/libafl_qemu_build/src/build.rs
libafl_qemu/libafl_qemu_build/src/lib.rs

Allow the URL and REVISION for QEMU to be overriden using environment variables.

Allow QEMU location and version to be specified in environment

---

libafl_cc/src/no-link-rt.c
libafl_targets/Cargo.toml
libafl_targets/src/cmplog.c
libafl_targets/src/cmplog.h
libafl_targets/src/cmps/mod.rs
libafl_targets/src/forkserver.rs

This uses `cmplog_instructions_extended_checked` for the correct headers to communicate with AFL++.
cc @Evian-Zhang

Expose AFL++ style extended cmplog for unicornafl

---

libafl/src/fuzzer/mod.rs
libafl/src/inputs/mod.rs

I use `NopFuzzer` to drive `ForkserverExecutor`, which doesn't really need anything from the fuzzer itself, except the trivial input converter.

Implement `HasBytesConverter` for `NopFuzzer`

---

libafl_bolts/src/fs.rs

From `Arc::try_unwrap`:
```
Returns the inner value, if the Arc has exactly one strong reference.
Otherwise, [None](https://doc.rust-lang.org/std/option/enum.Option.html#variant.None) is returned and the Arc is dropped.
This will succeed even if there are outstanding weak references.
If Arc::into_inner is called on every clone of this Arc, it is guaranteed that exactly one of the calls returns the inner value. This means in particular that the inner value is not dropped.
```
This exactly serves the original purpose. Using `Arc` here means I'm making a `Forkserver` to `Send`, as part of efforts to make the whole `ForkserverExecutor` to be `Send`. This is important so that we can spin up all fork servers and send them to standalone threads. Otherwise, we have to spin up threads first and …

Use `Arc<()>` to ref-counting `InpuFile` 

---

libafl_intelpt/src/linux.rs

Use is_multiple_of instead of % == 0
*I was reading the changelog of 1.87 and noticed that it's stable now.
Realised that I saw a todo in the code :)
https://releases.rs/docs/1.87.0/
- [*] I have run `./scripts/precommit.sh` and addressed all comments

Use is_multiple_of instead of % == 0

---

libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/mod.rs

As title, this PR allows `ForkserverExecutorBuilder` to accept an optional `CoreId` so that it can bind forkserver (and children) to a specific core. This is particularly useful for differential fuzzing where parallel forkservers are executed at the same time.

Support binding to a single core for `ForkserverExecutor`

---

fuzzers/forkserver/fuzzbench_forkserver_sand/src/main.rs
libafl/src/executors/forkserver.rs

Following https://github.com/AFLplusplus/AFLplusplus/pull/2421, this PR adds support for `AFL_LLVM/GCC_ONLY_FSRV` so that the normal sanitizer-enabled and pc instrumented binaries (built without `AFL_LLVM/GCC_ONLY_FSRV`) [can be used with `SandExecutor`](https://github.com/AFLplusplus/AFLplusplus/pull/2421/files#diff-ab30967d7af99ca9228e908b516bfe8778681594c6b37360605f020daad07719R51).  Another potential usage is executing cmplog binaries in this mode and that support will be added to LibAFL once I get it working with AFL++.
There is no need to patch `libafl_targets` since it is trivial to implement this on forkserver side, e.g. just skip the call to `map_shared_memory` or so.

Add support for `AFL_LLVM/GCC_ONLY_FSRV`

---

.github/workflows/build_and_test.yml
Dockerfile
libafl/Cargo.toml
libafl/src/executors/forkserver.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/os/pipes.rs
libafl_bolts/src/shmem.rs
libafl_cc/Cargo.toml
libafl_concolic/test/runtime_test/Cargo.toml
libafl_derive/Cargo.toml
libafl_libfuzzer/Cargo.toml
libafl_qemu/librasan/Cargo.toml
libafl_targets/Cargo.toml

Regarding `Shm`, it is safe because we take the ownership of the inner map pointer. Only potential violation is deref the underlying pointer but that’s already unsafe. Therefore, the properties of Send still hold within the safe world.
In addition, in most use cases, one fsrv holds one `Shm` and thus there should be almost no shared access.
As illustrated in #3240, the motivation is to make `ForkserverExecutor` to be `Send`. Without this, we have to spin up threads firstly and build `ForkserverExecutor` which further forks. It is already a known bad practice to mix multi threads and fork.
This PR also bumps to 1.87 and re-implement `libafl_bolts::os::Pipe` for `Send`.

Let`ForkserverExecutor` being `Send`

---

libafl/src/executors/forkserver.rs

Trivial patch.
The logs here seem useless and always triggered:
- If we do not pass in the coverage size to the builder, we return an error before printing it.
- If we pass in the coverage size to the builder, it logs anyway and we immediately overwrite the size.
- If we set `AFL_MAP_SIZE` environment variable, the builder won't take it from the environment variable.
Therefore, the check on the env seems useless and the log is not necessary at all.

Remove spurious logs

---

fuzzers/binary_only/python_qemu/fuzzer.py
libafl_qemu/src/emu/builder.rs
libafl_qemu/src/emu/mod.rs
libafl_sugar/src/qemu.rs

Linked to #3260 , I wanted to bring back passing a Qemu object to the QemuBytesCoverageSugar::run function of the python bindings. 
To (attempt to) avoid breaking anything I created a new functionQemuBytesCoverageSugar::run_with_qemu 
It introduces a `QemuSugarParameter` enum (the name is not great) to differentiate between cli argument and already running Qemu instance. In a way it brings back the `QemuBuilder` enum which was removed in #2707 
Note: It failed at building libafl_nyx

Allow passing Qemu object to QemuBytesCoverageSugar

---

libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs
libafl_bolts/src/target_args.rs

As title, this allows `InputLocation::Stdin` to have a filename specified instead of using the auto-generated ones.

Allow `InputLocation::Stdin` to specify a file name

---

libafl_bolts/Cargo.toml

`wide` seems not so active and let's release one for us temporarily.
https://crates.io/crates/libafl_wide

use `libafl_wide`

---

libafl/Cargo.toml
libafl_targets/src/cmplog.c
libafl_targets/src/cmplog.h
libafl_targets/src/cmps/mod.rs
libafl_targets/src/sancov_cmp.rs

Previously, we have exported:
* Cmplog for instructions
* Extended Cmplog for instructions
* Cmplog for routines
* Cmplog for routines with len (but exported in sancov_cmp.rs)
Now we can make it more consistent for others to use:
* Cmplog for instructions
* Extended Cmplog for instructions
* Cmplog for routines
* Cmplog for routines with len
* Extended cmplog for routines
* Extended cmplog for routines with len
BTW, [this TODO](https://github.com/AFLplusplus/LibAFL/blob/00e494b31f1577c918c79ca3e205e16136a185a8/libafl_targets/src/cmplog.h#L185) seems to be made in [this commit](https://github.com/AFLplusplus/LibAFL/commit/75fcd470443a2bcd540f9c1be2f2ae1240a3707b). In AFL++, it seems to be `len - 1` ([this code](https://github.com/AFLplusplus/AFLplusplus/blob/16cc444ae576da9c8c7ef45f55984507 …

Make cmplog exported functions more consistent

---

libafl_sugar/src/forkserver.rs
libafl_sugar/src/inprocess.rs

The `ForkserverBytesCoverageSugar` panic in the calibration stage when retrieving the map state (https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/stages/calibrate.rs#L218). Changing to a non named map fixes the issue
CC @domenukk

fix ForkserverBytesCoverageSugar

---

crates/libafl/src/corpus/inmemory_ondisk.rs

I'm not entirely sure what the purpose of the lockfiles is but I ran into the following crash with my fuzzer:
```
called `Result::unwrap()` on an `Err` value: Unknown("Failed to parse Int: ParseIntError { kind: InvalidDigit }",    0: <libafl_bolts::Error as core::convert::From<core::num::error::ParseIntError>>::from
1: libafl::corpus::inmemory_ondisk::InMemoryOnDiskCorpus<I>::save_testcase
2: <libafl::corpus::inmemory_ondisk::InMemoryOnDiskCorpus<I> as libafl::corpus::Corpus<I>>::add
3: <libafl::fuzzer::StdFuzzer<CS,F,IF,OF> as libafl::fuzzer::ExecutionProcessor<EM,I,OT,S>>::evaluate_execution
4: <libafl::fuzzer::StdFuzzer<CS,F,IF,OF> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_one
```
After looking at how data is written to and read from the lockfile, it appears to expect an integer as …

libafl: fix lockfile ctr serialization

---

.gitignore

`git` lists `crates/libafl_nyx/QEMU-Nyx` and `crates/libafl_nyx/packer` as untracked files after `libafl_nyx` is moved to `crates`. This PR updates `.gitignore` to fix the above problem.

Ignore downloaded Nyx folders

---

crates/libafl_intelpt/README.md
crates/libafl_intelpt/src/lib.rs
crates/libafl_intelpt/src/linux.rs

intel PT: check for availability in VMX
Check a CPU MSR to ensure that the CPU supports PT tracing in VMs

intel PT: check for availability in VMX

---

.github/workflows/build_and_test.yml

Upstream issue https://github.com/UmbrellaDocs/action-linkspector/issues/32 has been fixed.
- No.

Update check-md-links workflow to latest ubuntu

---

crates/libafl_targets/build.rs

65_536 bytes is 64 * 1024 is 64 kibibytes, not 65 KiB :)
`const TWO_MB: usize = 2_621_440;`
is sus as well, because 2 mibibytes should be 2 * 1024 * 1024 = 2097152, but I was afraid to change this value.
2_621_440 is actually 2.5 MiB.
- No.

nit: 65_536 bytes are 64 kibibytes

---

fuzzers/fuzz_anything/baby_no_std/Cargo.lock
fuzzers/fuzz_anything/baby_no_std/rust-toolchain
fuzzers/fuzz_anything/baby_no_std/rust-toolchain.toml

Fixes https://github.com/AFLplusplus/LibAFL/security/dependabot/11

Move rust-toolchain file to toml

---

crates/libafl_targets/build.rs

Like #3333, 2_621_440 bytes is 2.5 * 1024 * 1024 = 2.5 MiB.

2_621_440 bytes are 2.5 MiB

---

crates/libafl_qemu/runtime/nyx_api.h
crates/libafl_qemu/src/qemu/systemmode.rs

libafl_qemu tries to generate nyx bindings even if nyx is not going to be used.  On ARM, this results in a compile error during bindgen because kAFL_hypercall, which is defined inside an #ifdef on x86 platforms, is not defined and is later referenced in the same header file.
This commit adds an #else clause that creates a dummy definition of kAFL_hypercall on non-x86 platforms.  Additionally, a pointer cast is added because the signedness of `libafl_qemu_sys#libafl_qemu_sys`'s last argument appears to be unstable.

Fix libafl_qemu build on ARM

---

crates/libafl_libfuzzer_runtime/build.ps1
crates/libafl_libfuzzer_runtime/build.rs
crates/libafl_libfuzzer_runtime/build.sh

Adds options for profile, toolchain, rust args, cargo args, and c compiler in libafl-libfuzzer build scripts. This allows scenarios where e.g. you want to build std with some
unstable options. For example, to work with CFG you can build like `.\build.ps1 -Toolchain nightly -RustcArgs "-Zunstable-options -Zehcont-guard" -CargoArgs "-Zbuild-std" -CCFlags "/guard:ehcont"`.

Update libafl-libfuzzer build scripts with more options

---

crates/libafl/src/corpus/dynamic.rs
crates/libafl/src/corpus/mod.rs

A follow up of #3124 like `DynamicStage`. No idea why it was missing then.
The typical use case of this type is debugging. To be specific, when I'm developing fuzzers, I will save seeds or so to disks via `InMemoryOnDiskCorpus` while I will use `InMemoryCorpus` for production, writing nothing to disks so that it is easy to be orchestrated.

Add `DynamicCorpus`

---

crates/libafl_targets/src/cmplog.c

In `__libafl_targets_cmplog_routines_len` and
`__libafl_targets_cmplog_routines_extended_len`, `area_is_valid` was called with `CMPLOG_RTN_LEN` as length instead of the length passed as argument.
In ASAN instrumented builds, this leads to an early exit since ASAN would detect the region as poisoned anytime the argument's actual length is less than `CMPLOG_RTN_LEN`.
Fix this issue by passing the len argument instead of `CMPLOG_RTN_LEN`.

Fix cmplog collection in ASAN builds

---

crates/libafl/src/feedbacks/list.rs

This PR will create a modified ListFeedback that expects a ListObserver<u64>, e.g., containing addresses, and dump
any newly observed addresses to a file that is specified by `path` when creating ListDumpFeedback. This can be useful
to get live coverage for other tools. 
- [x ] I have run `./scripts/precommit.sh` and addressed all comments
(at least for my changes)

ListDumpFeedback: Add modified ListFeedback that will dump newly observed addresses

---

just/libafl-cc-libpng.just

As mentioned  in #3152, examples are broken on the latest macOS, due to a conflict in fopen definitions. Seems like libpng fixed that upstream, so updating works. 
But with the latest llvm there is a problem with feenableexcept, but I just disabled it since it's only used in building libpng's libtest (which is not used in fuzzing).
- [*] I have run `./scripts/precommit.sh` and addressed all comments

Fix libfuzzer_libpng examples on macOS

---

Cargo.lock
crates/libafl_bolts/src/tuples.rs

With handles, it was previously possible to retrieve a single element from a tuple_list. This PR introduces functions to retrieve tuples of elements based on tuples of handles.

Introduce get_all and get_all_mut on tuple_list using handles
