AFLplusplus/LibAFL

docs/src/design/core_concepts.md
docs/src/getting_started/build.md
docs/src/getting_started/crates.md
docs/src/introduction.md

I fixed a couple typos I spotted while reading the book

fixed some minor typos in the book

---

fuzzers/baby_fuzzer/src/main.rs
fuzzers/frida_libpng/src/fuzzer.rs
fuzzers/libfuzzer_libmozjpeg/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_reachability/src/lib.rs
fuzzers/libfuzzer_stb_image/src/main.rs
libafl/Cargo.toml
libafl/build.rs
libafl/src/bolts/tuples.rs
libafl/src/events/mod.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/lib.rs
libafl/src/observers/map.rs
libafl/src/observers/mod.rs
libafl_frida/src/asan_rt.rs

Now Observers are not anymore 'static

Observers lifetime

---

.github/FUNDING.yml
TODO.md
libafl/Cargo.toml
libafl_cc/Cargo.toml
libafl_derive/Cargo.toml
libafl_frida/Cargo.toml
libafl_targets/Cargo.toml

+ baby_fuzzer book chapter
+ LLMP TCP multi-machine
+ Conditional composition of Feedbacks
+ Allow lifetime in Observers
+ Reachability example and Feedback

Version 0.2.0

---

fuzzers/frida_libpng/README.md

I ran into trouble when attempting to cross-compile for Android, so I upated the README with the steps that helped me.

update frida_libpng README for cross-compiling to android

---

libafl/src/state/mod.rs

This removes the restriction on BytesInput which was unnecessary

Make load_initial_inputs work for arbitrary inputs

---

libafl/src/executors/forkserver.rs

rlim_t is signed in this platform.

FreeBSD build fix proposal.

---

fuzzers/forkserver_simple/src/main.rs
libafl/src/executors/forkserver.rs

#136 
the fuzzer example now uses TimeoutForkserverExecutor

Forkserver_simple uses TimeoutforkserverExecutor

---

libafl/src/feedbacks/mod.rs

I made `FeedbackTuple` generic by taking a `FeedbackLogic` which contains the actual logical implementation.
Now any feedback "group" can be defined generically like-so:
```rust
pub type AndFeedback<A,B,I,S>     = FeedbackTuple<A, B, I, S, LogicAnd>;
pub type EagerOrFeedback<A,B,I,S> = FeedbackTuple<A, B, I, S, LogicEagerOr>;
pub type FastOrFeedback<A,B,I,S>  = FeedbackTuple<A, B, I, S, LogicFastOr>;
```
Let me know what you think

Eager and Fast FeedbackTuple Implementations

---

libafl/Cargo.toml
libafl/src/bolts/compress.rs
libafl/src/lib.rs

This should fix #167 
I decided to use another library for GZip compression/decompression

compression fix

---

libafl/src/stats/mod.rs

The rationale behind this change is that I would like to plot this data by consuming it in a custom Stats implementation.

Expose some details about introspection

---

libafl_cc/build.rs
libafl_cc/src/clang.rs
libafl_targets/src/common.h
libafl_targets/src/libfuzzer_compatibility.c

This sholud fix the linker issues on MacOS.
LLVM Passes are (still) broken

MacOS Build

---

.github/workflows/build_and_test.yml
libafl/src/events/llmp.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs

After the feedback in #196, this PR moves the `mgr_id` to its own trait to make it easier to use

Mgr ID improvements

---

.github/workflows/build_and_test.yml
.gitignore
libafl/src/events/llmp.rs

Let's see if this can increase build speeds

Github Actions Cache

---

.github/workflows/build_and_test.yml
fuzzers/forkserver_simple/src/main.rs
scripts/dummy.rs

This PR tries to increase Github Actions Build times through caching

Cache Rust in CI

---

libafl/src/bolts/llmp.rs
libafl/src/events/mod.rs

This PR introduces a `panic` in clients (which will be then be forwarded and morrored by the broker) when the broker is too slow to process incoming messages - to avoid OOM. There is usually a misconception about the use of LLMP in this case, and the fuzzer needs to be changed.

Panic on Too Slow Broker

---

libafl/src/bolts/staterestore.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/stages/power.rs
libafl_frida/src/lib.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/hooks.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

fix ci for latest clippy version

---

libafl_frida/src/asan_rt.rs
libafl_frida/src/helper.rs

also, poison target bytes after run.

strdup is an allocating function, treat it as such

---

fuzzers/libfuzzer_stb_image_concolic/runtime/Cargo.toml
libafl/src/executors/command.rs
libafl/src/observers/concolic/mod.rs
libafl/src/observers/concolic/serialization_format.rs
libafl/src/stages/concolic.rs
libafl_concolic/symcc_runtime/Cargo.toml
libafl_concolic/symcc_runtime/src/filter.rs
libafl_concolic/symcc_runtime/src/filter/coverage.rs
libafl_concolic/symcc_runtime/src/lib.rs
libafl_concolic/symcc_runtime/src/tracing.rs
libafl_concolic/test/README.md
libafl_concolic/test/dump_constraints/Cargo.toml
libafl_concolic/test/dump_constraints/src/main.rs
libafl_concolic/test/expected_constraints.txt
libafl_concolic/test/runtime_test/Cargo.toml
libafl_concolic/test/runtime_test/src/lib.rs

~~fair warning: I'll most likely want to force push to this branch once #160 is merged to rebase on main.~~
This PR contains a bunch of additional documentation, tests and small refactors (removing unused code and renames).

Documentation and Refactors for Concolic

---

libafl_concolic/symcc_runtime/src/lib.rs
libafl_concolic/test/runtime_test/src/lib.rs

fix warnings in concolic code

---

fuzzers/baby_fuzzer/src/main.rs
libafl/Cargo.toml
libafl/build.rs
libafl/src/bolts/os/windows_exceptions.rs
libafl/src/bolts/shmem.rs
libafl/src/executors/inprocess.rs

#184 
(and a slight change in baby_fuzzer/main.rs to crash it on win10)
Windows-rs update 0.4 => 0.18
Tested with baby_fuzzer

Windows dependency update

---

libafl/src/bolts/cpu.rs

Minor docs link fix; docs won't build currently.

bolts::cpu: fix docs link

---

fuzzers/forkserver_simple/src/main.rs
libafl/src/bolts/shmem.rs
libafl/src/executors/forkserver.rs
libafl_tests/build.rs
libafl_tests/src/forkserver_test.c

Improve the forkserver executor by giving the forkserver inputs via memory, not harddisk.

Forkserver Shared Memory Testcase

---

docs/src/SUMMARY.md
docs/src/advanced_features/advanced_features.md
docs/src/advanced_features/concolic/concolic.md

initial book entry for concolic

---

libafl/src/stages/power.rs

Closes #291 
I guess this will fix the issue.

PowerSchedule::COE fix

---

docs/src/SUMMARY.md
docs/src/advanced_features/no_std/no_std.md

WIP: added unfinished no_std docs

---

.github/workflows/build_and_test.yml
fuzzers/libfuzzer_stb_image/src/main.rs
fuzzers/push_harness/Cargo.toml
libafl/Cargo.toml
libafl/src/bolts/launcher.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/os/windows_exceptions.rs
libafl/src/executors/command.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/mod.rs
libafl/src/executors/timeout.rs
libafl_cc/src/clang.rs
libafl_frida/Cargo.toml
libafl_qemu/src/emu.rs
scripts/clippy.ps1

This PR works on fixing CI in `main`

Still fixing CI

---

libafl/src/bolts/launcher.rs

Reported by expy on discord.
we are spawning cores^2 with the current code

Fix the number of clients spawned

---

fuzzers/frida_libpng/README.md

Just a small README improvement

Minor readme improvement in frida_libpng fuzzer.

---

fuzzers/frida_libpng/README.md

Screwed up numbering in prev commit

---

libafl_frida/src/helper.rs

I forgot some cfgs needed to build frida on windows

Fix cfgs for frida asan

---

libafl/Cargo.toml
libafl/benches/hash_speeds.rs

There's not really any reason to spend more time compiling.

remove unused const hashing mode

---

libafl_frida/src/cmplog_rt.rs
libafl_frida/src/helper.rs

add support for special cases(cbz/cbnz/tbz/tbnz/subs)

Cmplog instrumentation

---

libafl_frida/src/asan_rt.rs

The `libc++` shared object can have many different names, and frida doesn't always do a good job of finding the correct functions to hook. This PR makes sure that the necessary functions are hooked.

frida-asan: Support different names for the libc++ shared object when hooking

---

libafl_frida/src/asan_rt.rs

This PR adds the ability to suppress calls to hooked versions of standard c functions when using frida-asan/cmplog. It works just like regular instrumentation suppression (using `instrument-suppress-locations`).
This allows one to ignore a specific function call which is a false-positive/not-interesting while fuzzing.

Support suppression of hooked functions

---

fuzzers/libfuzzer_reachability/README.md
fuzzers/libfuzzer_reachability/src/bin/libafl_cc.rs
fuzzers/libfuzzer_reachability/weak.c

This is something left undone back in july.
https://github.com/AFLplusplus/LibAFL/pull/187#issuecomment-872900701

Reachability fuzzer fix

---

libafl_qemu/src/asan.rs
libafl_qemu/src/cmplog.rs
libafl_qemu/src/edges.rs
libafl_qemu/src/emu.rs

Clippy fixes for main

---

fuzzers/fuzzbench_qemu/src/fuzzer.rs
libafl_qemu/build.rs
libafl_qemu/src/aarch64.rs
libafl_qemu/src/arm.rs
libafl_qemu/src/asan-giovese.c
libafl_qemu/src/asan.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/i386.rs
libafl_qemu/src/lib.rs
libafl_qemu/src/snapshot.rs
libafl_qemu/src/x86_64.rs

Now we can access common regs without caring about the arch, like Regs::Sp

libafl_qemu cpu_target cfg

---

libafl/src/events/llmp.rs
libafl/src/events/simple.rs

from the discussion on discord.

Delete "We're a client, let's fuzz :)" from lib

---

fuzzers/frida_libpng/README.md

delete msys2 readme to build it, (I don't think it's a good way to build it on win with msys2, users have to switch between powershell and msys2 shell a lot)
and mention libc++ dependency.

Frida_libpng document change

---

docs/src/core_concepts/forkserver_and_inprocessforkserver.md

More detailed forkserver document for the book

forkserver docus

---

fuzzers/forkserver_simple/src/main.rs

I forgot arguments for forksever

Forkserver Example Fix

---

.gitmodules

This changes the symcc submodule to actually work

Symcc submodule referencing a path

---

fuzzers/fuzzbench/src/lib.rs
fuzzers/fuzzbench_gsoc/src/lib.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs

3 Fuzzbench examples also uses this api

Fix Clap about() issue

---

libafl_frida/src/drcov_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/lib.rs

This pr moves drcov code from helper.rs into a runtime.

DrCov Runtime

---

libafl/src/events/llmp.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/monitors/mod.rs

This pr makes statbility into an Userstats
Closes #409

Use UserStats for Stability

---

fuzzers/fuzzbench/src/bin/libafl_cc.rs
fuzzers/generic_inmemory/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libmozjpeg/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_ctx/src/bin/libafl_cc.rs
fuzzers/libfuzzer_libpng_launcher/src/bin/libafl_cc.rs
fuzzers/libfuzzer_reachability/src/bin/libafl_cc.rs
fuzzers/tutorial/src/bin/libafl_cc.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/os/unix_shmem_server.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/bolts/serdeany.rs
libafl/src/bolts/shmem.rs
libafl/src/bolts/tuples.rs
libafl/src/events/llmp.rs
libafl/src/events/simple.rs
libafl/src/stages/concolic.rs
libafl_cc/src/clang.rs
libafl_cc/src/lib.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/coverage_rt.rs
libafl_targets/src/drcov.rs
libafl_targets/src/libfuzzer.rs

Rust changed so we must do so, too

Clippy fixes for latest toolchain

---

libafl_frida/src/asan/asan_rt.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs

Fixed additional new clippy lints for libafl_qemu, libafl_frida

---

libafl_frida/src/alloc.rs

After the good work of @tokatoka this enables asan for frida on Apple

[libafl_frida] Enabled ASan for Apple

---

libafl_qemu/src/emu.rs

Added two Emulator methods to work with guest memory:
* `map_fixed`
* `mprotect`
When emulating a snapshot, one needs the ability to map memory at a fixed address. `Emulator::map_fixed` does the trick for me. It is obviously very similar to `map_private`, so I created a non-pub method `Emulator::mmap` that handles the actual call internally. Before `Emulator::mmap` becomes pub, if ever, it should drop the `c_int` type from it's signature so it's easier to work with from client code.
I find `Emulator::mprotect` is useful when mapping in compilation objects from disk. First, one needs to `map_{private,fixed}` with RW permissions, then copy in the buffer with `write_mem`, finally, applying desired permissions (e.g. Read only) to the mapped chunk of memory. The name `mprotect` is just the …

[libafl_qemu] map_fixed and mprotect target memory

---

fuzzers/frida_libpng/harness.cc
libafl_frida/src/asan/asan_rt.rs

I mis-calculated the bits value

Asan Fix & Asan Crashing Testacse

---

libafl_frida/src/alloc.rs

I didn't know/overlooked that in _normal_ linux we have a vsyscall page that's also listed in `/proc/<pid>/maps`
thus, this pr pre-defines the highest userspace address depending on the target arch, and then we can exclude those kernel space? mem region

Shadow Bit Fix

---

libafl_qemu/src/asan.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/lib.rs
libafl_qemu/src/snapshot.rs

This PR is same as #497 except it only contains one commit ahead of main. Hopefully this is straight forward now

[libafl_qemu] GuestAddr type

---

libafl/src/lib.rs

suppress the specialization feature warning

Allow incomplete feature

---

libafl_cc/build.rs

My llvm or xcode installation seems to be broken. This PR works for me.

Add sdk linker flag for broken MacOS systems

---

fuzzers/forkserver_simple/src/main.rs
fuzzers/forkserver_simple/src/program.c
libafl/src/executors/forkserver.rs

I noticed there's a buggy pattern

Forkserver builder fix

---

libafl_qemu/build_linux.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_qemu/src/hooks.rs

Because, why not, it's not even breaking the current API

Closure hooks and on thread create hook

---

README.md

List dependencies in readme.md

---

fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
fuzzers/libfuzzer_stb_image_concolic/runtime/src/lib.rs
scripts/test_all_fuzzers.sh

Fix concolic fuzzer and add related CI tests

---

fuzzers/libfuzzer_stb_image_concolic/Makefile.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/src/main.rs
fuzzers/qemu_launcher/.gitignore
libafl_concolic/symcc_libafl/README.md
libafl_concolic/symcc_libafl/src/lib.rs
libafl_concolic/test/smoke_test.sh
scripts/test_all_fuzzers.sh

This PR aims to fix the CI regression introduced in #559

Fixing CI from #559

---

fuzzers/baby_fuzzer_gramatron/src/main.rs
fuzzers/baby_fuzzer_grimoire/src/main.rs
fuzzers/baby_fuzzer_nautilus/src/main.rs
fuzzers/baby_fuzzer_tokens/src/main.rs
fuzzers/fuzzbench/src/lib.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/fuzzbench_text/src/lib.rs
fuzzers/fuzzbench_weighted/src/lib.rs
libafl/src/mutators/mopt_mutator.rs
libafl/src/mutators/scheduled.rs

Now the constructor use max_stack_pow to set the number of max stacked mutations.

Set the number of stacked mutations in MOpt mutator

---

fuzzers/fuzzbench/src/bin/libafl_cc.rs
libafl_cc/build.rs
libafl_cc/src/autotokens-pass.cc
libafl_cc/src/clang.rs
libafl_targets/src/coverage.rs

also changed clang.rs to load passes that were built using new PM

Autotokens New PM

---

libafl_qemu/src/snapshot.rs

SYS_mmap and SYS_newfstatat is not part of arm syscall for linux. Replacing with equivalent syscall. https://github.com/koutheir/syscall-numbers/blob/master/src/arm.rs

adding equivalent arm32 syscall for qemu snapshot

---

.github/workflows/build_and_test.yml
.github/workflows/codecov.yml
scripts/test_all_fuzzers.sh

1. merge ubuntu fuzzers and macos fuzzers
2. add ccache(no obvious time boost)
3. record time for each fuzzer when running `./test_all_fuzzers.sh`

Merge ubuntu and macos fuzzer && Record time for `./test_all_fuzzers.sh`

---

scripts/autofix.sh

This script (tries to) fix compile errors and clippy errors automatically.

Added autofix script

---

libafl/src/bolts/llmp.rs
libafl/src/bolts/minibsod.rs
libafl_cc/build.rs
libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/cmplog_rt.rs
libafl_frida/src/coverage_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/utils.rs
scripts/autofix.sh

Not sure why they didn't block CI?

Clippy nits & fixes

---

libafl_qemu/src/hooks.rs

No break only fix

---

.gitignore
libafl/src/bolts/fs.rs
libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs

This is a potential solution for #647, feel free to discuss @radl97 @tokatoka

Make OutFile auto-remove refcounted on drop

---

scripts/clippy.sh

Update symcc, clippy in release mode

Symcc update

---

libafl/Cargo.toml
libafl/src/bolts/shmem.rs
libafl/src/executors/inprocess.rs
libafl/src/lib.rs

update windows-rs: 0.29 -> 0.37

Windows-rs Update

---

libafl/src/bolts/core_affinity.rs
libafl/src/events/llmp.rs

addressing this issue https://github.com/Elzair/core_affinity_rs/issues/8

Check syscall result in set_for_current

---

libafl/src/bolts/core_affinity.rs

Generating core ids based on the actual count of logical cores

---

libafl_cc/build.rs
libafl_cc/src/afl-coverage-pass.cc
libafl_cc/src/coverage-accounting-pass.cc

I made a mistake in this pr #626 and I found it crashes with llvm-14
this PR fixes it.

Fix AFLCoverage Pass & small fixes

---

fuzzers/fuzzbench_weighted/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
libafl/src/schedulers/weighted.rs

Allow weighted scheduler to use powerschedules

Extend weighted scheduler

---

fuzzers/fuzzbench_weighted/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
libafl/src/schedulers/weighted.rs

* extend
* fix
* fmt
* more fix

Extend weighted scheduler (#685)

---

libafl/src/schedulers/testcase_score.rs

Fix score calculation

---

fuzzers/tutorial/Cargo.toml
libafl/Cargo.toml

lain seems to be unmaintained.

Bump rand version, dropping support for lain

---

libafl_cc/src/autotokens-pass.cc
scripts/fmt_all.sh

some changes in #614 is wrong and it gives multiple definition of ... error with curl fuzzer

Fix autotokens

---

fuzzers/fuzzbench_weighted/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
libafl/src/schedulers/weighted.rs

2 constructor 
`new` and `with_schedule`

Change StdWeightedScheduler API

---

libafl/src/bolts/core_affinity.rs

the cpuset api is already present in libc...

follow-up on netbsd build fix, simplification.

---

libafl/src/generators/mod.rs
libafl/src/inputs/bytes.rs
libafl/src/inputs/generalized.rs
libafl/src/stages/mod.rs

This Pr allows us to write a Grimore stage that is conditionally turned on at runtime (without copy&pasting the whole thing)

Skippable stage, generator wrapper for Grimoire

---

.github/workflows/build_and_test.yml
libafl/src/bolts/core_affinity.rs
libafl/src/executors/forkserver.rs

This enables Github Actions for FreeBSD

CI for FreeBSD

---

.github/workflows/build_and_test.yml
libafl/src/executors/command.rs
libafl/src/executors/mod.rs

fix #741 
Tested on : Windows 10 Home (cargo 1.63.0)

Fix cargo doc failed on windows

---

libafl/src/executors/forkserver.rs

Fix forkserver options

---

libafl/src/bolts/core_affinity.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/shmem.rs

implementing core affinity too.

Illumos build fix proposal.

---

libafl/src/bolts/launcher.rs
libafl_qemu/src/executor.rs

Some minor compilation additions for #806

Minor changes for linux without fork feature

---

.github/workflows/build_and_test.yml

This time, I try removing /usr/share/dotnet

Another Attempt to Fix CI

---

libafl_qemu/libqasan/malloc.c

https://github.com/AFLplusplus/AFLplusplus/issues/1548

Backport AFL++ issue #1548

---

libafl/src/bolts/os/windows_exceptions.rs
libafl_frida/src/windows_hooks.rs

The related probem is described in #830

Calling original UnhandledExceptionFilter in the hook

---

libafl/src/events/llmp.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/shadow.rs
libafl/src/executors/timeout.rs
libafl/src/fuzzer/mod.rs
libafl_frida/src/asan/errors.rs
libafl_frida/src/executor.rs
libafl_nyx/src/executor.rs
libafl_qemu/src/executor.rs
libafl_sugar/src/qemu.rs

I can't actually commit to the other branch, so internal PR it is!

Associated types continuation for corpus + state

---

.github/workflows/build_and_test.yml
fuzzers/frida_libpng/Makefile.toml
fuzzers/fuzzbench/Makefile.toml
fuzzers/fuzzbench_text/Makefile.toml
fuzzers/fuzzbench_weighted/Makefile.toml
fuzzers/libfuzzer_libmozjpeg/Makefile.toml
fuzzers/libfuzzer_libpng/Makefile.toml
fuzzers/libfuzzer_libpng_accounting/Makefile.toml
fuzzers/libfuzzer_libpng_cmin/Makefile.toml
fuzzers/libfuzzer_libpng_ctx/Makefile.toml
fuzzers/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/libfuzzer_stb_image/Makefile.toml
fuzzers/libfuzzer_stb_image_concolic/Makefile.toml
fuzzers/libfuzzer_stb_image_concolic/fuzzer/build.rs
fuzzers/libfuzzer_stb_image_sugar/Makefile.toml
scripts/test_all_fuzzers.sh

This might speed up CI a bit, but requires >15 GB in disk space so might also just fail.

CI: Build fuzzers with shared cargo target dir

---

libafl/src/bolts/cpu.rs

introspection does not work on aarch64

Fix aarch64 read_time_counter()

---

.github/workflows/build_and_test.yml
fuzzers/nyx_libxml2_parallel/Makefile.toml
fuzzers/nyx_libxml2_parallel/setup_libxml2.sh
fuzzers/nyx_libxml2_standalone/Makefile.toml
fuzzers/nyx_libxml2_standalone/setup_libxml2.sh
scripts/clippy.sh
scripts/test_all_fuzzers.sh

TODOs:
~~- [ ] `baptiste0928/cargo-install` is supposed to cache builds. this doesn't seem to work.~~

CI: small fixes

---

libafl/src/executors/forkserver.rs

this makes 5x speedup on forkserver executor.
still not enough though

Set persistent mode env variables.

---

.github/workflows/build_and_test.yml

Fix CI yml

---

libafl/src/observers/concolic/mod.rs
libafl/src/observers/concolic/serialization_format.rs
libafl/src/stages/concolic.rs
libafl_concolic/symcc_libafl/src/lib.rs
libafl_concolic/symcc_runtime/src/filter.rs
libafl_concolic/symcc_runtime/src/tracing.rs
libafl_concolic/test/expected_constraints.txt
libafl_concolic/test/smoke_test.sh

A draft for now until all issues are resolved. Creating this PR for CI.

Update and fix concolic support

---

.github/workflows/build_and_test.yml
fuzzers/fuzzbench_forkserver/src/main.rs
scripts/test_all_fuzzers.sh
utils/build_and_test_fuzzers/src/main.rs

diffing from the last commit is not ok, we need to diff the changes of each PR from origin/main

Fix CI diffing

---

libafl_frida/Cargo.toml

to allow users to disable default features while using stuff from libafl-frida

disable libafl's default features in libafl-frida

---

libafl_qemu/src/calls.rs
libafl_qemu/src/lib.rs

Add mips support for QemuTracerHelper

Add mips support for QemuTracerHelper

---

fuzzers/libfuzzer_windows_asan/.gitignore
fuzzers/libfuzzer_windows_asan/Cargo.toml
fuzzers/libfuzzer_windows_asan/Makefile.toml
fuzzers/libfuzzer_windows_asan/README.md
fuzzers/libfuzzer_windows_asan/corpus/hello_world
fuzzers/libfuzzer_windows_asan/harness.cpp
fuzzers/libfuzzer_windows_asan/src/bin/libafl_cc.rs
fuzzers/libfuzzer_windows_asan/src/bin/libafl_cxx.rs
fuzzers/libfuzzer_windows_asan/src/lib.rs
libafl_cc/src/common-llvm.h
libafl_targets/src/libfuzzer.c
scripts/test_all_fuzzers.sh

This adds an example fuzzer for windows (including ASAN)
It currently uses clang from VS.
What do you think? Can we integrate this into the CI easily?

[Windows] Add libfuzzer example for windows with ASAN

---

docs/src/baby_fuzzer/baby_fuzzer.md
docs/src/baby_fuzzer/more_examples.md
docs/src/getting_started/crates.md
docs/src/getting_started/setup.md
docs/src/introduction.md
docs/src/libafl.md

By @hexcoder- , this includes the PRs #957 #958 #959 #960 #962 #963

Documentation fixes

---

.github/workflows/build_and_test.yml
fuzzers/frida_libpng/Makefile.toml
libafl/src/bolts/cli.rs

On windows, it wrongly generates `frida${SEP}/target` folder now

Frida Makefile.toml fix

---

docs/src/advanced_features/concolic.md
docs/src/advanced_features/frida.md
docs/src/advanced_features/no_std.md
docs/src/advanced_features/nyx.md
docs/src/core_concepts/corpus.md
docs/src/core_concepts/executor.md
docs/src/core_concepts/feedback.md
docs/src/core_concepts/input.md
docs/src/core_concepts/mutator.md
docs/src/core_concepts/observer.md
docs/src/core_concepts/stage.md
docs/src/design/architecture.md
docs/src/design/metadata.md
docs/src/design/migration-0.9.md
docs/src/message_passing/message_passing.md
docs/src/message_passing/spawn_instances.md
docs/src/tutorial/tutorial.md

The rest of my document review. Please review to make sure that I have not changed the semantics unintentionally, thanks!

book review part2

---

docs/src/advanced_features/concolic.md

@julihoh @hexcoder- can you please check if this is correct, and if it's understandable? Thanks :)

Book: Explain SymCC constraint solving (follow up on #980)

---

.github/workflows/build_and_test.yml
fuzzers/frida_libpng/harness.cc
libafl/src/bolts/core_affinity.rs

The header file wasn't found in my case

Fix Launcher for M1, fix frida_libpng harness compilation

---

fuzzers/frida_libpng/src/fuzzer.rs
libafl_frida/src/executor.rs
libafl_frida/src/helper.rs

This makes sure transformer is only created once, and not dropped early.
See https://github.com/frida/frida-rust/issues/76 for further discussion.

Fix early drop for frida transformer

---

libafl_qemu/libafl_qemu_build/Cargo.toml
libafl_qemu/libafl_qemu_build/src/build.rs

Trying to run qemu_systemmode example and qemu_arm example, i received linker error shown below. Odd thing is I tried it on 6 different machine and 3 of them worked while other 3 times it didnt.

fixing linking issue on qemu build

---

libafl/src/mutators/grimoire.rs
libafl/src/stages/mutational.rs
libafl/src/stages/power.rs
libafl/src/state/mod.rs

This addresses a few different bugs that were small enough that it felt like they didn't deserve separate PRs. Each bug attached to diff.

Fixes for multiple subtle bugs with grimoire, mutators, and state

---

fuzzers/baby_fuzzer/baby_fuzzer.py

@andreafioraldi fails with
```python
TypeError: argument 'py_observers': 'MapObserverI32' object cannot be converted to 'ObserversTuple'
```

Fixing python example

---

libafl_targets/src/cmplog.rs

Comment Fix

---

libafl_frida/src/coverage_rt.rs

Please can you give this branch a try and see if it improves performance any for you? Thanks.

Change to combine restoration prologue with coverage register spill

---

libafl/src/state/mod.rs

This makes it possible to load corpus subsets on different cores, like so:
```rust
let sample_list: Vec<_> = opt
.input
.read_dir()
.expect("Could not read input dir")
.collect();
assert!(!sample_list.is_empty(), "No inputs given");
let chunk_size = (sample_list.len() as f64 / opt.cores.ids.len() as f64).ceil() as usize;
```
...
and inside the launcher
```rust
let files: Vec<PathBuf> = sample_list
.iter()
.skip(chunk_size * core_id)
.take(chunk_size)
.map(|x| x.as_ref().unwrap().path())
.collect();
state
.load_initial_inputs_by_filenames(&mut fuzzer, &mut executor, &mut mgr, &files)
```

Allow to load a list of files

---

libafl/src/feedbacks/new_hash_feedback.rs

Most of the time, fuzzing campaigns are reasonably long. Accordingly, when using `NewHashFeedback`, you might have good reason to believe that you'll find thousands (or more) different observations with different hashes. When the `HashSet` outgrows its capacity, it can cause reallocation, which is slow. See the following link for more details:
https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation

libafl: `with_capacity` method for `NewHashFeedback`

---

libafl/src/feedbacks/new_hash_feedback.rs

See discussion on #1034.
cc @domenukk

libafl: Increase default capacity of NewHashFeedback

---

bindings/pylibafl/src/lib.rs
fuzzers/fuzzbench/src/lib.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_forkserver/src/main.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/fuzzbench_text/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
fuzzers/libfuzzer_libpng_cmin/src/lib.rs
fuzzers/libfuzzer_windows_asan/src/lib.rs
fuzzers/tutorial/src/lib.rs
libafl/src/corpus/testcase.rs
libafl/src/executors/inprocess.rs
libafl/src/feedbacks/concolic.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/nautilus.rs
libafl/src/fuzzer/mod.rs
libafl/src/schedulers/minimizer.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/tmin.rs
libafl_frida/src/asan/errors.rs

I opened this PR with the wrong history and (for some reason) couldn't get a force-push to update the branch. Here's the new branch.

Fixes for on_replace/on_remove and related for StdFuzzer and MapFeedback

---

libafl/src/inputs/generalized.rs
libafl/src/mutators/grimoire.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/generalization.rs

Extended fixes relating to changes in #1067.

Fix grimoire when used with on_replace/on_remove

---

libafl/Cargo.toml

Move bytecount to dev-dependencies

---

libafl/src/mutators/mutations.rs

This makes sure that mutated inputs satisfy the `state.max_size()` limit.

Fix max input size for {CrossOverInsert,BytesInsertCopy}Mutator

---

libafl/src/bolts/cli.rs
libafl/src/bolts/core_affinity.rs

This fixes a merge issue from earlier

Fix CoreId for Frida, FreeBSD

---

docs/src/message_passing/message_passing.md
fuzzers/baby_fuzzer_minimizing/src/main.rs
fuzzers/baby_fuzzer_nautilus/src/main.rs
fuzzers/baby_fuzzer_swap_differential/src/main.rs
fuzzers/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/fuzzbench_forkserver/src/main.rs
fuzzers/fuzzbench_qemu/src/fuzzer.rs
fuzzers/fuzzbench_text/src/lib.rs
fuzzers/libfuzzer_libpng/src/lib.rs
libafl/src/corpus/cached.rs
libafl/src/corpus/inmemory_ondisk.rs
libafl/src/corpus/mod.rs
libafl/src/corpus/ondisk.rs

This moves the current OnDiskCorpus to InMemoryOnDiskCorpus and adds a real OnDiskCorpus.

Real OnDiskCorpus

---

libafl_frida/src/executor.rs

Windows fix

---

libafl/src/schedulers/testcase_score.rs

fix for https://github.com/AFLplusplus/AFLplusplus/issues/1656

Fix multiplication to division in powerschedule weighting

---

.github/workflows/build_and_test.yml
.gitignore
fuzzers/baby_fuzzer/src/main.rs
fuzzers/baby_fuzzer_swap_differential/src/main.rs
libafl/src/bolts/core_affinity.rs
libafl/src/bolts/llmp.rs
libafl/src/bolts/minibsod.rs
libafl/src/bolts/os/unix_signals.rs
libafl/src/bolts/shmem.rs
libafl/src/bolts/staterestore.rs
libafl/src/events/llmp.rs
libafl/src/events/simple.rs
libafl/src/executors/command.rs
libafl/src/executors/forkserver.rs
libafl/src/executors/inprocess.rs
libafl/src/lib.rs
libafl/src/mutators/mutations.rs
libafl_cc/src/cfg.rs
libafl_cc/src/clang.rs

Ignores those that cannot be supported

Allows libafl tests to run in miri

---

libafl/src/inputs/bytes.rs

Allow take the ownership of the BytesInput

---

fuzzers/baby_fuzzer_swap_differential/Makefile.toml
fuzzers/baby_fuzzer_swap_differential/src/main.rs

Addresses #1133, but a new (I think spurious) Miri error comes out now. :upside_down_face:

Resolve zero-sized allocation in swap diff fuzzer

---

libafl/src/mutators/gramatron.rs
libafl/src/schedulers/ecofuzz.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/testcase_score.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/sync.rs
libafl/src/state/mod.rs

Hello, previously I've implemented functions to reduce the amount of code when getting metadata or the testcase out of a state. So I searched the code and made some changes, but during this process I found cases which didn't fit into what I initially proposed. So, I would like to discuss some changes that can be made to make these functions more or how to adapt the API.

new metadata() and testcase() function added to the code

---

.github/workflows/build_and_test.yml
libafl/src/stages/logics.rs

Let's see if we can link z3, else we'll have to revert #1160 or at least disable the feature by default..

Install libz3-dev in CI

---

fuzzers/fuzzbench_fork_qemu/Makefile.toml
fuzzers/fuzzbench_qemu/Makefile.toml
fuzzers/libfuzzer_stb_image_sugar/Makefile.toml

it's broken since 0.7.0 #1176 
and sugar needs updates

Remove libfuzzer_stb_image_sugar for now

---

fuzzers/baby_fuzzer_minimizing/src/main.rs

modify `MapEqualityFactory::with_observer` to `MapEqualityFactory::new_from_observer`

Fix a build error in baby_fuzzer_minimizing

---

fuzzers/baby_fuzzer_minimizing/src/main.rs
libafl/src/stages/tmin.rs

Removed more `new_` (follow-up on #1159)

---

.gitignore
fuzzers/baby_fuzzer_gramatron/src/main.rs
fuzzers/baby_fuzzer_minimizing/src/main.rs
fuzzers/baby_fuzzer_nautilus/src/main.rs
fuzzers/baby_fuzzer_tokens/src/main.rs
fuzzers/baby_fuzzer_with_forkexecutor/src/main.rs
fuzzers/baby_no_std/src/main.rs
fuzzers/backtrace_baby_fuzzers/rust_code_with_fork_executor/src/main.rs
fuzzers/backtrace_baby_fuzzers/rust_code_with_inprocess_executor/src/main.rs

This further reduces undefined behaviour in our example fuzzers and should fix #1132

Example fuzzers with even less UB

---

fuzzers/baby_fuzzer/src/main.rs
fuzzers/baby_fuzzer_swap_differential/src/main.rs
fuzzers/nyx_libxml2_standalone/src/main.rs
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs

The status bar will contain the name of fuzzer and the version information of LibAFL.

add the version information of LibAFL in the UI

---

utils/cfg_builder/README.md
utils/cfg_builder/build.py

Follow-up on #1226 
Dump the call graph, and added a README on how to use the script

Dump Call Graph

---

libafl/src/fuzzer/mod.rs
libafl/src/schedulers/ecofuzz.rs
libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/probabilistic_sampling.rs
libafl/src/schedulers/queue.rs
libafl/src/schedulers/tuneable.rs
libafl/src/schedulers/weighted.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/generalization.rs
libafl/src/stages/mod.rs
libafl/src/stages/push/mod.rs
libafl/src/stages/push/mutational.rs
libafl/src/stages/tmin.rs

Alternative implementation of #1250.

Alternative scheduled count strategy

---

libafl/src/events/simple.rs
libafl/src/generators/mod.rs
libafl/src/lib.rs

It's that time of the year again :)
Few, but good suggestions

Fix latest clippy

---

.github/workflows/build_and_test.yml
scripts/executions-check.sh

Reverts AFLplusplus/LibAFL#1270

Revert "Automatically add the comment about executions when a new PR triggers"

---

libafl_cc/src/clang.rs

Reverts AFLplusplus/LibAFL#1274

Revert "Don't pass LLVM pass & its args during linking"

---

utils/noaslr/demo/build.rs
utils/noaslr/demo/src/main.rs
utils/noaslr/libnoaslr/src/lib.rs
utils/noaslr/noaslr/Cargo.toml
utils/noaslr/noaslr/build.rs
utils/noaslr/noaslr/src/args.rs
utils/noaslr/noaslr/src/main.rs

to port to the library, might need a nice layer over the FreeBSD's C api (nix?) before hand.

util/noaslr porting to FreeBSD (the non-lib part).

---

libafl_qemu/libafl_qemu_build/src/build.rs

https://github.com/AFLplusplus/qemu-libafl-bridge/issues/27

Fix generic hooks bug in libafl_qemu

---

.github/workflows/build_and_test.yml

This should make CI marginally faster

CI: Move apt-get before checkout

---

Dockerfile
fuzzers/push_harness/Cargo.toml
fuzzers/push_harness/src/main.rs

More fuzzer fixes for Bolts

---

libafl/src/schedulers/powersched.rs

this fixes https://github.com/AFLplusplus/LibAFL/issues/1373

update documentation of `PowerQueueScheduler::on_add`

---

libafl/src/schedulers/ecofuzz.rs
libafl/src/schedulers/minimizer.rs
libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/weighted.rs

This extends #1409 and fixes the leftovers of #1373

Updated Scheduler::on_add documentation

---

libafl_bolts/src/core_affinity.rs

Tiny clippy fix

---

libafl/src/feedbacks/map.rs

this current seems to describe `NextPow2IsNovel`

update documentation of `feedbacks::map::OneOrFilledIsNovel`

---

fuzzers/baby_fuzzer_minimizing/src/main.rs
libafl_frida/src/executor.rs
libafl_qemu/src/executor.rs
libafl_sugar/src/qemu.rs

Fixes for frida, qemu_sugar

---

libafl_bolts/src/minibsod.rs

pretty close to freebsd for the most part.

bolts write_minibsod netbsd implementation.

---

fuzzers/frida_gdiplus/src/fuzzer.rs
libafl_frida/src/executor.rs
libafl_frida/src/pthread_hook.rs

Looks like simply getting the thread_id for `stalker` doesn't work on windows, at least since #1256 the CI was red.
This PR uses `follow_me` if no thread id is given.

Fix Frida CI for Windows, Clippy

---

fuzzers/frida_executable_libpng/src/fuzzer.rs
fuzzers/frida_executable_libpng/src/lib.rs

Clippy fixes for frida_executable_libpng fuzzer

---

libafl/src/mutators/tuneable.rs

This commit fixes some issues regarding the `TuneableScheduledMutator`, which had an edge case for drawing probabilities.
The user is supposed to provide a vector with probabilities that have to add up to 1.0, but due to floating-point errors, the number can be sligthly off.
If the sum ends up being slow, there's a chance that we draw a number that is bigger than it (for example, 1.0), and that would not be present in the cumulative distribution vectors (either for iterations or mutations).
The issue is fixed by setting the last value of the cumulative distribution to 1.0.
This commits adds some validations in the function that calculates the cumulative distribution function, making sure that the numbers add up to 1, and that they are all between 0 and 1.
The API is now changed so the …

Fix probabilities in TuneableScheduledMutator.

---

libafl/Cargo.toml
libafl_bolts/Cargo.toml

This reduces some dependencies

Use postcard with default-features = false

---

libafl/Cargo.toml
libafl/src/executors/inprocess.rs
libafl/src/executors/timeout.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/shmem.rs

Windows dependency upgrade

---

fuzzers/baby_fuzzer_gramatron/Cargo.toml
libafl/Cargo.toml
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/observers/concolic/metadata.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/build_id.rs
libafl_concolic/symcc_libafl/Cargo.toml
libafl_concolic/symcc_runtime/Cargo.toml
libafl_concolic/symcc_runtime/build.rs
libafl_frida/Cargo.toml
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_build/Cargo.toml
libafl_qemu/libafl_qemu_sys/Cargo.toml
libafl_sugar/Cargo.toml
libafl_targets/Cargo.toml
utils/gramatron/construct_automata/Cargo.toml
utils/gramatron/construct_automata/src/main.rs

Remove dependencies, add doc.rs metadata

---

.github/workflows/build_and_test.yml
README.md
libafl/Cargo.toml
libafl/src/events/tcp.rs
libafl/src/lib.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/lib.rs
libafl_targets/src/sancov_8bit.rs

This adds information for all features we have in LibAFL to the docs

Document features

---

libafl_bolts/src/llmp.rs

The Rust stdlib has a lot of cool functionality, let's use it :)

Replace binary search with stdlib

---

libafl/Cargo.toml
libafl/src/lib.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/lib.rs
libafl_concolic/symcc_libafl/Cargo.toml
libafl_concolic/symcc_runtime/Cargo.toml
libafl_libfuzzer/Cargo.toml
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml

This should fix the docs.rs error `[INFO] [stderr] error: none of the selected packages contains these features: document-features`

Introduce document-features feature

---

docs/src/introduction.md
docs/src/message_passing/configurations.md
docs/src/message_passing/spawn_instances.md
libafl/src/events/launcher.rs

will make it easer to find the `LIBAFL_DEBUG_OUTPUT` env variable for Launcher debugging.

Document LIBAFL_DEBUG_OUTPUT in Launcher

---

libafl/src/stages/tuneable.rs

Yet another follow-up to #1437 and #1458

Fix TuneableMutationalStage _std function generics

---

.github/workflows/build_and_test.yml
fuzzers/qemu_coverage/build.rs
fuzzers/qemu_launcher/build.rs
libafl/Cargo.toml
libafl/build.rs
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_sys/Cargo.toml
libafl_qemu/libafl_qemu_sys/build_linux.rs

This aims to fix #1492 and hopefully allows the docs build with `--all-features`.

Fix docs build for libafl_qemu

---

fuzzers/libafl_atheris/Makefile
fuzzers/libafl_atheris/src/lib.rs

Fixed libafl_atheris Makefile clean action, and fixed reading input flag in lib.rs

Fixed libafl_atheris Makefile and reading of input flag

---

.github/workflows/build_and_test.yml
libafl/src/stages/calibrate.rs
libafl_frida/src/cmplog_rt.rs

Don't send unstable entries if there's nothing

---

Cargo.toml
fuzzers/libfuzzer_libpng_centralized/Cargo.toml
fuzzers/libfuzzer_libpng_norestart/Cargo.toml
utils/gdb_qemu/demo/Cargo.toml
utils/noaslr/demo/Cargo.toml

the previous one had conflicts

Give proper name to some crates and exclude them 2

---

libafl_frida/src/alloc.rs

I am fixing the build ability for Android x86_64.

fix(libafl_frida): enable asan for Android x86_64

---

libafl/src/executors/inprocess.rs
libafl_frida/src/executor.rs
libafl_qemu/src/executor.rs
libafl_targets/src/windows_asan.rs

reverting #1327 
But I still don't understand why this is bad

Fix libjpeg fuzzer

---

libafl_cc/src/cmplog-routines-pass.cc

Reverts AFLplusplus/LibAFL#1589
i need to add runtime callbacks to it it's not done

Revert "Update cmplog-routines-pass.cc"

---

libafl_frida/src/helper.rs

In the original version, information about an instruction was recorded as information about the covered basic block, which is incorrect. I have been using this patch for a long time, but no one has made fixes/PR in all this time. Maybe I'm wrong and everything works correctly?..

fix(libafl_frida): correctly calculate the coverage using DrCov

---

libafl/src/stages/logics.rs

Makes it possible to use a stage that's `None` if it cannot be constructed (i.e., no complog binary was available)

Add OptionalStage

---

libafl_bolts/src/lib.rs
libafl_targets/build.rs
libafl_tinyinst/src/lib.rs

Remove warnings

---

Dockerfile

Updated the rust container image to 1.73.0 and added the command `rustup default nightly`

updated rust container image + default nightly

---

.github/workflows/build_and_test.yml

Since I didn't get #1646 to run properly, trying this way now.
See https://github.com/vmactions/freebsd-vm/issues/74 for reference

Fix FreeBSD CI by updating freebsd-vm

---

fuzzers/libfuzzer_libpng_centralized/Cargo.toml
libafl/Cargo.toml
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/mod.rs
libafl/src/fuzzer/mod.rs
libafl/src/stages/concolic.rs
libafl/src/state/mod.rs

actually sending messages to the broker after #1674

scalability monitor 2nd

---

.github/workflows/update_rust_toolchain.yml

I don't know why sed doesn't work on ci while it works on my pc..

Fix scheduled ci

---

libafl_bolts/src/lib.rs

This adds a logger that logs to a `RawFd`

Add file descriptor logger

---

.github/workflows/build_and_test.yml
fuzzers/baby_fuzzer_swap_differential/Makefile.toml
fuzzers/frida_libpng/Makefile.toml
fuzzers/fuzzbench/Makefile.toml
fuzzers/fuzzbench_text/Makefile.toml
fuzzers/libafl_atheris/Makefile
fuzzers/libfuzzer_libmozjpeg/Makefile.toml
fuzzers/libfuzzer_libpng/Makefile.toml
fuzzers/libfuzzer_libpng_accounting/Makefile.toml
fuzzers/libfuzzer_libpng_centralized/Makefile.toml
fuzzers/libfuzzer_libpng_cmin/Makefile.toml
fuzzers/libfuzzer_libpng_ctx/Makefile.toml
fuzzers/libfuzzer_libpng_launcher/Makefile.toml
fuzzers/libfuzzer_libpng_norestart/Makefile.toml
fuzzers/libfuzzer_libpng_tcp_manager/Makefile.toml
fuzzers/libfuzzer_stb_image/Makefile.toml
fuzzers/libfuzzer_stb_image_sugar/Makefile.toml
fuzzers/nautilus_sync/Makefile.toml

My guess is that simply the duration to run the fuzzer is too short for the their machine to generate any testcase

Another attemp to fix CI

---

libafl/Cargo.toml
libafl/src/executors/inprocess.rs
libafl_bolts/src/os/unix_signals.rs

If you talk to a pipe that quits, it shouldn't kill the fuzzer

Ignore SigPipe by default

---

fuzzers/libafl_atheris/src/lib.rs

Fix atheris fmt, clippy

---

libafl_qemu/libafl_qemu_build/src/build.rs
libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs
libafl_qemu/src/emu.rs

updated QEMU. Adapted emu.rs to fit new interface.

---

fuzzers/qemu_launcher/Makefile.toml
fuzzers/qemu_launcher/README.md
fuzzers/qemu_launcher/injection_test/Makefile
fuzzers/qemu_launcher/injection_test/README.md

Fixes for https://github.com/AFLplusplus/LibAFL/issues/1785

Pr/fix qemu launcher build - fixes 1785

---

libafl_cc/build.rs
libafl_cc/src/cfg.rs
libafl_targets/build.rs

Increase default edgemap size

---

.github/workflows/build_and_test.yml
fuzzers/libfuzzer_libpng_ctx/Makefile.toml
libafl_bolts/src/os/windows_exceptions.rs
scripts/test_all_fuzzers.sh

num_enum #1350 update broke windows stuff.

Fix windows after #1350

---

libafl_qemu/src/emu.rs
libafl_qemu/src/hooks.rs

fix #1805
As mentioned in the issue, this is the solution 1, requiring the least amount of change to the current code base.

Fix libafl_qemu hooks references

---

libafl/src/stages/logics.rs

OptionalStage is a nested stage

---

libafl_qemu/build_linux.rs
libafl_qemu/libqasan/Makefile

fix https://github.com/AFLplusplus/LibAFL/issues/1831
as mentioned at #1832

Fix libafl_qemu libqasan Makefile

---

Dockerfile
fuzzers/forkserver_libafl_cc/Cargo.toml
fuzzers/forkserver_simple/Cargo.toml
fuzzers/fuzzbench/Cargo.toml
fuzzers/fuzzbench_fork_qemu/Cargo.toml
fuzzers/fuzzbench_forkserver/Cargo.toml
fuzzers/fuzzbench_forkserver_cmplog/Cargo.toml
fuzzers/fuzzbench_qemu/Cargo.toml
fuzzers/fuzzbench_text/Cargo.toml
fuzzers/qemu_launcher/Cargo.toml
libafl/Cargo.toml
libafl/src/executors/forkserver.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/llmp.rs
libafl_bolts/src/os/unix_shmem_server.rs
libafl_bolts/src/shmem.rs
libafl_concolic/test/dump_constraints/Cargo.toml
libafl_frida/Cargo.toml
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/helper.rs
libafl_frida/src/utils.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
utils/gdb_qemu/demo/Cargo.toml
utils/gdb_qemu/gdb_qemu/Cargo.toml
utils/gramatron/construct_automata/Cargo.toml
utils/noaslr/demo/Cargo.toml
utils/noaslr/libnoaslr/Cargo.toml
utils/noaslr/noaslr/Cargo.toml

Remove unused shmem structs, update Nix

---

libafl/src/mutators/token_mutations.rs
libafl_cc/src/no-link-rt.c

#1853 
Can you check this is fine? @novafacing

Fix token mutation crash

---

libafl_libfuzzer/libafl_libfuzzer_runtime/Cargo.toml
libafl_targets/Cargo.toml

Because these included files do not exist with llvm <= 14

Fix libfuzzer feature for LLVM <=14

---

libafl/src/corpus/mod.rs
libafl/src/executors/differential.rs
libafl/src/executors/hooks/timer.rs
libafl/src/executors/hooks/unix.rs
libafl/src/executors/inprocess.rs
libafl/src/executors/inprocess_fork.rs
libafl/src/executors/mod.rs
libafl/src/feedbacks/mod.rs
libafl/src/monitors/mod.rs
libafl/src/observers/mod.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/cmplog_rt.rs
libafl_qemu/libafl_qemu_sys/src/x86_64_stub_bindings.rs
libafl_qemu/src/emu.rs
libafl_qemu/src/executor.rs
libafl_targets/src/cmps/mod.rs
utils/noaslr/libnoaslr/src/lib.rs
utils/noaslr/noaslr/src/main.rs

Cleanup Pointer Clippy Lints

---

libafl_qemu/libafl_qemu_build/src/build.rs
libafl_qemu/src/emu.rs

Reverts AFLplusplus/LibAFL#1830
See discussion in https://github.com/AFLplusplus/LibAFL/pull/1806#issuecomment-1949217542

Revert "Companion patch to qemu-libafl-bridge #46"

---

libafl/src/monitors/tui/ui.rs

fix: TuiUI will cause deadlock problems under multi-threading.

---

libafl/src/events/centralized.rs
libafl/src/events/llmp.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/prometheus.rs
libafl/src/monitors/tui/mod.rs
libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/weighted.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/fuzz.rs
libafl_qemu/src/injections.rs

It's a tiny optimization, but it also doesn't hurt

Less useless allocs for monitor display

---

libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl_bolts/src/llmp.rs

If you don't send update exec message, once you no more find any new testcase, you got disconnected from the centralized broker.
This is wrong

Fix the centralize disconnection bug.

---

libafl/src/executors/hooks/timer.rs
libafl_bolts/src/os/windows_exceptions.rs

Fix batched timeout

---

libafl_bolts/src/anymap.rs
libafl_targets/Cargo.toml
libafl_targets/src/sancov_pcguard.rs

Fix UB in anymap.rs and other minor warnings.

---

libafl_qemu/libafl_qemu_build/src/bindings.rs

Fix for #1352.
It works on my side. Hopefully, this will be enough to fix the issue completely.

Fix libafl_qemu_sys unnecessarily rebuilding.

---

libafl/src/stages/calibrate.rs

Fix self.restart_helper.execs_since_progress_start in calibration stage

---

.github/workflows/build_and_test.yml
scripts/test_all_fuzzers.sh

this will hopefully shorten CI time even more

Separate fuzzbench fuzzers's test

---

libafl/src/schedulers/mod.rs
libafl/src/schedulers/powersched.rs
libafl/src/schedulers/probabilistic_sampling.rs
libafl/src/schedulers/queue.rs
libafl/src/schedulers/tuneable.rs
libafl/src/schedulers/weighted.rs
libafl_bolts/Cargo.toml
libafl_bolts/src/anymap.rs

Use const_assert not assert

---

libafl/src/events/tcp.rs
libafl/src/executors/forkserver.rs
libafl/src/stages/dump.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/os/mod.rs
libafl_bolts/src/shmem.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/corpus.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/merge.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/options.rs
libafl_qemu/src/snapshot.rs
scripts/fmt_all.sh

This is in line with the other names, generally

Rename OSError -> OsError and merge with redundant Error::File

---

.github/workflows/build_and_test.yml
fuzzers/tinyinst_simple/Makefile.toml
fuzzers/tinyinst_simple/README.md
fuzzers/tinyinst_simple/src/main.rs
fuzzers/tinyinst_simple/test/test.cpp
libafl_bolts/src/shmem.rs

Fix the id of MmapShMem to the shared memory path instead of the fd number.

Update tinyinst_simple to support Linux (#1316)

---

fuzzers/nyx_libxml2_parallel/src/main.rs
fuzzers/nyx_libxml2_standalone/src/main.rs
libafl_nyx/src/helper.rs
libafl_nyx/src/settings.rs

https://github.com/AFLplusplus/LibAFL/pull/1960#discussion_r1535977952, I also removed the `parallel_mode` field since it is kind of redundant.

libafl_nyx: Add documentation to `NyxSettings` fields

---

Dockerfile

Fix libafl_qemu fuzzers not building in Docker

---

fuzzers/frida_executable_libpng/Cargo.toml
fuzzers/frida_executable_libpng/src/fuzzer.rs
fuzzers/frida_executable_libpng/src/lib.rs
fuzzers/frida_gdiplus/Cargo.toml
fuzzers/frida_gdiplus/src/fuzzer.rs
fuzzers/frida_libpng/Cargo.toml
fuzzers/frida_libpng/src/fuzzer.rs
libafl_bolts/src/ownedref.rs
libafl_frida/Cargo.toml
libafl_frida/src/asan/errors.rs
libafl_frida/src/lib.rs
libafl_frida/src/pthread_hook.rs
libafl_frida/src/utils.rs

This fixes a bunch of things in Frida

Add unsafe to AsanErrorsObserver, fix UBs, fix Frida Version missmatch

---

fuzzers/baby_no_std/src/main.rs

Use new Rust CStr constant

---

fuzzers/nyx_libxml2_standalone/setup_libxml2.sh
libafl_qemu/src/command.rs
libafl_qemu/src/emu.rs

Fix non-generic inputs in libafl_qemu

---

libafl/src/monitors/disk.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/prometheus.rs
libafl/src/monitors/tui/mod.rs

Add option to enabled/disable client stats and fix #1771

---

Dockerfile

Missing file to build libafl_nyx in Docker

Update Dockerfile to work

---

.github/workflows/build_and_test.yml

I though CI was broken because ppl were playing around with self-hosted runners; turns out YAML is a bad format instead

Fix yml file for CI

---

libafl_frida/src/helper.rs

Fixes the issues logged in #2025 (but there may be more?)

Fix docs for frida (see #2025)

---

fuzzers/python_qemu/README.md
fuzzers/python_qemu/fuzzer.py
libafl_qemu/src/emu.rs
libafl_sugar/src/qemu.rs

Fix python bindings & example of LibAFL QEMU

---

libafl/Cargo.toml
libafl/src/events/centralized.rs
libafl/src/events/llmp.rs
libafl/src/events/mod.rs

There's no reason you can't implement this if you can implement the `EventStatsCollector` trait.
So merge them together.

Add HasAdaptiveSerializer trait.

---

libafl/src/executors/differential.rs

We try to keep generics ordered

Order differential generics alphabetically

---

libafl_bolts/src/core_affinity.rs

since 13.1 (EOL since mid-2023) , supports the sched affinity api like linux/dragonflybsd.

bolts: core affinity simplification for freebsd.

---

fuzzers/forkserver_libafl_cc/src/main.rs

Don't merge until CI passes pls

Missing tracking hints (oops)

---

.github/workflows/build_and_test.yml

Checkout repository before calling the filter action

Fix failing filter action in CI

---

libafl_frida/src/alloc.rs

This PR fixes edge cases in `check_shadow` and adds some additional tests

Frida windows check shadow fix

---

libafl_bolts/src/minibsod.rs

With #2162 we introduced some `*` imports that clippy doesn't like.
We don't currently run Apple clippy in CI, so...

Clippy for Apple after #2162

---

libafl_sugar/Cargo.toml
libafl_sugar/src/lib.rs

Fix libafl_sugar docs build

---

libafl/src/stages/calibrate.rs

This extends #2215 to be restart-safe

Report 100% stability if no unstable edges are found (extends #2215)

---

fuzzers/frida_executable_libpng/Cargo.toml
fuzzers/frida_gdiplus/Cargo.toml
fuzzers/frida_libpng/Cargo.toml
libafl/Cargo.toml
libafl_frida/src/utils.rs

There are probably more, remove if you see them! :)

Remove unused dependencies

---

.github/workflows/build_and_test.yml
libafl_frida/src/utils.rs
libafl_qemu/libafl_qemu_sys/build.rs
libafl_qemu/libafl_qemu_sys/build_linux.rs

Because I have to fix all of the clippy lints all the time...

Run Clippy on macOS

---

libafl/src/fuzzer/mod.rs

Follow-up to ##2226, cc @s1341

Clean up samplig_rate, add docs

---

libafl_libfuzzer/libafl_libfuzzer_runtime/src/merge.rs
libafl_qemu/Cargo.toml
libafl_qemu/build_linux.rs
libafl_qemu/runtime/libafl_qemu.h

fix #2249.
also added a testcase to avoid this kind of issue in the future

Fix `libafl_qemu.h`

---

libafl/src/executors/forkserver.rs
libafl/src/lib.rs
libafl_bolts/src/core_affinity.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/os/mod.rs
libafl_bolts/src/os/pipes.rs
libafl_bolts/src/os/unix_shmem_server.rs
libafl_bolts/src/os/unix_signals.rs
libafl_bolts/src/tuples.rs

Fix nix update (#2252)

---

libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/restarting.rs

Add always_interesting option to llmp mgr

---

libafl/Cargo.toml
libafl/src/monitors/tui/ui.rs
libafl_cc/build.rs

Update ratatui to 0.26

---

libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/restarting.rs

Reverts AFLplusplus/LibAFL#2262
It's not working.

Revert "Add always_interesting option to llmp mgr"

---

libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/restarting.rs

Reverts AFLplusplus/LibAFL#2274

Revert "Revert "Add always_interesting option to llmp mgr""

---

libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/hooks/centralized.rs
libafl/src/events/llmp/hooks/mod.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/tcp.rs
libafl_bolts/examples/llmp_test/main.rs
libafl_bolts/src/core_affinity.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/os/pipes.rs
libafl_bolts/src/os/unix_signals.rs
libafl_bolts/src/shmem.rs
libafl_libfuzzer/libafl_libfuzzer_runtime/src/fuzz.rs
libafl_targets/src/cmps/mod.rs
libafl_targets/src/sancov_8bit.rs
libafl_targets/src/sancov_pcguard.rs

replaces closures in llmp with a proper hook system, built using the tuple pattern.
we should use this pattern whenever we can imho, it s a good design

LLmp hooks

---

libafl/src/fuzzer/mod.rs
libafl/src/mutators/mod.rs
libafl/src/observers/stdio.rs

Adding some docs, related to #2266 and #2301.

Adding StdXObserver Docs

---

libafl/src/executors/combined.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/generalization.rs
libafl/src/stages/tracing.rs
libafl_targets/src/cmps/stages/aflpptracing.rs

Before i get down to stages fix i need to make this exec count reliable
- stages don't need increment
- combined don't need increment

Delete wrong exec count increment

---

fuzzers/baby_fuzzer_wasm/src/lib.rs
libafl/src/stages/calibrate.rs
libafl/src/stages/colorization.rs
libafl/src/stages/concolic.rs
libafl/src/stages/generalization.rs
libafl/src/stages/logics.rs
libafl/src/stages/mod.rs
libafl/src/stages/mutational.rs
libafl/src/stages/power.rs
libafl/src/stages/sync.rs
libafl/src/stages/tracing.rs
libafl_targets/src/cmps/stages/aflpptracing.rs

Re-Rename Retrying Restart Helper

---

CONTRIBUTING.md

clippy.sh is not in the root, so the command was not quite working.
Should there also be a note about the Powershell scripts for potential windows developers?

doc: fixed instruction in CONTRIBUTING.md

---

libafl/src/corpus/inmemory_ondisk.rs

Make sure inmemory_ondisk corpus catches filesystem errors correctly

---

fuzzers/libafl_atheris/Cargo.toml
fuzzers/libfuzzer_libpng/Cargo.toml
fuzzers/libfuzzer_libpng_accounting/Cargo.toml
fuzzers/libfuzzer_libpng_aflpp_ui/Cargo.toml
fuzzers/libfuzzer_libpng_centralized/Cargo.toml
fuzzers/libfuzzer_libpng_cmin/Cargo.toml
fuzzers/libfuzzer_libpng_launcher/Cargo.toml
fuzzers/libfuzzer_libpng_norestart/Cargo.toml
fuzzers/tutorial/Cargo.toml

We had a bunch of unupdated versions in the repo

Update all which dependencies

---

libafl/Cargo.toml
libafl/src/corpus/ondisk.rs
libafl_bolts/Cargo.toml
utils/gdb_qemu/gdb_qemu/Cargo.toml
utils/noaslr/noaslr/Cargo.toml

Users should set that themselves

Remove release_max_level_info from log

---

libafl/src/stages/sync.rs

This seems more descriptive as a name
Follow-up to #2402

Rename load_new_from_drectory to find_new_files_rec

---

libafl/src/events/llmp/restarting.rs

Just implementing the missing HasCustomBufHandlers for LlmpRestartingEventManager from the internal llmp_mgr so that we can add custom buf handlers easily when using the Launcher:
```rust
let mut run_client =
|state: Option<_>, mut mgr: LlmpRestartingEventManager<_, _, _>, _core_id| {
mgr.add_custom_buf_handler(buf_handler);
```

impl HasEventManagerId for LlmpRestartingEventManager

---

fuzzers/libafl-fuzz/src/fuzzer.rs
fuzzers/libafl-fuzz/src/scheduler.rs

libafl-fuzz: add IndexesLenMinTimeScheduler back

---

.github/workflows/build_and_test.yml
.github/workflows/fuzzer-tester-prepare/action.yml
.github/workflows/qemu-fuzzer-tester-prepare/action.yml
.github/workflows/ubuntu-prepare/action.yml
.github/workflows/windows-tester-prepare/action.yml

CI: update actions and fix warnings

---

fuzzers/libpng/libfuzzer_libpng_cmin/README.md

Fix markdown issue in fuzzers/libpng/libfuzzer_libpng_cmin/README.md

---

.github/workflows/build_and_test.yml
fuzzers/others/libafl-fuzz/Makefile.toml

This makes sure TOML files are formatted with Taplo, follow-up to #2436

Add Taplo check to CI

---

.github/workflows/build_and_test.yml

...
Not sure if Github allows this with sub-yamls?

Speedup CI by moving checkout back

---

fuzzers/qemu/qemu_launcher/Cargo.toml
fuzzers/qemu/qemu_launcher/injection_test/.gitignore
libafl/src/monitors/tui/ui.rs
libafl_qemu/libafl_qemu_build/src/lib.rs

This makes it easier to build and test

libafl_qemu: Continue build with outdated LLVM, ignore TUI race conditions

---

.gitignore
libafl/src/events/centralized.rs
libafl/src/events/events_hooks/mod.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/mgr.rs
libafl/src/events/llmp/mod.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/fuzzer/mod.rs

After several attempts, I finally got how i can do this.
all event manager should have `S` and I should be <S::Corpus as Corpus>::Input

No uses from EventManager

---

libafl_targets/src/sancov_pcguard.rs

Make pcs_init compatible with multiple DSOs

---

libafl/src/stages/calibrate.rs

This resolves a minor typo discovered while testing https://github.com/TNO-S3/WuppieFuzz/pull/5

Fix typo in error message

---

libafl_qemu/src/modules/calls.rs
libafl_qemu/src/modules/cmplog.rs
libafl_qemu/src/modules/edges.rs
libafl_qemu/src/modules/mod.rs
libafl_qemu/src/modules/usermode/asan.rs
libafl_qemu/src/modules/usermode/asan_guest.rs
libafl_qemu/src/modules/usermode/drcov.rs
libafl_qemu/src/modules/usermode/injections.rs
libafl_qemu/src/modules/usermode/snapshot.rs

bring `state` to the first arg

Change qemu signature (again)

---

fuzzers/others/libafl-fuzz/src/scheduler.rs
libafl/src/schedulers/minimizer.rs

This fixes libafl-fuzz's Scheduler with the new Scheduler changes

libafl-fuzz: fix libafl-fuzz scheduler

---

fuzzers/others/libafl-fuzz/.gitignore
fuzzers/others/libafl-fuzz/Makefile.toml
fuzzers/others/libafl-fuzz/rustfmt.toml
fuzzers/others/libafl-fuzz/src/afl_stats.rs
fuzzers/others/libafl-fuzz/src/corpus.rs
fuzzers/others/libafl-fuzz/src/env_parser.rs
fuzzers/others/libafl-fuzz/src/executor.rs
fuzzers/others/libafl-fuzz/src/feedback/filepath.rs
fuzzers/others/libafl-fuzz/src/feedback/persistent_record.rs
fuzzers/others/libafl-fuzz/src/feedback/seed.rs
fuzzers/others/libafl-fuzz/src/fuzzer.rs
fuzzers/others/libafl-fuzz/src/main.rs
fuzzers/others/libafl-fuzz/src/scheduler.rs

Make LibAFL-fuzz build on MacOS

---

libafl_cc/build.rs
libafl_frida/Cargo.toml
libafl_frida/src/alloc.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/test_harness.cpp

This patch makes startup on MacOS significantly faster as well as fixes some bugs. The way we increase the speed by stopping at the shadow region as well as it is the highest possible relevant region. 
We also remove TLS tracking on darwin systems as TLS regions are allocated on the heap.

MacOS frida ASAN fix

---

libafl_qemu/src/modules/mod.rs

possibility to update filters from modules with a helper function

Addr filter update helper functions

---

libafl/src/executors/forkserver.rs

In the current version, the `Forkserver` will tell the address sanitizer to save a log file, which can cause significant degradation in the fuzzing throughput (nearly 10x slower).
This PR adds an option for specifying whether a log file should be saved by the address sanitizer. A log file will be saved only when an `AsanBacktraceObserver` is attached.

Add option for ASAN log dumping

---

fuzzers/binary_only/qemu_launcher/README.md
fuzzers/binary_only/qemu_launcher/src/client.rs
fuzzers/binary_only/qemu_launcher/src/harness.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
libafl_targets/src/coverage.rs

This makes this easier to adapt to new targets.

Qemu_Launcher: Move all target-specific code to harness.rs

---

fuzzers/binary_only/qemu_launcher/src/client.rs
fuzzers/binary_only/qemu_launcher/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
fuzzers/binary_only/qemu_launcher/src/options.rs

Add AFLStats to QEMU_Launcher TUI

---

libafl/src/executors/forkserver.rs

Reverts AFLplusplus/LibAFL#2612
The revert makes no sense at all

Revert "Revert "Fix pipe I/O in forkserver""

---

libafl_qemu/src/modules/usermode/asan_guest.rs
libafl_qemu/src/modules/usermode/snapshot.rs

Fix minor issues introduced in #2367

libafl_qemu: fix RISC-V port issues

---

libafl_bolts/src/lib.rs

Move it out of the nightly flag.

Core::errors::Error is stable now

---

.github/workflows/build_and_test.yml
bindings/pylibafl/test.py
fuzzers/binary_only/python_qemu/fuzzer.py
fuzzers/inprocess/dynamic_analysis/concatenator.py
libafl/src/events/launcher.rs
scripts/fmt_all.sh
scripts/parallellize_cargo_check.py
utils/cfg_builder/build.py
utils/gramatron/construct_automata.py
utils/gramatron/gnf_converter.py
utils/libafl_fmt/Cargo.toml
utils/libafl_fmt/src/main.rs

As discussed in #2665.
This is a very simple implementation that just spawns n clients per core. I'm not sure how this interacts with fixing a certain client to a core (via core affinity of the thread/process).
I've also added some cleanup (pre-commit scripts that have been complaining for a bit, unnecessary cfg restrictions).

Introducing Launcher::overcommit, improving CI formatting

---

fuzzers/forkserver/libafl-fuzz/Cargo.toml
fuzzers/forkserver/libafl-fuzz/Makefile.toml
fuzzers/forkserver/libafl-fuzz/src/corpus.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
fuzzers/forkserver/libafl-fuzz/src/main.rs

Use SimpleMonitor/EventManager instead of Centralized stuff for FuzzBench

Feature: libafl-fuzzfuzzbench

---

Cargo.toml
libafl/Cargo.toml
libafl/src/mutators/token_mutations.rs
libafl/src/observers/cmp.rs
libafl_intelpt/Cargo.toml
libafl_intelpt/src/lib.rs
libafl_targets/src/cmps/mod.rs

follow up of https://github.com/AFLplusplus/LibAFL/pull/2471

move to bitbybit

---

fuzzers/baby/baby_fuzzer_custom_executor/Cargo.toml
fuzzers/baby/baby_fuzzer_minimizing/Cargo.toml
fuzzers/baby/baby_fuzzer_swap_differential/Cargo.toml
fuzzers/baby/baby_fuzzer_unicode/Cargo.toml
fuzzers/binary_only/qemu_launcher/src/options.rs
libafl/src/mutators/grimoire.rs
libafl/src/mutators/unicode/mod.rs
libafl/src/schedulers/accounting.rs
libafl/src/schedulers/testcase_score.rs
libafl/src/state/mod.rs
libafl_cc/src/clang.rs
libafl_libfuzzer/build.rs
libafl_libfuzzer/runtime/src/corpus.rs
libafl_qemu/libafl_qemu_build/src/lib.rs

We forgot to add the tui_monitor flag to examples

Fix tui monitor for example fuzzers

---

.github/dependabot.yml

Ignore pyo3 update

---

fuzzers/baby/baby_fuzzer/src/main.rs

update baby_fuzzer example to 0.14

---

.github/workflows/build_and_test.yml

Run miri test only if it has labels

---

Cargo.toml
bindings/pylibafl/Cargo.toml
bindings/pylibafl/src/lib.rs
fuzzers/baby/baby_fuzzer/src/main.rs
libafl/Cargo.toml
libafl_bolts/Cargo.toml
libafl_bolts/src/lib.rs
libafl_qemu/Cargo.toml
libafl_qemu/libafl_qemu_sys/Cargo.toml
libafl_qemu/libafl_qemu_sys/src/usermode.rs
libafl_qemu/src/arch/aarch64.rs
libafl_qemu/src/arch/arm.rs
libafl_qemu/src/arch/i386.rs
libafl_qemu/src/arch/mips.rs
libafl_qemu/src/arch/mod.rs
libafl_qemu/src/arch/ppc.rs
libafl_qemu/src/arch/x86_64.rs
libafl_qemu/src/lib.rs
libafl_qemu/src/qemu/mod.rs
libafl_qemu/src/qemu/usermode.rs
libafl_sugar/Cargo.toml
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs

* add python bindings to workspace
* make pyo3 stuff dependent of workspace again
* adapt impl for pyo3

Update pyo3 to version 0.23.2

---

libafl/Cargo.toml

This removes some dependencies down the road.

Remove non_basic const_panic features

---

libafl/src/inputs/multi.rs

Follow-up to #2750.
@domenukk better now?

Fixing Empty MultipartInput Names Part 2

---

libafl/src/corpus/mod.rs
libafl/src/events/llmp/mgr.rs
libafl/src/mutators/mod.rs
libafl/src/mutators/token_mutations.rs
libafl_frida/src/helper.rs
libafl_qemu/src/emu/hooks.rs
libafl_qemu/src/qemu/usermode.rs

New year new clippy

---

libafl_targets/src/libfuzzer/mutators.rs

Lots of things we missed... :)

Clippy bugfix

---

libafl_targets/src/libfuzzer/mutators.rs

More clippy

---

libafl/src/events/llmp/restarting.rs
libafl/src/feedbacks/bool.rs
libafl/src/feedbacks/mod.rs
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/feedbacks/value_bloom.rs
libafl/src/inputs/mod.rs
libafl/src/stages/mod.rs
libafl/src/state/mod.rs

A simple feedback that says true or false..

Add BoolValueFeedback

---

.github/workflows/build_and_test.yml

No we don't have enough ci runners to handle them..

Revert "Don't fail fast for now"

---

fuzzers/forkserver/libafl-fuzz/src/executor.rs

Remove UsesState from libafl-fuzz

---

.vscode/settings.json.default

else i have to wait for 5 minutes for rust analyzer

Set rust-analyzer.cargo.allTargets to False in setings.json.default

---

libafl/src/executors/command.rs
libafl/src/feedbacks/stdio.rs
libafl/src/observers/stdio.rs
libafl_nyx/src/executor.rs

Dedup stdout/stdin observer

---

libafl_qemu/libqasan/malloc.c

i think this is a vestige from an old version of qasan.
it was not crashing here because sizeof(struct chunk_struct) >= sizeof(struct chunk_begin) so no overflow.

Fix qasan type confusion

---

utils/drcov_utils/Cargo.toml
utils/drcov_utils/src/bin/drcov_dump_addrs.rs

then recursively scan folders and process all the files

Make drcov_dump_address.rs accept list of directories

---

MIGRATION.md
fuzzers/inprocess/libfuzzer_libpng_launcher/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_norestart/src/lib.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/tui/mod.rs

Change combine_monitors macro to be tuple_list of Monitors

---

fuzzers/binary_only/fuzzbench_qemu/src/fuzzer.rs
fuzzers/binary_only/qemu_coverage/src/fuzzer.rs
libafl_qemu/src/qemu/usermode.rs

then you can view it like
```
let mappings = QemuMappings::new(&qemu);
println!("{:#?}", mappings);
```

Add a functionality to see the current qemu mappings.

---

libafl_qemu/src/qemu/usermode.rs

Add getter method to QemuMappingsViewer

---

Cargo.toml
libafl_qemu/src/modules/usermode/snapshot.rs

Fix brk() handling for snapshot module

---

fuzzers/baby/baby_fuzzer_swap_differential/README.md
fuzzers/binary_only/frida_executable_libpng/README.md
fuzzers/binary_only/frida_libpng/README.md
fuzzers/binary_only/intel_pt_baby_fuzzer/README.md
fuzzers/binary_only/intel_pt_command_executor/README.md
fuzzers/binary_only/qemu_cmin/README.md
fuzzers/binary_only/qemu_coverage/README.md
fuzzers/binary_only/qemu_launcher/README.md
fuzzers/binary_only/tinyinst_simple/README.md
fuzzers/forkserver/forkserver_libafl_cc/README.md
fuzzers/full_system/nyx_libxml2_parallel/README.md
fuzzers/full_system/nyx_libxml2_standalone/README.md
fuzzers/full_system/qemu_linux_kernel/README.md
fuzzers/full_system/qemu_linux_process/README.md
fuzzers/fuzz_anything/baby_fuzzer_wasm/README.md
fuzzers/inprocess/libfuzzer_windows_asan/README.md
utils/gdb_qemu/README.md
utils/noaslr/README.md

Replace "cargo make" to "just" in md files

---

libafl/src/inputs/value.rs

- [ x] I have run `./script/fmt_all.sh` to format the code
- [ x] I have run `./script/clippy.sh` and fixed all errors/warnings

Change type generic of ValueInput from I to T

---

fuzzers/inprocess/fuzzbench/Justfile
libafl/src/stages/replay.rs

Fix replay

---

libafl/src/common/mod.rs
libafl_bolts/src/lib.rs
libafl_bolts/src/serdeany.rs

Add try_insert for SerdeAnyMap

---

.github/PULL_REQUEST_TEMPLATE.md

Add PR description place

---

.github/PULL_REQUEST_TEMPLATE.md
scripts/precommit.sh

Adds a simpler-to-use single script

Add precommit script

---

.github/PULL_REQUEST_TEMPLATE.md
libafl/src/events/mod.rs
libafl/src/feedbacks/list.rs
libafl/src/feedbacks/map.rs
libafl/src/feedbacks/new_hash_feedback.rs
libafl/src/fuzzer/mod.rs
libafl/src/inputs/encoded.rs
libafl/src/inputs/gramatron.rs
libafl/src/monitors/stats/perf_stats.rs
libafl/src/mutators/scheduled.rs
libafl/src/observers/stacktrace.rs
libafl/src/stages/push/mod.rs
libafl_bolts/src/ownedref.rs
libafl_cc/src/ar.rs
libafl_cc/src/clang.rs
libafl_cc/src/libtool.rs

Fix Clippy for Rust 1.85

---

.github/workflows/build_and_test.yml

cuz it doesn't work (not our fault)

Disable windows-libfuzzer-asan

---

.github/workflows/build_and_test.yml
libafl_cc/src/ddg-instr.cc

Update LLVM in CI

---

.github/workflows/build_and_test.yml

Disable CI that uses self-hosted runner

---

.gitignore
libafl_libfuzzer/log

Delete useless file

---

libafl_qemu/src/modules/usermode/snapshot.rs

Fix snapshot module 

---

.github/workflows/build_and_test.yml

Debug windows CI

---

.github/workflows/build_and_test.yml

Debug Windows CI (again)

---

docs/src/DEBUGGING.md

Add more debugging tips

---

fuzzers/binary_only/qemu_launcher/src/fuzzer.rs
fuzzers/full_system/nyx_launcher/src/fuzzer.rs
fuzzers/inprocess/fuzzbench/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_centralized/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_launcher/src/lib.rs
fuzzers/inprocess/sqlite_centralized_multi_machine/src/lib.rs
libafl/src/events/centralized.rs
libafl/src/events/launcher.rs
libafl/src/events/llmp/restarting.rs
libafl/src/events/mod.rs
libafl/src/events/simple.rs
libafl/src/executors/hooks/inprocess.rs
libafl/src/executors/hooks/unix.rs
libafl/src/executors/hooks/windows.rs
libafl/src/executors/inprocess/inner.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/executors/inprocess/stateful.rs
libafl/src/feedbacks/map.rs
libafl/src/fuzzer/mod.rs
libafl_qemu/src/executor.rs
libafl_sugar/src/forkserver.rs
libafl_sugar/src/inmemory.rs
libafl_sugar/src/qemu.rs
libafl_targets/src/windows_asan.rs

Remove AdaptiveSerializer, Send off interesting testcase from crash handler, Add clearer error message

---

fuzzers/inprocess/fuzzbench/src/lib.rs
libafl/src/feedbacks/map.rs

i didn't revert the changes for debugging

Cleanup for #3035

---

libafl_qemu/librasan/Justfile
libafl_qemu/librasan/asan/Justfile
libafl_qemu/librasan/asan/build.rs
libafl_qemu/librasan/dummy_libc/Justfile
libafl_qemu/librasan/fuzz/Justfile
libafl_qemu/librasan/gasan/Justfile
libafl_qemu/librasan/qasan/Justfile
libafl_qemu/librasan/runner/Justfile
libafl_qemu/librasan/zasan/Justfile

Tiny fixes to make it build correctly.

librasan: tiny fixes to make it build

---

libafl/src/executors/hooks/inprocess.rs
libafl/src/executors/hooks/unix.rs
libafl/src/executors/hooks/windows.rs
libafl/src/executors/inprocess/inner.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/executors/inprocess/stateful.rs
libafl/src/fuzzer/mod.rs
libafl/src/state/mod.rs
libafl_qemu/src/executor.rs
libafl_targets/src/windows_asan.rs

The idea of putting crashing testcase into corpus simply doesn't work in practice

Partially Revert #3029 and #3053

---

fuzzers/binary_only/fuzzbench_fork_qemu/Justfile
fuzzers/binary_only/fuzzbench_qemu/Justfile

Fix wrong path in Justfile

---

fuzzers/fuzz_anything/baby_fuzzer_wasm/src/lib.rs
libafl/src/executors/inprocess/mod.rs
libafl/src/fuzzer/mod.rs

Fix metadata addition when solution is found

---

libafl/src/monitors/stats/manager.rs
libafl/src/monitors/stats/mod.rs
libafl/src/monitors/tui/mod.rs
libafl/src/monitors/tui/ui.rs
libafl_bolts/src/lib.rs

* Add the total execs to the overview at the top of the TUI.
* Pretty print big numbers in the TUI so you can see what they are at a glance.

Total execs

---

libafl_qemu/src/emu/usermode.rs
libafl_qemu/src/qemu/usermode.rs

@rmalmain 
like i said in discord on saturday. i need it to accept fd so that I can pass things from stdin

Make Qemu.mmap public and accept fd as the argument

---

fuzzers/inprocess/libfuzzer_stb_image_sugar/Justfile

It fails for no reason and it's annoying

 More stable `just test` for `libfuzzer_stb_image_sugar`

---

libafl_bolts/src/lib.rs
libafl_bolts/src/llmp.rs
libafl_bolts/src/shmem.rs
libafl_frida/src/asan/hook_funcs.rs
libafl_frida/src/pthread_hook.rs

Change ptr::eq to ptr::addr_eq where semantically more correct

---

Cargo.toml
bindings/pylibafl/Cargo.toml

upgrade pyo3 0.23.2 -> 0.24.0

---

libafl_qemu/librasan/asan/src/tracking/guest.rs
libafl_qemu/librasan/asan/tests/guest_tracking.rs
libafl_qemu/librasan/fuzz/fuzz_targets/guest_tracking.rs

Change GuestTracking to use a BTreeSet to remove performance bottleneck

---

libafl/src/executors/forkserver.rs

Didn't I remove this very bound just some in PR #2852 :)

Remove unecessary HasTargetBytes constraint

---

fuzzers/binary_only/frida_libpng/Justfile
fuzzers/binary_only/tinyinst_simple/Cargo.lock

#3123 can't be merged without removing portable simd

Fix tiny inst

---

libafl/src/executors/mod.rs
libafl/src/executors/nop.rs
libafl/src/stages/dynamic.rs
libafl/src/stages/mod.rs
libafl/src/stages/nop.rs

These are several QoL changes I have been using since very early libafl. The main purpose is for easier evaluation without adding a lots of features. For instance:
```
let stage = if enable_this_component {
DynamicStage::Stage1(...)
} else {
DynamicStage::Stage2(NopStage::new())
};
```
```
// Perform a single stage (the stage doesn't use executor bundled with fuzzer)
let mut corpus = InMemoryCorpus::new();
let sol = InMemoryCorpus::new();
let mut fb = ConstFeedback::new(false);
let mut obj = ConstFeedback::new(false);
let mut state = StdState::new(StdRand::new(), corpus, sol, &mut fb, &mut obj)?;
let mut fuzzer = StdFuzzer::new(QueueScheduler::new(), fb, obj);
let mut executor = NopExecutor::ok(); // Or we have to create some fancy executor
let mut mgr = SimpleEventManager::printing(); …
```

QoL Types and Changes

---

libafl/src/stages/nop.rs

NopStage::should_restart shall return false

---

libafl/Cargo.toml
libafl/examples/tui_mock/main.rs
libafl/src/corpus/minimizer.rs
libafl/src/events/broker_hooks/mod.rs
libafl/src/events/multi_machine.rs
libafl/src/events/simple.rs
libafl/src/events/tcp.rs
libafl/src/monitors/disk.rs
libafl/src/monitors/disk_aggregate.rs
libafl/src/monitors/logics.rs
libafl/src/monitors/mod.rs
libafl/src/monitors/multi.rs
libafl/src/monitors/prometheus.rs
libafl/src/monitors/stats/manager.rs
libafl/src/monitors/stats/user_stats/mod.rs
libafl/src/monitors/statsd.rs
libafl/src/monitors/tui/mod.rs
libafl/src/stages/concolic.rs
libafl_qemu/libafl_qemu_build/src/build.rs
scripts/clippy.sh

Use HashMap to manage ClientStat, Fix #3133

---

libafl/src/monitors/stats/manager.rs
libafl/src/monitors/stats/mod.rs
libafl/src/monitors/tui/ui.rs

Fix #3133 #2755

---

libafl/src/monitors/tui/ui.rs

Remove "global" prefix from TUI

---

fuzzers/binary_only/fuzzbench_fork_qemu/Cargo.lock
fuzzers/binary_only/fuzzbench_fork_qemu/Justfile
fuzzers/binary_only/fuzzbench_fork_qemu/src/fuzzer.rs

Fix cmplog for qemu fork executor

---

libafl/src/fuzzer/mod.rs

Make `InputFilter` public

---

libafl_bolts/Cargo.toml
libafl_bolts/src/minibsod.rs
libafl_targets/src/forkserver.rs

Update mach crate to maintained fork

---

libafl_bolts/src/ownedref.rs

bolts: Fix UB in Truncate trait

---

libafl_cc/build.rs
libafl_cc/src/common-llvm.h
libafl_cc/src/coverage-accounting-pass.cc

#3182 accidentally broke LLVM-15 and this PR fixes it.

Fix for LLVM-15

---

fuzzers/forkserver/fuzzbench_forkserver/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_cmplog/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_sand/src/main.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
libafl/src/mutators/token_mutations.rs
libafl/src/observers/cmp.rs
libafl/src/stages/afl_stats.rs
libafl_sugar/src/forkserver.rs
libafl_targets/src/cmps/mod.rs
libafl_targets/src/cmps/observers/aflpp.rs
libafl_targets/src/cmps/stages/aflpptracing.rs

Conform AFL struct casing to codebase/rust

---

libafl/src/stages/sync.rs

Add doc links to newly added load_callback return err

---

utils/gdb_qemu/gdb_qemu/src/child.rs

Looks like [this](https://github.com/AFLplusplus/LibAFL/commit/f901c2085d097df3bde8414fd6160a6481248a7c) guy got a bit over zealous with find and replace.

Fix gdb_qemu after spurious find-replace

---

.github/workflows/build_and_test.yml
utils/gdb_qemu/Justfile
utils/gdb_qemu/gdb_demo/src/args.rs
utils/gdb_qemu/gdb_qemu/src/child.rs
utils/gdb_qemu/gdb_qemu/src/exit.rs
utils/gdb_qemu/gdb_qemu/src/logger.rs
utils/gdb_qemu/gdb_qemu/src/main.rs
utils/gdb_qemu/gdb_qemu/src/parent.rs
utils/libafl_repo_tools/src/main.rs

* Add test for `gdb_qemu` to CI. Adding other utils should be simple once they have a suiable `Justfile` and `test` target in place.
* Fix the formatting for `gdb_qemu` and remove its exeption from `./scripts/fmt_all.sh`

Add CI for utils

---

libafl_bolts/src/fs.rs

The input file names will immediately clash if creating more than one `ForkserverExecutor` accepting `InputLocation::Stdin` (which is default). This PR fixes this by generating _really unique_ std input files.

Really unique std input file

---

.github/workflows/build_and_test.yml

Use nightly fmt

---

libafl_qemu/src/modules/usermode/snapshot.rs

* Fix issue with snapshots handling large reads when hooking `SYS_read`

Fix snapshots

---

fuzzers/binary_only/qemu_cmin/Justfile
fuzzers/binary_only/qemu_cmin/src/fuzzer.rs
fuzzers/binary_only/qemu_coverage/src/fuzzer.rs
fuzzers/binary_only/qemu_tmin/Justfile
fuzzers/binary_only/qemu_tmin/src/tmin_multi_core.rs
fuzzers/binary_only/qemu_tmin/src/tmin_single_core.rs
libafl_qemu/src/modules/usermode/mod.rs
libafl_qemu/src/modules/usermode/redirect_stdout.rs

Support re-directing the output for `qemu_cmin` and `qemu_tmin`

Add redirect stdout

---

.github/workflows/build_and_test.yml
fuzzers/binary_only/frida_windows_gdiplus/Justfile
fuzzers/inprocess/libfuzzer_stb_image/Justfile
libafl_qemu/libafl_qemu_build/src/build.rs
scripts/check_tested_fuzzers.sh

Improve CI

---

.github/workflows/build_and_test.yml
.github/workflows/ubuntu-prepare/action.yml

Use nightly for miri

---

.github/workflows/build_and_test.yml

No more no_std clippy

---

.github/workflows/build_and_test.yml
libafl_libfuzzer_runtime/Cargo.lock

NoStd Bolts

---

fuzzers/binary_only/qemu_launcher/tests/injection/test.sh
fuzzers/binary_only/qemu_launcher/tests/qasan/gasan_test.sh
fuzzers/binary_only/qemu_launcher/tests/qasan/qasan_test.sh

libafl_qemu_launcher: "fix" tests

---

libafl_nyx/build.rs
libafl_qemu/src/emu/builder.rs

May fix the docs issues described in #3280 (but I don't know how to test it)

Fix Docs for QEMU, Nyx

---

.github/workflows/build_and_test.yml
fuzzers/baby/tutorial/src/input.rs
fuzzers/binary_only/qemu_launcher/Justfile
fuzzers/full_system/qemu_baremetal/Cargo.toml
fuzzers/full_system/qemu_baremetal/Justfile
libafl/src/corpus/cached.rs
libafl/src/corpus/inmemory.rs
libafl/src/corpus/inmemory_ondisk.rs
libafl/src/corpus/ondisk.rs
libafl/src/corpus/testcase.rs
libafl/src/inputs/bytes.rs
libafl/src/inputs/mod.rs
libafl_frida/src/asan/asan_rt.rs
libafl_frida/src/helper.rs
libafl_qemu/src/command/mod.rs
libafl_qemu/src/command/parser/mod.rs
libafl_qemu/src/emu/drivers/mod.rs

Add CI for qemu i386

---

CONTRIBUTING.md

We have been auto-closing AI commits. Let's make that formal.

Clarify AI assistance rules in contributing

---

crates/libafl_asan/src/hooks/read/libc.rs
crates/libafl_asan/src/hooks/write/libc.rs
crates/libafl_asan/src/maps/entry.rs
crates/libafl_asan/src/maps/mod.rs
crates/libafl_asan/src/mmap/libc.rs
crates/libafl_frida/src/asan/asan_rt.rs

Clippy fixes for MacOS

---

Cargo.toml

Reverts AFLplusplus/LibAFL#3332

Revert "Update z3 requirement from 0.12.1 to 0.13.1"

---

crates/libafl/src/mutators/scheduled.rs

Call the `ScheduledMutator` fns of the wrapped mutator in `LoggerScheduledMutator`, to avoid overriding the wrapped mutators scheduling strategy.

Generalize `LoggerScheduledMutator` to work with any `ScheduledMutator`

---

crates/libafl/src/stages/calibrate.rs
crates/libafl_libfuzzer/runtime/src/lib.rs
crates/libafl_sugar/src/forkserver.rs
crates/libafl_sugar/src/inprocess.rs
crates/libafl_sugar/src/lib.rs
crates/libafl_sugar/src/qemu.rs
fuzzers/baby/baby_fuzzer_custom_executor/src/main.rs
fuzzers/baby/tutorial/src/lib.rs
fuzzers/binary_only/fuzzbench_fork_qemu/src/fuzzer.rs
fuzzers/binary_only/fuzzbench_qemu/Cargo.lock
fuzzers/binary_only/fuzzbench_qemu/src/fuzzer.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
fuzzers/forkserver/fuzzbench_forkserver/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_cmplog/src/main.rs
fuzzers/forkserver/fuzzbench_forkserver_sand/src/main.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs
fuzzers/full_system/nyx_launcher/src/instance.rs
fuzzers/full_system/qemu_baremetal/src/fuzzer_breakpoint.rs
fuzzers/full_system/qemu_baremetal/src/fuzzer_sync_exit.rs
fuzzers/inprocess/fuzzbench/src/lib.rs
fuzzers/inprocess/fuzzbench_ctx/src/lib.rs
fuzzers/inprocess/fuzzbench_text/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_cmin/src/lib.rs
fuzzers/inprocess/libfuzzer_libpng_tcp_manager/src/lib.rs
fuzzers/inprocess/libfuzzer_windows_asan/src/lib.rs

Reverts AFLplusplus/LibAFL#3356

Revert "Pass Handle to construct CalibrationStage"

---

crates/libafl/src/stages/calibrate.rs

Real fix for CalibrationStage

---

crates/libafl/src/common/nautilus/README.md
crates/libafl/src/common/nautilus/grammartec/context.rs
crates/libafl/src/common/nautilus/mod.rs
crates/libafl/src/common/nautilus/regex_mutator/mod.rs
crates/libafl/src/executors/command.rs
crates/libafl/src/stages/afl_stats.rs
crates/libafl_bolts/src/rands/mod.rs
fuzzers/baby/baby_fuzzer_custom_executor/src/main.rs
fuzzers/binary_only/qemu_launcher/src/instance.rs
fuzzers/forkserver/libafl-fuzz/src/fuzzer.rs

Fix AFLStatsStage

---

.github/workflows/build_and_test.yml
.github/workflows/fuzzer-tester-prepare/action.yml

TinyInst linux CI

---

crates/libafl/src/corpus/minimizer.rs
crates/libafl/src/schedulers/minimizer.rs
crates/libafl/src/schedulers/mod.rs
crates/libafl/src/schedulers/testcase_score.rs
crates/libafl_qemu/src/modules/drcov.rs
fuzzers/baby/tutorial/src/metadata.rs

Separate TestcaseScore into TestcasePenalty
